### ISSUE TITLE
Sweep background tests causing failures in internal product testing

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1004]
gerrit 280256
#872 #411 have resulted in problems for internal products.  The code they had to add to overcome this can be found in the above gerrit change.  We should revert or ignore the changes as necessary and revert this.

**Comment by hsaraogi** [comment]
Modify sweep so that it takes in the table picking heuristic and just drop the picked table.

**Comment by rhero** [comment]
Slightly confused, our tests are causing failures for another product team's tests? If they have fixes for our tests, then can we just cherry pick them? I think I'm missing something here.

**Comment by jboreiko** [comment]
In short, they extend our tests and run time internally.  But due to pollution in the backing store they are running against these tests fail.  So by committing them we had to ignore them in an internal product.

**Comment by rhero** [comment]
@jboreiko is this something we'll want to address when we enable background sweep by default? (#1118)

Will this only affect the one internal product, or might this be annoying for others as well?

**Comment by jboreiko** [comment]
Eh, this is just more to do with poorly abstracted code making it hard to write tests.  I would be happy to close this since it really amounts to refactor + test improvements that can be picked up if we choose to modify any of the background sweep code.  Which, for the record, we will likely end up doing once it is on everywhere and starts running in odd patterns that increase load on the boxes.
