### ISSUE TITLE
Single Node Down Cassandra startup possible regression 

### ISSUE THREAD

**Issue by glentakahashi** [palantir/atlasdb#1048]
It seems that somewhere between atlasdb 0.15.0 and 0.17.0 applications that use atlas fail to start up. In 0.15.0 they come up and spew warnings about a cassandra node being down, but in 0.17.0 it fails to start up complaining about schema consistency.

**Comment by jboreiko** [comment]
Proposed actions:
- add automated testing for 3-node cluster start up with only 2-nodes available
-- resolve any issues arising from writing these tests
- (Optional) track down the PR that regressed this functionality between 0.15.0 / 0.17.0, can't think of anything immediately suspicious in this time frame.

**Comment by jboreiko** [comment]
Being tackled in #1045

**Comment by harrybiddle** [comment]
An update on this issue: Clockfort has put up a fix. We are still reviewing the PR; I'll update this ticket when we merge it.

**Comment by harrybiddle** [comment]
The fix for this has been merged and will be included in our 0.23.0 release.
