### ISSUE TITLE
Define HA expectation for (Cassandra) KVS operations

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1075]
As per internal email thread titled: How should Atlas handle if cassandra nodes are down?

There should be testing and documentation detailing which KVS / Transaction capabilities are able to run against degraded clusters.  Currently the list of operations requiring a fully operation cluster appear to be:
- kvs.delete()
- kvs.truncateTable(s)()

We should confirm these are the only methods requiring all nodes.

A follow up to this would be to form recommendations to library users on how to handle the failure of these methods (if say for example an application is attempting a hard delete).

**Comment by tpetracca** [comment]
@gbrova as we discussed this a bit today

I think it would be nice for this spec to exist at the KeyValueService level and to provide methods that allow for non-blocking/non-critical-path execution of Non-HA tasks.  Basically I would find it interesting for there to be a kvs.bestEffortDelete() or some naming to that effect that we could call in operations where ideally we would delete something, but wether or not it succeeds doesn't actually matter.

There's a particular consumer internally using truncate() in a critical code-path that then makes it non-HA in Cassandra deployments.

And eh, maybe this is a terrible idea and it's entirely up to the consumer to implement that logic (which probably is reasonable).

**Comment by jboreiko** [comment]
Decided this was valuable for helping ourselves and products understand what we are capable of in a degraded state.  A goal for this would be both testing and documentation for the KVS api and communicating the results to teams so they can better understand their HA capabilities on Cassandra.  We don't consider this high enough priority for TODO, entering into backlog.

**Comment by rhero** [comment]
This is documented in our official docs here: https://palantir.github.io/atlasdb/html/configuration/multinode_cassandra.html.

Also in javadocs here: #1329.
