### ISSUE TITLE
Check we're the only people using the database

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/atlasdb#1082]
We should make sure that two applications aren't using the same database.

One potential fix:
- Check that all the tables have the correct prefix.

**Comment by clockfort** [comment]
I would impl this as "are there any other tables at all in my tablespace that are not in my table-metadata table"

I approve of this feature, but do know that you need to allow this condition or allow the user to specify that they want to allow this condition, as we have customer stacks with co-resident tables. For instance, most PG stacks would fall in this bucket.

**Comment by tpetracca** [comment]
Interestingly related to #1087 and just having smarter checks around schema'y things

**Comment by jboreiko** [comment]
We have encountered this a single time in the field.  We agree it would be valuable for people deploying the product but not currently convinced that it's worth the lift.
