### ISSUE TITLE
Impl KVS.deleteRange

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#1086]
Range Tombstones are supported in newer C*, and even more recently actually work. 

(This feature is also achievable for both the postgres and oracle syntaxes of DELETE, however I suspect the speedup is somewhat less from these, and coming just from doing less round trips, as I doubt they have a similar storage-level feature unless you happen to delete more than a DB block's worth of data; aka it should be 1 SQL delete call from from KVS perspective but still n mark-as-free-space operations on disk)

I believe that most all consumer workflows wouldn't need this feature, but sweep could readily use this feature;
sweep most of the time wants to delete all versions of an row less than some timestamp, and could issue a deleteRange mutation for the range encompassing the history of this row.

It would still have to be a three-part operation, where we:
- get the range in the actual table
- lookup transaction timestamps to find the most up to date committed version of a given row
- issue a deleteRange for the historical row versions up to (exclusive) the min(found_most_up_to_date_version, immutable_ts)

The most improved case would be rows that are heavily historied, whether it be from constant mutation or from not sweeping very often.

**Comment by clockfort** [comment]
I think this would also be a good project for someone new on the team, if you're ever spinning someone new up, since it's a quick and well-confined whirlwind introduction to the KVS impls and how sweep / transactions work.

**Comment by jboreiko** [comment]
Wondering what version we would have to be on to get this working?  Want to be careful about premature optimization and agree that this could be a good project for introducing someone to the product.

**Comment by clockfort** [comment]
The 2.2.x we currently ship is fine for this.

Agree, I might do a quickie benchmark when I have a second to see if it's worth the time to look into.

**Comment by rhero** [comment]
Sounds like it could be valuable, but given that Sweep isn't on by default yet, and generally performance of Sweep isn't terribly important, I'm going to mark this as a P2. Might make a newhire label though.
