### ISSUE TITLE
Check live schema against one stored in the KVS

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#1087]
@schlosna for SA [and because it was his idea]

Came up recently in relation to PDS-45978.  A consumer of atlas made a breaking change to their schema that resulted in a vague exception during regular product use.  By storing metadata about our schemas in the KVS we could catch errors related to schema changes on startup time, by checking if the schema version in the metadata matches the version atlas receives at runtime.

This would also be an interesting first step in the longer term [not currently being worked on] goal of providing easy ways to perform schema/table migrations.

**Comment by schlosna** [comment]
+ @gracew @bavardage @jared2501 as well.

**Comment by clockfort** [comment]
? Do you mean the things we currently store in the table metadata table ? There isn't too too much in most people's schemas outside of those.

I do agree though that the user should probably be alerted somehow, possibly in some stop-the-world way, when they issue a metadata change that is on-disk-format-incompatible with the existing one.

**Comment by tpetracca** [comment]
I honestly have no idea what we actually store in the metadata table, but it sounds like it.

**Comment by jboreiko** [comment]
Should have just about everything we need to implement this without on disk changes
```
public class TableMetadata implements Persistable {
    final NameMetadataDescription rowMetadata;
    final ColumnMetadataDescription columns;
...
```

**Comment by jboreiko** [comment]
"This has made it on to our weekly plan" - robert "Cubs" hero
