### ISSUE TITLE
Investigate test failure on develop

### ISSUE THREAD

**Issue by ashrayjain** [palantir/atlasdb#1088]
Investigate why shouldCreateTablesConsistentlyWithMultipleCassandraNodes in CassandraSchemaLockTest fails to complete within 4 mins.

https://circleci.com/gh/palantir/atlasdb/3699

**Comment by jboreiko** [comment]
@rhero to link to internal pds ticket.  He will then close.

**Comment by rhero** [comment]
I had suspected that this was related to the schema mutation lock issues that we've been seeing where we fail to finish making all the service-specific tables, but that does not appear to be the case here. The relevant logs are here:

- [CassandraSchemaLockTest.xml](https://3699-36960637-gh.circle-artifacts.com/4/tmp/circle-junit.7eik8XF/junit/TEST-com.palantir.cassandra.multinode.CassandraSchemaLockTest.xml)
- [cassandra1.log](https://3699-36960637-gh.circle-artifacts.com/4/home/ubuntu/atlasdb/atlasdb-cassandra-multinode-tests/container-logs/cassandra1.log)
- [cassandra2.log](https://3699-36960637-gh.circle-artifacts.com/4/home/ubuntu/atlasdb/atlasdb-cassandra-multinode-tests/container-logs/cassandra2.log)
- [cassandra3.log](https://3699-36960637-gh.circle-artifacts.com/4/home/ubuntu/atlasdb/atlasdb-cassandra-multinode-tests/container-logs/cassandra3.log)

It looks like all three nodes successfully load all of the relevant tables and are `Listening for thrift clients...`, and the client side logs have errors constructing a Cassandra client, but those go away completely once the three nodes are up. Nothing is logged in any of the Cassandra nodes for three minutes and then the test ends with some docker looking errors.

We are constantly creating a "new client for cassandra[123]:9160/atlasdb as user cassandra..." for a couple of minutes, but it's not clear to me that anything is actually wrong from an AtlasDB side. In my non-expert opinion, I think this looks like a docker induced flake.

**Comment by rhero** [comment]
Not sure if we want to add this to a list of other flakes, but I'm pretty sure this isn't the same issue we've seen in only two other places. Generally in favor of closing this.

**Comment by rhero** [comment]
After looking at the logs locally (because chrome is terrible at displaying these), it looks like we blacklist cassandra2 and cassandra3 multiple times before they're up and running, but then they start and the errors go away. There's a big gap between these two log lines in CassandraSchemaLockTest.xml:
```
10:12:52.376 [pool-20-thread-4 calling cassandra host cassandra1:9160 started at 2016-10-19T10:12:52.349Z - 13] DEBUG c.p.a.k.c.CassandraClientPoolingContainer - During org.apache.cassandra.thrift.Cassandra$Client@76d353e5 check-in, cleaned up a read buffer of 133 bytes
10:13:33.116 [commons-pool-EvictionTimer] DEBUG c.p.a.k.c.CassandraClientFactory - Created new client for cassandra3:9160/atlasdb as user cassandra
```

And it's in that time window that Cassandra 2 and 3 come up. Following that there are three minutes of client logs that look like the following while Cassandra logs nothing.
```
10:14:33.423 [commons-pool-EvictionTimer] DEBUG c.p.a.k.c.CassandraClientFactory - Created new client for cassandra2:9160/atlasdb as user cassandra
```

**Comment by rhero** [comment]
Closing out as this doesn't seem related to the internal support ticket, and it's unlikely we'll dig into this further. This also may be related to some recent fixes to how we blacklist hosts.
