### ISSUE TITLE
Postgres DbKvs silently truncates table names to 63 characters

### ISSUE THREAD

**Issue by tjwilson90** [palantir/atlasdb#1092]
Oracle is polite enough to fail if you try to create a table with more than 30 characters. Postgres will instead silently truncate to 63 characters.

This is mostly ok as long as the truncation doesn't cause any conflicts. Any attempts to interact with the table will truncate the table name and always find the right table.

If there is a conflict, this causes much badness.

**Comment by clockfort** [comment]
See also #747 ; likely these should have the same fix.

**Comment by jboreiko** [comment]
Moving this to #747 and closing.
