### ISSUE TITLE
atlasdb-config should not depend on Dropwizard libraries

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#1106]
This week Vidit had a tonne of classpath fun where the root cause was atlasdb-config depending on Dropwizard (incompatibilities between Dropwizard 0.9 and Dropwizard 1.0).

This made Intellij pick up two versions of dropwizard-jackson (one for 0.9 and one for 1.0) and cause execution to fail in exciting ways.

AtlasDB probably shouldn't be taking an explicit Dropwizard dependencies - or more generally, should be aiming to minimise the impact of diamond dependencies (probably by not depending on 0.x libraries?).

**Comment by SerialVelocity** [comment]
This is so we can pull in `DiscoverableSubtypeResolver` and `Jdk7Module` in `AtlasDbConfigs`. The latter can be fixed by pulling in the jackson library but the former is dropwizard specific.

**Comment by jboreiko** [comment]
Can't bump to 1.0 because it would cause problems for downstream consumers.  To overcome this, we can instead shadow this small dep on dropwizard.  If you feel this need to be worked on this week or next please let us know, otherwise it will be placed in the backlog.

**Comment by tpetracca** [comment]
We don't have to use `DiscoverableSubtypeResolver`, we can use Jackson's `StdSubtypeResolver`, which would then require annotating are abstract classes (using the jackson deserialization) with `@JsonSubTypes`

**Comment by gmaretic** [comment]
Fixed by #3218
