### ISSUE TITLE
Unintuitive behavior with timestamp cli

### ISSUE THREAD

**Issue by ashrayjain** [palantir/atlasdb#1116]
Currently, running the timestamp fetch cli outputs the timestamp in the Multipass logs instead of the cli output! There is a `file` option that outputs it to a file instead which will work for rescue but we should definitely consider documenting the default behavior which is quite unintuitive.

Also, we may eventually want to fix this behavior by using `System.out` instead of logging the timestamp.

@SerialVelocity @rhero

**Comment by tpetracca** [comment]
I thought about using System.out but figured the logging for the product could just be modified to make the log statement hit stdout.  Open to just directly hitting stdout though (in addition to logging)

**Comment by jboreiko** [comment]
We can switch outputs to System.out() since we can't control the logging methodology when deployed (in particular dropwizard).

**Comment by tpetracca** [comment]
I'd argue we should *add* System.out, and not remove the logging

**Comment by jboreiko** [comment]
I believe we are in agreement, it doesn't appear we can have enough control over the logging in order to properly utilize console appenders where we need them (for the clis).  I would imagine this will require us to modify our checkstyle to have a bypass flag for authorized system.{out, err}.print
