### ISSUE TITLE
Enable background sweep job by default

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1118]
We have been working towards this but we don't have an actual ticket tracking the issue. To enable background sweep by default we need to finish work on the backup lock (#852) and do some integration testing of backups with sweep.

Backup lock PR is here: #1011. Then we need to add additional testing once we have a fully automated backup solution.

High level benefits of sweeping can be found on our [docs](https://palantir.github.io/atlasdb/html/cluster_management/sweep.html).

**Comment by rhero** [comment]
Blocked on the new backup lock impl #1400.

**Comment by gsheasby** [comment]
We should probably compile a list of sweep tickets that need fixing before we can make this call.

#1537, #1564, #1563, #1523, #982 - any others?

**Comment by gsheasby** [comment]
(Discussing offline)
The main issue is that should not be able to take down Cassandra: #1563. The rest aren't hard blockers, but would just improve our confidence in background sweep.

**Comment by gsheasby** [comment]
No longer blocked. Initial testing has been successful and we are ready to continue with a controleld rollout across internal products.

**Comment by hsaraogi** [comment]
Blocked on rolling out on internal navigation product.

**Comment by hsaraogi** [comment]
Blocked on #1976 and getting sane defaults from the internal fruit deployment.

**Comment by gsheasby** [comment]
#1976 merged. Do we have sane defaults yet?

**Comment by fsamuel-bs** [comment]
Solved by #2104.
