### ISSUE TITLE
Oracle Table name mapping might collide

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1120]
We want to map table names to meet Oracle length limits of 30 characters.

This is the mapping function: (does not change the name if it is already in the 30 character limit)
1. Drop vowels from table name (As few as neccessary).
2. Truncate if (prefix + table_name) it is still more than 25 characters.
3. Append a 5-character SHA256 hash of the tablename.

Pros:
1. We do not need to store the table name mapping as it is deterministic and there is no complexity of caching.
2. The probability of collision is about 1 in 50 million (as calculated by @gsheasby).

Cons:
1. If there is collision in hashed table names, there is no way of knowing if it was a call to `createTable(x)` multiple times or there was a collision. Reads and writes might work with an old table especially if there were dynamic columns. 
2. `createTable` becomes unsafe as it does not guarantee that the table was created and might give an illusion that it exists.

Partial solution:
1.  We can validate Schemas for mapping collisions before schema generation. However, there might be tables on disk created from old schemas, kept around for rollback. @j-baker, does the internal product delete schemas on upgrade tasks?

@clockfort @rjullman : Any ideas if these issues can be resolved in a simple manner (i.e. without persisting table names and having caching around that)?

**Comment by clockfort** [comment]
No, I think all ideas would require persisting and caching table names to solve this problem.

**Comment by hsaraogi** [comment]
How about having deterministic table mapping and just storing it in a table that has long_name as primary key and short_names as unique(enforced by the unique constraint)? This will: 
1. fail table creation due to unique violation if any two different name hashes collide
2.  provide an easy way to look at the table name mapping
3. We would not need a table lookup each time we insert or select
@jboreiko @clockfort

**Comment by clockfort** [comment]
Yes, this seems like an okay solution, where collisions can still happen but the user knows when it happens and it stops the world. (and it's so unlikely to happen that it's not a big deal anyways)

**Comment by gsheasby** [comment]
Will be solved by #1076 - after some discussion, we have decided to treat long tables like this:
1 - truncate the table name to 25 chars
2 - append a sequence number (maintained per "first 25 characters of a table name"), persisted by the table mapping table

Caching will not be added unless it provably adds performance benefit.

**Comment by gsheasby** [comment]
Closing as shouldn't be an issue due to the chosen implementation of #1076.
