### ISSUE TITLE
CassandraClientPool#handleException doesn't blacklist a host on which a final attempt triggers a connection exception

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1135]
Found when having a look at the retry logic for #885.
If the final attempt of running something with CassandraClientPool#runWithRetryOnHost() fails, we will call handleException() with numTries = MAX_TRIES_TOTAL. But we throw an exception out of the if-block (line 506 or 509), and the host in question is not added to the blacklist even if the exception was a connection exception, which seems inconsistent.

**Comment by fsamuel-bs** [comment]
With the current `CassandraRequestExceptionHandler`, I think this works as intended, as the `numTries = MAX_TRIES_TOTAL` is the `MAX_TRIES_TOTAL + 1`th attempt, which means we should fail.
