### ISSUE TITLE
AtlasDB clients cannot communicate via load balancers

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1146]
As a user of an AtlasDB product, I would like to put my product into HA configuration, with each client communicating via load balancers. This would be useful when setting up AtlasDB product in a cloud environment with custom certificates, as it makes the management of those certificates easier.

Here is one example of where this breaks:

1. The AtlasDB leader is killed
2. When another node wants a timestamp, it continues to ask the load balancer for the old leader, since this is cached in our remote proxy
3. The load balancer responds with a 503
4. The node asking for the timestamp doesn't consider this a retriable exception, and propogates the error up to the user, instead of trying another one

(The above case may also be a reproducer of #1000, discovered by @ungureanuvladvictor).

We can resolve the above case by making 503 a retriable exception, but we also need to take care to ensure that we don't introduce performance issues.

There may be further issues that we encounter.

**Comment by harrybiddle** [comment]
@tpetracca - you mentioned yesterday that AtlasDB clients shouldn't be communicating to each other via load balancers.

Can you give any specifics of what will break? Do you think AtlasDB should support this?

**Comment by tpetracca** [comment]
The fetching of timestamp is a performance critical operation. We need to minimize the amount of time we spend actually communicating with the timestamp services themselves. We can't make any guarantees about how a load balancer will choose where to send requests, not to mention that the load balancer himself is an additional network leg to jump through.

In an ideal world (read: not today's reality) we'd have a client that was smart about who it sent fresh-timestamp requests to. If I have timestamp services A, B, and C, A is currently the leader, and all services are online, then technically a request to any of A, B, or C will return a valid timestamp, but a request to A will do so significantly faster than B or C will.  If a request to B or C is able to tell us where the leader is (or just returns a 503) then we can make the client adjust all future queries to the actual leader.

The idea is that non-leader requests are expensive (and would be frequent if we interacted with a load balancer).

**Comment by tpetracca** [comment]
So as it relates to this issue, my guess is we actually do want to make 503 a retry-able error.  In the case that we have A, B, and C, A is the leader, and B is down (which is a valid state to be in, yay highly available!) then a request to B will result in a 503. We should retry the request against the next timestamp uri in our list.

**Comment by gsheasby** [comment]
So in other words, the ticket title should go back to "503 should be retriable", but without all the jazz about load balancers? Separately, do we want to give advice about _how_ to run Atlas in an HA configuration (e.g. don't use load balancers)?

**Comment by harrybiddle** [comment]
Sorry - I should clarify: the motivation for changing the title of this issue was to make explicit the need to run AtlasDB behind load balancers. In particular, I'm concerned that there might be more than just the 503 problem lurking around the corner: this could expand into many more problems. I considered the load-balancer issue to be the more important/urgent/encompassing issue to track, rather than just 503's, and so expanded the scope of this ticket.

**Comment by tpetracca** [comment]
We should indeed give advice about how to run Atlas in HA mode.

**Comment by harrybiddle** [comment]
Closed: AtlasDB now always retries if the server responds with a 503, regardless of whether there is a Retry-After header.

**Comment by jboreiko** [comment]
Has this been confirmed in practice?  And more generally is that internal stack up and running with the load balancers?

**Comment by harrybiddle** [comment]
@jboreiko I thought it was deployed, but I've just found out it isn't yet! I'm re-opening this until it's been confirmed in use. Confirmation so far is in the form of wiremock tests and through some manual testing of the timelock server; but neither of those were using load balancers. No intentions to put load balancers on the internal stack.

**Comment by ungureanuvladvictor** [comment]
Tested on our internal stack. Things worked as advertised.

**Comment by harrybiddle** [comment]
Closing out
