### ISSUE TITLE
Support Cassandra 3.7

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1147]
Per http://cassandra.apache.org/download/, Cassandra 2.2 is EOL'd this month, and Cassandra 3.0.X ends support in spring of next year. We'd like to target Cassandra 3.7 as the next version we do testing against and recommend for customers.

We should move our testing to this version and product a 3.7 Cassandra docker image for internal products to do testing against.

**Comment by gsheasby** [comment]
Will be fixed by #1206
