### ISSUE TITLE
Stream store needs to stream when loading items larger than inMemory limit

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1150]
One of our internal products noticed poor performance when fetching large object from the stream store.  After a bit of work and some perf logging / code diving we found the stream store does not 'stream' objects when loading.  It loads objects into a temp file and returns an input stream to this temp file.  The offending lines can be found here: https://github.com/palantir/atlasdb/blob/d2a038cb131153c4a701ee0fa231d6e872081144/atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractGenericStreamStore.java#L68-L81

This results in the call blocking on the full load of the object into the temp file (which for a dockerized cassandra-backed setup resulted in about a 45 second load of a 700MB object).

A resolution here would be to create an InputStream impl that lazily fetches blocks from the backing store.  As noted by @NeilRickards it might be valuable to wrap this returned InputStream in a BufferingInputStream to ensure some of the blocks are fetched initially since most impls will assume fast response from interacting with the method when under the inMemoryThreshold.

**Comment by jboreiko** [comment]
@clockfort, @tmgordeeva for SA

**Comment by clockfort** [comment]
Yep, I could see someone wanting that.
If you're going to make a change to make it actually stream both to and from all the way to the user on the massively oversized stream load case, it'd be preferable if you don't make it temp-file-backed at all and just keep an IN_MEMORY_THRESHOLD portion at a time in memory.

**Comment by gsheasby** [comment]
Adding brief notes of a chat with @NeilRickards about expected functionality. @jboreiko, thoughts?

    * Currently, loadStream loads everything in one transaction. Getting first byte can time out
    * Getting first byte should be fast, ergo loadStream should only a pointer to the stream in the first transaction. Other reads are done in subsequent “transactions”
    * If the value is overwritten (i.e. key -> v1 and now also key -> v2), streaming should continue + complete. If the master transaction is serialisable, txn should fail
    * Delete should be prevented while the master transaction is still open (reading)

**Comment by gsheasby** [comment]
Solved by #1341.
