### ISSUE TITLE
Cannot Initialise KVS Immediately After Killing Cassandra

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1154]
During testing, I found that if I have a three-node Cassandra cluster, and I kill one node then immediately construct a KVS, the KVS construction fails.

**Comment by rhero** [comment]
Closing this until it becomes an issue during testing or actually occurs with customers.

**Comment by tpetracca** [comment]
Didn't it get fixed by clock's most recent changes anyway? @clockfort @harrybiddle
