### ISSUE TITLE
Codegen should discourage `SELECT *`

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#1169]
If you have a table with many columns, the codegen should encourage you to specify a column selection when calling `getRow`, `getRows` etc. Possibly by deprecating the methods that don't take a column selection.

This could avoid over-fetching (and the latent perf issues that come with over-fetching)

**Comment by hsaraogi** [comment]
@jboreiko

**Comment by rhero** [comment]
It seems like a valid use case for people to select all of the columns of a row, so I don't know if it makes sense to deprecate the method. How were you thinking of us discouraging the use of this in practice (or highlighting the use of the other ways to fetch rows)?

**Comment by leeavital** [comment]
> It seems like a valid use case for people to select all of the columns of a row, so I don't know if it makes sense to deprecate the method. How were you thinking of us discouraging the use of this in practice (or highlighting the use of the other ways to fetch rows)?

I'm not sure about the relative frequencies of when want to avoid selecting all columns and when you want to select all columns. What I'm concerned about is inadvertently adding a large column (e.g. if I'm storing long form text) which can be slow to retrieve. Another solution would be excluding certain columns from being "implicitly selected", and only having those tables omit the `getRows()`  method.

**Comment by gsheasby** [comment]
Is there a specific instance where over-fetching happened and was harmful?

**Comment by leeavital** [comment]
We had one instance where a table had two columns, let's say left and
right. Left was always pretty small. Right could grow to be pretty large
(say on the order of a few MBs).  We have a bunch of code that fetches
left, but most it accidentally fetched right as well. This would up slowing
things down, and in really bad cases wound up crashing because we assumed
fetching many lefts at once would not take up a bunch of memory.

**Comment by rhero** [comment]
Hey Lee,

I don't see us getting to this anytime soon. There doesn't seem like a concrete way of detecting when a use of `select *` is intended vs unintended. I think we're going to rely on schema reviews and talking directly with teams to identify when people are misusing this API.

-Robert
