### ISSUE TITLE
How to KVS Migrate Live

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#1185]
It's unclear how to do a KVS migration online, or if it's even possible given the current state of the KvsMigrationCommand.

**Comment by jboreiko** [comment]
It appears that it's not too far from being possible.  It currently could accept a configuration pointing it to a running atlasdb client.  And from there it range scans tables in batches copying the chunks over to the to kvs at the migration timestamp.  I guess the final portion that appears to be missing is how do you account for the writes that came after the migration started and were missed in the initial range scans.  Would be interested in knowing how this works for our large internal product @tmgordeeva @clockfort

**Comment by clockfort** [comment]
how it works in our product is

during migration:
- writes go to old kvs + new kvs
- reads come from old kvs
- backfilling the new kvs with old kvs data ranges as you described

after migration:
- writes go to new kvs
- reads go to new kvs

**Comment by jboreiko** [comment]
Hmm, this will move us away from the cli migration functionality as the running application needs to be aware the migration is occurring.  This would appear to be quite a bit of work.  Next steps would be to collect a priority on this @rhero

**Comment by rhero** [comment]
Sorry, not sure if I understand - are there any code changes to allow live migrations (as specified by clockfort)? If it's just a point of documentation, then we can do this, but as Tom has noted before in conversations, the offline migrations happen quickly enough that there's not a ton of value of doing it online. 

I'm labeling this as a P2, but we should probably explicitly document if this needs to happen offline or not.

**Comment by rhero** [comment]
Chatted with folks about this, and we don't think it's possible to do an online migration right using strictly OSS AtlasDB. We think PG uses a bit of special migration logic that isn't portable. 

I'll add a docs note that we don't support doing live migrations and then close this out. I don't think we need to support live migrations until KVS migrations start to take a lot of time (for most services this happens very quickly).

**Comment by rhero** [comment]
Fixed in #1221.
