### ISSUE TITLE
AtlasDB should publish a runnable dist for atlasdb-cli

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1196]
As a simple short term solution we should publish a runnable AtlasDB cli to Bintray.  This would be very benificial to teams / people attempting to debug older AtlasDB clusters that do not have functioning dropwizard bundle support.

**Comment by tpetracca** [comment]
+100000

**Comment by rhero** [comment]
This is done: https://bintray.com/palantir/releases/download_file?file_path=com%2Fpalantir%2Fatlasdb%2Fatlasdb-cli-distribution%2F0.27.0%2Fatlasdb-cli-distribution-0.27.0.sls.tgz

It's slightly annoying to navigate to https://bintray.com/palantir/releases/atlasdb and then go to Files, atlas-cli-distribution, <your-version>, but it's there!
