### ISSUE TITLE
Remove RocksDB and JDBC KVSs

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1198]
We aren't supporting these KVSs and are actively trying to move people away from them. Once all the internal services have removed dependencies for these KVSs, we are going to actually remove the functionality from AtlasDB.

Filed primarily for tracking. Tentatively planning to remove these KVSs by March 2017.

**Comment by jugaadi** [comment]
@rhero Any particular reason we are abandoning support for JDBC KVSs?

**Comment by rhero** [comment]
@jugaadi mostly to standardize configurations in which people can deploy AtlasDB and reduce the surface area we need to support. We're choosing DBKVS as the preferred KVS impl for Postgres/Oracle primarily for two reasons:
- far more customers have deployed services on DBKVS, and migrating those customers off of DBKVS is very costly
- JDBC has more complexity and we have less control of how it works. It's a hand wavy argument because I'm not intimately familiar with details, but that's how it was explained to me.

At this point, there are very few customers using JDBC, so we want to eliminate the possibility of issues arising with it, and give people the final nudge to migrate to DBKVS.

**Comment by tpetracca** [comment]
Any thoughts on when we're actually going to cut these out?

**Comment by rhero** [comment]
I think we're waiting for a product who may still has a few customers using RocksDB to 3.0, then they're going to remove it, and we're planning on removing it shortly after. JDBC we could probably remove now that we've unblocked a product who relies on dynamically created tables #1350. I'm not aware of anybody who's actually migrated to DBKVS though for that product though, so there may be other issues.

@j-baker - do you you guys know when you'll feel comfortable removing RocksDB support entirely?

@carrino or @twilson-palantir - Do you have any thoughts on removing the JDBC KVS?

**Comment by tjwilson90** [comment]
You could have removed them long ago. Anyone who absolutely needs these can just fork them from atlas. That was part of the point in making the kvs service loaded.
