### ISSUE TITLE
Include core tests for AtlasConsole operations

### ISSUE THREAD

**Issue by tkleingarn** [palantir/atlasdb#1204]
We have basically zero test coverage for AtlasConsole in atlasdb

We should increase test coverage for generic console operations.

These should not be specific to a particular schema for a given product, and should live in atlasdb.

**Comment by gsheasby** [comment]
There is an ETE test, `DropwizardEteTest`, that tests that Console starts up. We're happy to accept further tests covering different commands, but will not be prioritising this ourselves yet.
