### ISSUE TITLE
Add tests to ensure that the we do not change the dependency footprint accidentally 

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1213]
We can probably port internal classpath tests.

**Comment by gsheasby** [comment]
@SerialVelocity has a magic script for this, in `scripts/get-dependency-diff.sh`. We could automate this - but would probably have to check in a "dependency footprint" file.

**Comment by jboreiko** [comment]
We should also confirm a gradle plugin doesn't already exist for this use case.  Dan fox was mentioning they had a dependency lock file that would accomplish the same end.

**Comment by jboreiko** [comment]
called nebula lock file - https://github.com/nebula-plugins/gradle-dependency-lock-plugin

**Comment by iamdanfox** [comment]
There are a variety of ways to use this plugin, but in our repo we check in the .lock files which gradle then uses to source dependency versions (using the nebula gradle dependency recommender plugin).

As an example, http-remoting checks in [lock files][1] and fails your build if they're out of date using a [`verifyDependencyLocksAreCurrent` task][2]

[1]: https://github.com/palantir/http-remoting/blob/develop/tracing-okhttp2/versions.lock
[2]: https://github.com/palantir/http-remoting/blob/97d2619c7d6f99593a7416f8a7287d2978be8c6b/build.gradle#L58

**Comment by rhero** [comment]
Fixed by #1418 .
