### ISSUE TITLE
Log or alert when fetching a lot of bytes from Cassandra

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1217]
Notify (e.g. via more log messages, or better still, a nagios alert) when values successfully returned are dangerously high.

We may want "dangerously high" to be configurable.

There's already a log message in SnapshotTransaction: `com.palantir.atlasdb.transaction.impl.SnapshotTransaction: A single get had quite a few bytes:` - do we want anything else?

**Comment by gsheasby** [comment]
Need to ensure that our internal log collection scheme will pick this up, and that the log message doesn't leak any sensitive information.

**Comment by tpetracca** [comment]
I'm not worried about a lot of bytes in a single get (as you not SnapshotTransaction already logs this) so much as a lot of bytes in a single row or cell.

**Comment by clockfort** [comment]
+1 , mostly care about many bytes per single cell as handling for these is especially egregious in C*

FWIW also, besides the warning I wrote in SnapshotTransaction, there are a few different C* side warnings for similar things.
https://issues.apache.org/jira/browse/CASSANDRA-10876?focusedCommentId=15153282&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15153282

**Comment by jboreiko** [comment]
Do we want to focus only on C* kvs or should we just through these warnings into Cell.java.  Anytime you create one over our limits you get WARNs (would hit all get/put paths).

**Comment by tpetracca** [comment]
I think we do this at the C* level, given the issues we're looking for are specifically related to things we know Cassandra itself will be upset with.
