### ISSUE TITLE
StreamStore has inconsistent handling of nonexistent IDs

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#1228]
The `StreamStore` throws an exception if you call `loadStream` with a nonexistent ID. However, the existence check is bypassed when calling `loadStreams`, and the entry is simply omitted from the returned map.

Not sure if this is actually a bug or intended behavior - but IMO it should be consistent (either both throw, or loadStream returns Optional).

**Comment by gsheasby** [comment]
I'm currently working on fixing up the loadStream(s) methods - this looks like a tiny bug that I could quickly fix while I'm here. Thanks for filing!

**Comment by gsheasby** [comment]
We don't want to break the API of loadStream, but we can phase this out. Moving forward:
* loadStream will become deprecated
* a new method, loadSingleStream, will return Optional<InputStream>
* loadStreams will work as before.
