### ISSUE TITLE
Fix/suppress findbugs warnings from the new findbugs plugin

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1230]
We added a findbugs plugin (http://kengotoda.github.io/findbugs-slf4j/) to ensure secure logging syntax. The plugin detects a bunch of findbugs check failures which are not always log related. 

The branch : https://github.com/palantir/atlasdb/tree/gr/logging.

@griechel for SA.

**Comment by gsheasby** [comment]
Looks like this merged in #1298. Closing out.
