### ISSUE TITLE
Idle Cassandra Client Pool Consantly Re-Establishing Connections

### ISSUE THREAD

**Issue by jnelson15** [palantir/atlasdb#1233]
When services are running idle, a not insignificant amount of time is spent re-establishing Cassandra connections and setting the keyspace, causing load and context switching since much of this is in kernel mode:
```
BasePooledObjectFactory.java:60 com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create() 108 1
CassandraClientFactory.java:51 com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.create() 108 1
CassandraClientFactory.java:77 com.palantir.atlasdb.keyvalue.cassandra.CassandraClientFactory.getClient(InetSocketAddress, CassandraKeyValueServiceConfig) 108 1
CassandraClientFactory.java:91 org.apache.cassandra.thrift.Cassandra$Client.set_keyspace(String) 108 1
```
It's not clear where the connections are being terminated (Cassandra hosts apparently close idle connections after 30 seconds but not sure how this relates to open connections), but maybe we can implement some type of heartbeat to keep the connections in our pool alive?

<img width="1093" alt="atlas-connections" src="https://cloud.githubusercontent.com/assets/4187816/20433679/acd9bb5e-ad9c-11e6-9793-b6737e81eda2.png">

**Comment by clockfort** [comment]
I wrote up a really good writeup of the rather complicated logic around this last time I went through the code, and put it in a comment in `CassandraClientPoolingContainer`

```
    /**
     * Pool size:
     *    Always keep {@code config.poolSize()} (default 20) connections around, per host.
     *    Allow bursting up to poolSize * 5 (default 100) connections per host under load.
     *
     * Borrowing from pool:
     *    On borrow, check if the connection is actually open. If it is not,
     *       immediately discard this connection from the pool, and try to take another.
     *    Borrow attempts against a fully in-use pool immediately throw a NoSuchElementException.
     *       {@code CassandraClientPool} when it sees this will:
     *          Follow an exponential backoff as a method of back pressure.
     *          Try 3 times against this host, and then give up and try against different hosts 3 additional times.
     *
     *
     * In an asynchronous thread:
     *    Every approximately 1 minute, examine approximately a third of the connections in pool.
     *    Discard any connections in this third of the pool whose TCP connections are closed.
     *    Discard any connections in this third of the pool that have been idle for more than 3 minutes,
     *       while still keeping a minimum number of idle connections around for fast borrows.
     *
     */
    private GenericObjectPool<Client> createClientPool() {
        CassandraClientFactory cassandraClientFactory = new CassandraClientFactory(host, config);
        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();

        poolConfig.setMinIdle(config.poolSize());
        poolConfig.setMaxIdle(5 * config.poolSize());
        poolConfig.setMaxTotal(5 * config.poolSize());

        // immediately throw when we try and borrow from a full pool; dealt with at higher level
        poolConfig.setBlockWhenExhausted(false);
        poolConfig.setMaxWaitMillis(config.socketTimeoutMillis());

        // this test is free/just checks a boolean and does not block; borrow is still fast
        poolConfig.setTestOnBorrow(true);

        poolConfig.setMinEvictableIdleTimeMillis(TimeUnit.MILLISECONDS.convert(3, TimeUnit.MINUTES));
        // the randomness here is to prevent all of the pools for all of the hosts
        // evicting all at at once, which isn't great for C*.
        poolConfig.setTimeBetweenEvictionRunsMillis(
                TimeUnit.MILLISECONDS.convert(60 + ThreadLocalRandom.current().nextInt(10), TimeUnit.SECONDS));
        // test one third of objects per eviction run  // (Apache Commons Pool has the worst API)
        poolConfig.setNumTestsPerEvictionRun(-3);
        poolConfig.setTestWhileIdle(true);

        poolConfig.setJmxNamePrefix(host.getHostString());

        return new GenericObjectPool<>(cassandraClientFactory, poolConfig);
    }
```

The solution I propose would be to examine a smaller ratio (currently 1/3rd, could make it 1/10th or something) of connections at a time, and maybe change the frequency to be slightly more often than is current.
aka, in order to be a better neighbor to other processes on both this box and Cassandra, do less work more frequently rather than doing more work less frequently.

That said, the only thing that actually creates new connections like how you're seeing is people doing queries and actually attempting to use connections (more connections than the pool has currently) so maybe what you actually want is just for the connection pool to have a higher minimum number of connections at idle, or a longer period of time before the bursted-up extra connections we create here get gradually closed so that we settle down back to the normal level of connections much slower. (Currently if you did a lot of work and bursted up your connections pool, within 3 minutes-ish you'd fall back down to normal connection levels; I think this is reasonable, but I don't know everyones' workloads)

Does this make sense / jive with what you're seeing on your stack?

**Comment by jnelson15** [comment]
Yeah that makes sense. So basically if you have an application that is bursty in the sense that it sporadically uses a lot of connections then you'd want to jack up the pool size so that you reduce the frequency that you're going over the idle size? What's the benefit of having the max idle 5x the min rather than just increasing the minimum? I imagine some type of resource constraints but if you can handle 5x under load it seems that could be some benefit to keeping them around.

I like the idea of doing less work more often. Seems like it would smooth out load for weird cases like we're seeing.

**Comment by clockfort** [comment]
> So basically if you have an application that is bursty in the sense that it sporadically uses a lot of connections then you'd want to jack up the pool size so that you reduce the frequency that you're going over the idle size?

Yes.

> What's the benefit of having the max idle 5x the min rather than just increasing the minimum? I imagine some type of resource constraints but if you can handle 5x under load it seems that could be some benefit to keeping them around.

Yes, and also more generally if you have multiple co-operating connectees to your C* cluster this form of pool swelling will leave the C* cluster happier unless there are periods of bursty usage shared between both connectees.
There is also thread and system-resource usage on the connectee that is improved by idling at a lower number of connections (the pool size is per node, so a connectee attached to a 10 node C* cluster could use a default of (20 * 10 = 200 connections) at idle)

> I like the idea of doing less work more often. Seems like it would smooth out load for weird cases like we're seeing.

You could try upping your pool size up and seeing if it improves your situation, and if it does we can either change the default Atlas settings your application sets for itself, or change the defaults in AtlasDB if this is believed to be a more general problem.

**Comment by jnelson15** [comment]
Okay great. I'll investigate increasing the pool size a bit and then we discuss again if this would be good more generally. Thanks.

**Comment by tpetracca** [comment]
> There is also thread and system-resource usage on the connectee that is improved by idling at a lower number of connections (the pool size is per node, so a connectee attached to a 10 node C* cluster could use a default of (20 * 10 = 200 connections) at idle)

Sounds like we should have the default be variable with the size of the cluster. In general I'd expect a bigger cluster to mean each node itself should receive less requests because the data is spread more thinly, which aligns well with the idea that we should want less connections per node with lots of nodes to prevent connection bloat on larger clusters.

**Comment by gsheasby** [comment]
@tpetracca's solution sounds useful for us. Keeping this thread open now for tracking @jnelson15's investigation, but we might at some point spin off a ticket to track varying the default relative to cluster size.

**Comment by jnelson15** [comment]
@clockfort what do you think of what we were talking about earlier in the ticket about increasing the frequency of eviction runs on a smaller proportion and maybe increasing the idle timeout? Something like:
```
        poolConfig.setMinEvictableIdleTimeMillis(TimeUnit.MILLISECONDS.convert(10, TimeUnit.MINUTES));
        poolConfig.setTimeBetweenEvictionRunsMillis(
                TimeUnit.MILLISECONDS.convert(20 + ThreadLocalRandom.current().nextInt(5), TimeUnit.SECONDS));
        poolConfig.setNumTestsPerEvictionRun(-10);
```
Not sure what the best values are but seems like this could help smooth out the load a good amount, especially if we have a large pool size or large number of nodes that we need to test since they'll be more likely to hit their idle timeout when under low-to-medium load.

**Comment by hsaraogi** [comment]
#1294 is related but does not fix the issue here.

**Comment by jnelson15** [comment]
Yeah similar concept, just different pools

**Comment by rhero** [comment]
Hey @jnelson15 - saw you opened a PR for this. Once that merges, are there any open concerns with Cassandra client pooling that you want to see addressed, or would we be good to close this out?

**Comment by jnelson15** [comment]
Sounds like potentially some work based on Tom's suggestion, but probably okay to close this ticket out since the PR mostly solves the issue described here.
