### ISSUE TITLE
Java 8 Optional doesn't work

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#1249]
https://github.com/palantir/atlasdb/pull/1162/files purported to add support for Java 8 optional.

In practice, every generated table implements `AtlasDbNamedImmutableTable` which is the interface that has the `getRow` method on it. This method is defined to return a Guava optional, so none of the generated code actually compiles.

There are a few options here:

1. You could revert the change.
**2. You could delete the interface AtlasDbNamedImmutableTable. None of that interface hierarchy is actually used anywhere (I checked internally), so far as I can tell.**

@uschi2000

**Comment by j-baker** [comment]
Regardless, it seems like the schema generation code needs better tests. I'd recommend taking a look at https://github.com/google/FreeBuilder if you want some inspiration.

**Comment by gsheasby** [comment]
Looks like we'll go with option 2 from your first post. While doing this, we'll make one of our test schemas use java8 optionals, which should expose the issue.

The second post - lack of schema testing - is a separate problem, we'll make a new ticket to track that.

**Comment by ellisjoe** [comment]
+1 to getting this fixed. ran into this today

**Comment by jboreiko** [comment]
This was flagged again today by ellisjoe @gsheasby, let's see if we can get this fixed.

**Comment by gsheasby** [comment]
I'd like to, but it's sitting below a few other things on my priority list right now, and I might not get to it myself unless the higher things (e.g. #1442, #1443, #852) get done/blocked.

Happy to accept a PR with option 2, or for someone else to pick this up.

**Comment by gsheasby** [comment]
Bumping up the priority list - we'll put this on our weekly plan next week.
