### ISSUE TITLE
running AtlasDB

### ISSUE THREAD

**Issue by rdotapple** [palantir/atlasdb#126]
Sorry for submitting this question under Issues, I could not find a more suitable place. 

AtlasDB seems like a very nice project. Could you please provide some basic commands on how to run AtlasDB? I figured out that I needed Gradle first, I installed it and issued 'gradle' successfully, as well as 'gradle build'. What is the next step? How do I actually run one of the projects now? 

For instance, in the Wiki I see a section called "Running a standalone atlas server that talks json/rest" and it shows this line: 'AtlasDbServer server src/dist/atlasdb_standalone.yml'. But how do you run that line? When I issue it (from a top directory like /usr/local/atlasdb/), I get 'bash: AtlasDbServer: command not found'. I did play a little with the java command and by supplying a classpath, as well as with some other options, but not much luck. 

Thanks in advance.

**Comment by markelliot** [comment]
If you've built the code you can run the server by running the main class, `com.palantir.atlasdb.server.AtlasDbServer` with the classpath from the server's dependencies, with args `server path/to/atlasdb_standalone.yml`. We're not currently distributing the server binary right now, though we might in the future.

Most of our internal use of this system, though, is to embed AtlasDb's thick client into our own servers. This gives us stateless, scalable applications that may be replicated for either availability or for scale. At least recently, we're heavy users of Dropwizard, and for a Dropwizard app, adding the client involves the following steps:

 1. Take a dependency on the client, config, and at least one implementation jar, such as rocksdb, e.g.:

        com.palantir.atlasdb:atlasdb-client:0.3.13
        com.palantir.atlasdb:atlasdb-config:0.3.13
        com.palantir.atlasdb:atlasdb-rocksdb:0.3.13

 2. In your configuration implementation, add an `AtlasDbConfig` getter: (https://github.com/palantir/atlasdb/blob/develop/atlasdb-config/readme.md)

        public final class MyAppConfiguration extends Configuration {
            private final AtlasDbConfig atlas;
            public MyAppConfiguration(@JsonProperty("atlas") AtlasDbConfig atlas) {
                this.atlas = atlas;
            }
            public AtlasDbConfig getAtlas() {
                return atlas;
            }
        }

 3. In your server class' run method, initialize a `TransactionManager` for use:

        public void run(AtlasDbServerConfiguration config, Environment env) throws Exception {
            TransactionManager transactionManager =
                TransactionManagers.create(
                  config.getAtlas(),
                  Optional.<SSLSocketFactory>absent(),
                  ImmutableSet.<Schema>of(),
                  env.jersey()::register);
            ...

**Comment by rdotapple** [comment]
Thanks, I did try some of that a while back, unfortunately -cp / -classpath has simply not cooperated so far.

For example, to give you an idea of the directory structure:

```
>>> ls /usr/local/atlasdb/atlasdb-server/build/classes/main/com/palantir/atlasdb/server/AtlasDbServer*
/usr/local/atlasdb/atlasdb-server/build/classes/main/com/palantir/atlasdb/server/AtlasDbServer$1.class
/usr/local/atlasdb/atlasdb-server/build/classes/main/com/palantir/atlasdb/server/AtlasDbServer.class
/usr/local/atlasdb/atlasdb-server/build/classes/main/com/palantir/atlasdb/server/AtlasDbServerConfiguration.class


>>> ls /usr/local/atlasdb/atlasdb-server/src/main/java/com/palantir/atlasdb/server/AtlasDbServer*
/usr/local/atlasdb/atlasdb-server/src/main/java/com/palantir/atlasdb/server/AtlasDbServer.java
/usr/local/atlasdb/atlasdb-server/src/main/java/com/palantir/atlasdb/server/AtlasDbServerConfiguration.java
```

Then:

```
cd /usr/local/atlasdb/
java -cp atlasdb-server/build/classes/main com.palantir.atlasdb.server.AtlasDbServer

Error: Could not find or load main class com.palantir.atlasdb.server.AtlasDbServer
```

I have tried a large number of variations, including with some jars for the -cp , and have also spent some time on general java forums, but no luck. I have used both Ubuntu and Mac OS X. I wonder if there is a larger issue with Gradle at this point, but I am not really sure. Also, I know you mentioned using args server path/to/atlasdb_standalone.yml, however I am trying to sort out the Error message above first.


If you would be able to paste the exact java -cp... command you use to run com.palantir.atlasdb.server.AtlasDbServer, and also what your $CLASSPATH variable is set to by default, that would be great. I realize that the variable should be irrelevant if -cp is specified, however I did play with $CLASSPATH as well, and have had no luck with that approach either.


Thanks again!

**Comment by rdotapple** [comment]
Hi, I am not sure if this forum is still monitored, if it is would somebody please be able to address the questions above? Getting AtlasDB to run has not been possible so far. Thanks a lot...

**Comment by carrino** [comment]
The key is to copy all the dependent jars into one place to make it easy to set up the java classpath.

http://stackoverflow.com/questions/26697999/gradle-equivalent-to-mavens-copy-dependencies

Steps I think should work.  
Add this block to atlas-server/build.gradle

```
task copyDependencies(type: Copy) {
   from configurations.runtime
   into 'build/lib'
}
```

Then run `./gradlew copyDependencies -p atlasdb-server` and `./gradlew jar -p atlasdb-server`
This will collect all the deps and create the service jar.

Now you can run java knowing you have all the runtime deps

```
java -cp 'build/lib/*:build/artifacts/*' com.palantir.atlasdb.server.AtlasDbServer server src/dist/var/conf/atlasdb_standalone.yml
```

**Comment by joelea** [comment]
Going to close this due to lack of activity - please feel free to comment if more help is required.
