### ISSUE TITLE
As an operator I want to know what version of Atlas is currently running

### ISSUE THREAD

**Issue by ThomasBoam** [palantir/atlasdb#1263]
When working on support issues it is useful to know what version of Atlas is currently running.  This can tell us if a particular bug is present or fixed, if a CLI is available etc.  Currently this is difficult as I have to check which version of a product is running and then look at its dependencies to find the Atlas version.

Instead we should make this information available either via a CLI, an endpoint or in the backing store (or all of these).

**Comment by rhero** [comment]
So two reasons this would be useful are for debugging (as noted above), and for a log collection service that depends on the current AtlasDB version running (@griechel). As a workaround for support issues, we have an internal tool that maps product versions to AtlasDB version which should suffice.

Going to backlog this as it might be a solution for the log collection problem, but we'll revisit that problem separately.
