### ISSUE TITLE
Warn users Cassandra Trace Logging is active

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1271]
PDS-47457 was the result of cassandra trace logging being left on a production stack.  My proposed changes would be:
- [x] live reload the config, helps us turn it on and off without down time - https://github.com/palantir/atlasdb/issues/1307
- [ ] larger warning printed in the logs that tracing is enabled and can have serious performance implications

**Comment by rhero** [comment]
The first issue we're going to file separately as a bug to fix live reloading (as this should work), so we will make the logging for tracing more obvious than is currently.

**Comment by tpetracca** [comment]
Isn't this already covered?
- All traces [log at ERROR](https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingQueryRunner.java#L95)
- The [trace config file loader](https://github.com/palantir/atlasdb/blob/develop/atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingPrefsConfig.java#L65) even logs when it detects a config

Maybe just make the latter of those two more distinctly say that this will affect perf like the [docs](https://palantir.github.io/atlasdb/html/configuration/enabling_cassandra_tracing.html#overview) do?

**Comment by gsheasby** [comment]
Docs here https://palantir.github.io/atlasdb/html/configuration/enabling_cassandra_tracing.html should also be updated to have a banner warning - @rhero to work on this

**Comment by rhero** [comment]
Added a warning banner and updated the prefs file comment to be clearer #1432.
