### ISSUE TITLE
Remove Authentication Of Cassandra Images

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1274]
I want to propose that we remove the username and password from our Cassandra docker image. It’s caused a bunch of pain and time so far, as we have started testing against three-node clusters (_italic_ = sunk cost):

- _Writing all of the orchestration to be able to set RF and run repairs_, and the complexity it has added to our codebase
- _The modifications to this orchestration that Glenn had to make when we added Cassandra 3.7_
- The ~few minutes it adds to our ETE tests, having to run the repairs before we start testing
- The flakes it currently adds to our ETE tests: Grgur has found that the repair often hangs, so we’d need to add some timeouts and retries if we want a flake-free ETE test

What I want to propose is:

1. We alter our docker image, taking out the PasswordAuthenticator configuration
2. We alter our AtlasDB code so that it doesn’t set up a Cassandra user
3. We remove all of the AtlasDB code that sets the RF of and runs a repair on the system_auth keyspace
4. All of our tests are now running against a Cassandra cluster with no username/password

We’d like to eventually be testing against Casssandra clusters with a username/password, but we could have a targeted authentication test in AtlasDB for this, that could even just be a one-node thing.

Does that sound OK to everybody? I've talked to @ashrayjain, @gsheasby and @gmaretic and they are in agreement, but wanted to loop @tpetracca in because I know that you are pushing for username/passwords on Cassandra!

Harry

**Comment by tpetracca** [comment]
I'm happy to have a single-node one-off test that ensure that keyspace user/pass authentication works and then having all the rest of the tests run un-authenticated.

**Comment by jboreiko** [comment]
As a clarification, the auth is related to the RF bump + repair because it is the auth keyspace that defaults to not being distributed.

**Comment by rhero** [comment]
This all sounds good. It's not an immediate problem for any tests we're writing, so we'll address this when we add additional security related tests.

Notably, this will likely speed up Cassandra HA tests by 1-2 minutes.

**Comment by jboreiko** [comment]
Also an interesting note on this process - https://docs.datastax.com/en/cassandra/2.1/cassandra/security/security_config_native_authenticate_t.html  There are certainly no work arounds as it is the second step in the process.

**Comment by gmaretic** [comment]
We did this

**Comment by harrybiddle** [comment]
You rock @gmaretic 😎

**Comment by gmaretic** [comment]
He's alive! 🎉

**Comment by jeremyk-91** [comment]
👋 Hey @harrybiddle!

**Comment by harrybiddle** [comment]
Hey guys!!
