### ISSUE TITLE
If Timelock Server crashes owing to an exception, the Atomix client is not closed.

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1282]
Steps to reproduce: 
1. Add a line at the end of the `run()` method in `TimeLockServer` that throws an exception (or error, if you prefer).
2. Run timelock server (assuming default settings), watch it crash
3. Curl `localhost:8700`. 
Expected: connection refused; actual: empty reply from server (so we're still listening)

**Comment by rhero** [comment]
@jeremyk-91 can you add this to the weekly plan? We want to get to this before releasing the server as it could cause issues when users try to restart it.

**Comment by SerialVelocity** [comment]
So I tried to fix this. Turns out you get a `ConcurrentModificationException` if you try to shutdown the server. I can put in a fix but it'll be super hacky:
```
    public static void main(String[] args) throws Exception {
        try {
            new TimeLockServer().run(args);
        } finally {
            if (Thread.activeCount() > 1) {
                System.exit(1);
            }
        }
    }
```

**Comment by SerialVelocity** [comment]
https://github.com/atomix/atomix/pull/197 will fix it once a new version of atomix is released

**Comment by schlosna** [comment]
@SerialVelocity What's the timeframe for a new release? Looks like current build is failing https://travis-ci.org/atomix/atomix 
and I don't see anything on https://groups.google.com/forum/#!forum/atomixio or https://gitter.im/atomix/atomix about a atomix-1.0.0-rc10 or 1.0 release, and last published build was June 23rd. Can you poke those to see if we can get an updated build?

**Comment by SerialVelocity** [comment]
No idea what their time frame is. I'm assuming it's as soon as someone asks (@hsaraogi asked here: https://github.com/atomix/atomix/issues/206). Locally, I've been testing against the snapshot releases looking for more bugs (like #1310) so we can get all the fixes we need in before a new release is cut.
