### ISSUE TITLE
Use pre-built docker-compose cli instead of pip installing it

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1283]
"12 fun ways to speed up your circle builds", # 3

Downloading the pre built one takes <1 second.  Actual one took ~11 seconds. Also I don’t know why we were downloading docker ourselves… circle already has it.

**Comment by rhero** [comment]
Is the benefit only a single 10 second improvement? This probably won't be looked at unless we're making a big push on build times.

**Comment by SerialVelocity** [comment]
Yes, single line change though.

**Comment by rhero** [comment]
There was the other question about CircleCI having the proper version.
