### ISSUE TITLE
Use DockerComposeRule’s AggressiveShutdownStrategy

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1284]
"12 fun ways to speed up your circle builds", # 5

By default, DCR does an incredibly careful, gentle shutdown thing.  This was taking 40seconds of build time, so I added an aggressive mode that would effectively kill-9 everything.  If you grab DCR 0.24+, you can just add .shutdownStrategy(ShutdownStrategy.AGGRESSIVE) to take advantage of this.

Comment from @SerialVelocity, 20/10/16 - We'll switch once there's a fix for the networks not being deleted

**Comment by ashrayjain** [comment]
DCR PR at https://github.com/palantir/docker-compose-rule/pull/133
