### ISSUE TITLE
Dump excessive containers to speed up our build

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1285]
"12 fun ways to speed up your circle builds", # 6

An internal data ingestion team were testing their product with a huge kerberized hive hadoop monstrosity.  The backend already has tests for this, so we dumped these slow containers and switched to their fastest source instead. (This was a huge win)

@SerialVelocity commented: "Something similar to this that we need to do is switch to the OSS cassandra image we have"

**Comment by iamdanfox** [comment]
I've also tried to get either of the two `docker-squash` CLIs to work on my Mac a few times, but have never actually succeeded :/

**Comment by rhero** [comment]
What about OSS Cassandra makes it faster? One potential benefit was disabling gossip, correct? Would this affect our multi-node tests?

@clockfort @tpetracca in case you guys have thoughts.

**Comment by SerialVelocity** [comment]
Before, we were building the OSS cassandra image every time we ran the builds. Now we just pull in the pre-built image.

**Comment by rhero** [comment]
We don't think we suffer from this because our Cassandra image is one-layer, and we're pulling in the background as well, so we probably won't benefit anymore from this.
