### ISSUE TITLE
Background docker container pulls!!!

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1286]
"12 fun ways to speed up your circle builds", # 7

@iamdanfox can confirm the effectiveness of this one.
Things started to get ridiculous at this point.  We don’t try to cache any docker images because I’ve previously experimented with tarring them up and caching them, but extracting from the cache turned out to take almost exactly the same amount of time as pulling them (and this just bloats our cache).  Instead, we realised that we could start a background docker pull right at the beginning of the build, so that when the docker-compose-rule ETEs actually fire up, most of the containers will already be present.  We put this script in the `pre` block of the `machine` section, and then we wait for docker to be installed then immediately start pulling images. This seems hacky, but it gives us an extra 20 seconds of pulling time (while circle restores it’s cache) before the `post` block even gets executed.  We also made sure to order our master list of containers by frequency of use, so that the most commonly used ones are pulled first.

**Comment by iamdanfox** [comment]
This one is insane.

**Comment by iamdanfox** [comment]
We've tuned our script further since then to pull exactly the images needed for each node.  (E.g. only node 1 and 2 need wiremock, so we don't bother pulling it on the other nodes).

**Comment by rhero** [comment]
We want to see how much time we spend pulling images right now, as we suspect we spend a lot of time doing this and this improvement would be the largest of the recent devEx ones. 

@jboreiko can you post how much time we're looking at potentially saving?

**Comment by iamdanfox** [comment]
If you're using docker-compose-rule, we could just wrap the pre-test `docker-compose build` call in a stopwatch and log it out?

**Comment by rhero** [comment]
This is merged in #1330.
