### ISSUE TITLE
Background sphinx install

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1287]
"12 fun ways to speed up your circle builds", # 8

Same as the #1286 .  Saves you about 6 seconds.  We also included a couple of retries here because pip install occasionally fails.

```
#!/usr/bin/env bash

# exit immediately if sphinx-build is already installed
which sphinx-build && exit 0

# install sphinx (retry twice if it fails).  This should take around 6 seconds.
sudo pip install sphinx && exit 0
sudo pip install sphinx && exit 0
sudo pip install sphinx
```

**Comment by rhero** [comment]
Going to close this out. If somebody wants to do this, feel free to just do it.
