### ISSUE TITLE
Shorter timeouts (optimising time to failed build)

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1288]
"12 fun ways to speed up your circle builds", # 12

We may have already done this. I remember some builds waiting for 10 minutes before giving up.

Internal product comment: "Previously we were waiting 20 minutes after no console output before failing a build.  This used up circle resources and seemed unnecessary.  We make sure that working tests log frequently and have dropped this to 5 minutes.  (Docker pull is usually the worst offender here)."

**Comment by rhero** [comment]
@hsaraogi can you close this out after you change it?
