### ISSUE TITLE
Documentation for paxos node replacement

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1299]
@diogoholanda - hoping to replace a node of the internal auth service was unable to find documentation regarding what invalidation process that is necessary for invalidating the now lost paxos acceptor.log and learner.log.

From my current understanding this cli lives internally but would need to be ported and the necessary documentation written.  The need for this utility goes away once we are in the atomix lockservice world.

**Comment by rhero** [comment]
The workaround here is to delete the contents of the logs manually on all the nodes (don't delete the file, just truncate the log files), but this won't be necessary when we have an external timelock service. We should test how to replace a lost timelock server though.

Going to close this out for now.

**Comment by tpetracca** [comment]
For reference, the port from internal (plus necessary changes) is at https://github.com/palantir/atlasdb/pull/1302. Sounds like we don't want/need it, but it's there if people are curious.
