### ISSUE TITLE
Speed up Jepsen Tests

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1313]
(At the time of writing, the tests haven't merged in yet).

If we start with a fresh slate, and want to run the Jepsen tests for five minutes; the whole gradle task actually takes ten. From looking the times (see attached), we could do this, in order of biggest win first:

1. Pull images that already have Java 8 installed, so that these can be used for Jepsen's n1-n5 nodes: would save just under 4 minutes.
2. Run docker-compose build in parallel with earlier tasks (i.e. #1286): would save just under 1 minute.
3. Save down a docker image that already has our lein dependencies downloaded: would save 30 seconds.

![picture1](https://cloud.githubusercontent.com/assets/5887227/20749367/f8b2d4a6-b6e9-11e6-8cdd-5138e99cbfa9.png)

[analysis.xlsx](https://github.com/palantir/atlasdb/files/621555/analysis.xlsx)

**Comment by rhero** [comment]
@harrybiddle is this worth looking into at all given that we're going to be running our jepsen tests on a nightly cadence and not pre-merge?

**Comment by harrybiddle** [comment]
Nope, I don't think it is worth it any more for exactly that reason. Closing out.

Goodbye beautiful pie.
