### ISSUE TITLE
AtomixRetryer doesn't actually retry with new clients

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1320]
The point of `AtomixRetryer`, among other things, was to help us recover from a `ClosedSessionException` when a session we have expires (e.g. owing to a network partition). The impl in `AtomixTimestampService` and `InvalidatingLeaderProxy` unfortunately isn't quite right, because they simply call `get()` on a `DistributedLong` or `DistributedGroup`. But these distributed objects are tied to a `CopycatClient`; if the client is expired then each get applies to an expired client, and all 3 attempts will return an exceptional `CompletedFuture`. This is not what is expected (behaviour being to start a new session, and then retry it with the new client).

Correct usage is more along the lines of what's in `AtomixRetryerTest`.

**Comment by rhero** [comment]
We'll want to address this if we do end up going with atomix.

**Comment by rhero** [comment]
@tboam @jeremyk-91 I'm not sure if it's completely decided on yet, but it seems like we're heavily leaning towards not doing this implementation. Any issues with me closing this out?

**Comment by tboam** [comment]
Yeah, I think it is unlikely we will use Atomix at this time.  We can always find this ticket again if we go back down this path. 

Closing.
