### ISSUE TITLE
CassandraMultinode tests are flaky

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1326]
Many builds across branches are currently failing due to an issue with the CassandraMulitnode tests (e.g. [develop](https://circleci.com/gh/palantir/atlasdb/tree/develop)).

This may be linked to authentication troubles.

**Comment by clockfort** [comment]
At least for me, it seems to mostly be OOMs because of the extremely constrained resources we need to fit many concurrent Cassandra instances in the same <4GB Circle CI memory

**Comment by gsheasby** [comment]
Fixed by #1327.
