### ISSUE TITLE
Dynamic columns sort order

### ISSUE THREAD

**Issue by uschi2000** [palantir/atlasdb#133]
Hi,
As it stands, dynamic columns are unordered when retrieved through the schema API, although they are presumably ordered in the (Cassandra) backend. RowResult still maintains a SortedMap for columns, but  this gets flattened into a HashMap in schema-generated code. Can we export the sort order all the way?
  R.

**Comment by uschi2000** [comment]
@carrino @pnepywoda

**Comment by carrino** [comment]
I think this makes sense assuming all values types are comparable

**Comment by carrino** [comment]
So in the case where a column name is a VAR_LONG, do you want the columns sorted by the byte order or the long order?

**Comment by uschi2000** [comment]
I think the semantics should be identical to the case of row key ordering,
if possible?
  R.

**Comment by uschi2000** [comment]
Any update on this?

**Comment by carrino** [comment]
so the goal would be to have the generated code consist of sortedMaps?  

Preserving the order from cassandra specifically isn't really useful because rows are fetched in total so either way the whole row is coming back from the storage node.

**Comment by uschi2000** [comment]
yep, the generated code should export sorted maps, in particular since they are already sorted in RowResult, as far as I can tell.

**Comment by pnepywoda** [comment]
still no update on this? (Foundry has a TODO referencing this issue)

**Comment by joelea** [comment]
This is probably something that should happen, but isn't likely to be a priority for a couple of months. A PR that fixes it would be lovely to have.

Should this be a higher priority than we're giving it?

**Comment by uschi2000** [comment]
Not pressing for Foundry.

**Comment by rhero** [comment]
Hey @pnepywoda - going through the backlog and wanted to see if this was a higher priority now.

**Comment by pnepywoda** [comment]
Not higher priority (probably lower for foundry). But I still think it's good to expose the sorted map as it's given back by cassandra.

**Comment by sandorw** [comment]
There are dynamic column scanning APIs that were built some time ago. Closing out.
