### ISSUE TITLE
AtlasDB should set UserAgents on the timestamp and lock http clients

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1335]
This was flagged since request logs without UserAgents are significantly harder to parse.

**Comment by rhero** [comment]
Do we want to set this as "atlasdb" or the name of the actual service that is making use of AtlasDB?

Thoughts @schlosna ?

**Comment by schlosna** [comment]
http-remoting sets the user agent using https://github.com/palantir/http-remoting/blob/develop/http-clients-api/src/main/java/com/palantir/remoting1/clients/UserAgents.java of the form `String.format("%s (%s)", userAgent, version)` and pulls the agent & version from JAR manifest's implementation title and version, so we'd probably want to update the build to make sure we're setting the appropriate properties in `META-INF/MANIFEST.MF` for `Implementation-Title` and `Implementation-Version`

```
jar {
    manifest {
        attributes(
                "Implementation-Title"   : project.name,
                "Implementation-Version" : project.version,
                "Implementation-Vendor"  : "Palantir Technologies, Inc.")
    }
}
```

**Comment by jeremyk-91** [comment]
(Post offline discussion I'll be picking this one up.)

**Comment by jeremyk-91** [comment]
@schlosna We aren't actually using http-remoting for the timestamp and lock clients, though - we've been using Feign and OkHttp directly. I've figured that this needs to be added in `AtlasDbHttpClients`.

Also, from reading your suggestion I'd like to confirm that the user agent is going to be "atlasdb", or something along those lines (in particular, it's not the service that is using AtlasDB).

**Comment by harrybiddle** [comment]
I'm trying to figure out if it's OK to stick with "atlasdb" or use the name of the service.

On the one hand, for timelock in particular, it would be useful to have the the service in the server-side request logs. On the other hand, we can deduce this from the originating IP and it feels at odds with the idea of UserAgent [identifying the client software originating the request](https://en.wikipedia.org/wiki/User_agent). I can't a need for UserAgent for embedded timestamp and lock services.

On balance keeping it as "atlasdb" seems best to me unless there is a strong use case for having the service name. @jboreiko can you elaborate on the original motivation for this PR?

**Comment by jboreiko** [comment]
The initial intention of this ticket was to help us differentiate traffic on nodes.  Now that can be partially accomplished by knowing what path is being hit, but would be simplified with a UserAgent (and require no knowledge about atlasdb versions / expected paths).  With that in mind, the most helpful UserAgent might be something along the lines of `<project.name>-atlasdb`.  If http remoting is using the above then it shouldn't be too hard to mimic that logic with a slightly different `String.format("%s-atlasdb (%s)", userAgent, version)`.

**Comment by harrybiddle** [comment]
Oh, by pulling `project.name` from the same place as http-remoting gets it from, assuming that all of our products are already setting properties in the jar manifest? That's a great idea and we get the best of all worlds; I like it!

**Comment by jeremyk-91** [comment]
Oops, this was actually finished when the PR merged. Closing out.
