### ISSUE TITLE
Running distZip on an unclean repo may include outdated class files

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1342]
A user reported issues running a locally-compiled `atlas-cli`, apparently because the generated CLI included a class that had been renamed several versions ago. We believe this may be due to gradle caching.

Repro:
Check out 0.11.4
Run `./gradlew distZip`
Check out 0.22.0
Run `./gradlew distZip` again
Verify that the generated zip contains com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool$LightweightOPPToken.class
(it should contain LightweightOppToken).

Possible solution: add a gradle dependency on `clean` before running distZip.

**Comment by rhero** [comment]
Assuming this is a pain currently because people have to manually build the CLIs from source to use them. This should go away after we start publishing artifacts with the runnable CLIs. Closing out in favor of #1196.
