### ISSUE TITLE
Add Jepsen verifier for liveness

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1352]
I've been going through the logs manually when evaluating whether various implementations pass Liveness under Partition (i.e. they can still issue timestamps when the network is partitioned, as long as a majority partition exists).

The general idea here would simply be something like: _there is at least 1 invoke-ok cycle between any pair of nemesis-start and nemesis-stop events_. Note that a bit more logic than simply adding a checker for this is required, because we would probably not want this to apply to all possible nemeses/test specifications. 

For example, we might want different settings for pre-merge tests (which could perhaps run a tighter loop that could risk leader election not finishing during the partition) vs some kind of nightly or release test (which could give longer time windows).

**Comment by gsheasby** [comment]
Fixed by #1358
