### ISSUE TITLE
Instrument Metrics for Transactions Cache

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#1365]
Metrics for #1238 would be excellent.

CC @schlosna @clockfort

**Comment by schlosna** [comment]
yeah, we should get @lmaPalantir's #1356 in and expose this among many things. I'm hoping to spend some time next week open sourcing some infrastructure that will help instrument and capture metrics throughout AtlasDB.

**Comment by gsheasby** [comment]
Currently blocked on PR #1356

**Comment by gsheasby** [comment]
Unblocked as 1356's successor #1429 was merged.

@schlosna - is this something your team is planning to do soon?

**Comment by schlosna** [comment]
@gsheasby yes, I still have some work to do to get some instrumentation stuff open sourced so that will simplify this, so shooting for something hopefully next week or by end of January.

**Comment by rhero** [comment]
Fixed in #1685.
