### ISSUE TITLE
Output spurious logging while using AtlasDB Console

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1390]
While using console, you will occasionally see logging output from the background sweeper and other background processes. We should prevent this logging from interrupting console sessions.

![console-sweep-log](https://cloud.githubusercontent.com/assets/7671354/21263807/b3358a78-c390-11e6-8dbf-18ef0486eb2e.png)
![console-sweep-log-2](https://cloud.githubusercontent.com/assets/7671354/21263809/b5201ab0-c390-11e6-9344-9eb892f681b6.png)

**Comment by gsheasby** [comment]
Caught up with @rhero on slack - this is kind of annoying, but can wait until we tackle other console issues.

**Comment by gmaretic** [comment]
This will never happen
