### ISSUE TITLE
Augment Profiling KVS to include a slow log

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1409]
Currently only the heavy weigh cassandra profiling capabilities allows a slow log.  We should extend profiling kvs to contain a slow log that is on by default to help product teams / users identify slow queries before it begins to effect end user work flows.

**Comment by glapul** [comment]
I would like to work on that one.

What should be the conditions of logging a query? Exceeding a global time threshold? Exceeding a time threshold given on per-operation basis? Being x standard deviations above the mean for that operation for some x? Or something else?

**Comment by jboreiko** [comment]
Discussed in person.

For a v0 let's start with a global time threshold.  This threshold should have a sane default (say 1 second) and should be configurable.

**Comment by fsamuel-bs** [comment]
We currently have a slow log under the `kvs-slow-log` logger name both for KVS and Cassandra calls. Implemented by #1801 and #2676.
