### ISSUE TITLE
NamespacedKeyValueService is obsolete

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1433]
PR #323 changed the `KeyValueService` API to use `TableReference` everywhere instead of Strings for table names. This makes `NamespacedKeyValueService` obselete, and we should delete it.

**Comment by jboreiko** [comment]
@rjullman can you confirm?

**Comment by gsheasby** [comment]
Ping - is Bobby back yet?

**Comment by rjullman** [comment]
`NamespacedKeyValueService` also does table mapping (changing the names of tables to be shorted and satisfy constraints of all the underlying stores).  Although the open-sourced code paths do no use this internal code does.  This could be used to replace the oracle specific table mapping and instead be shared across all KVSs.  I know that @clockfort was considering making a change like this to support C*.

**Comment by clockfort** [comment]
https://github.com/palantir/atlasdb/issues/1518

**Comment by rhero** [comment]
Seems like NamespacedKVS isn't actually obsolete given the internal usage, so I'm going to just close this issue out.
