### ISSUE TITLE
Document dropwizard metrics

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1454]
If we're providing dropwizard metrics by default (per #1429), I would like to explicitly call out which metrics we provide in our documentation.

**Comment by gsheasby** [comment]
Someone should run the test server, hit the metrics endpoint, and copy/paste output to the docs. @jboreiko might have time for this.

**Comment by rhero** [comment]
@jboreiko can you do this real quick today?

**Comment by gsheasby** [comment]
If someone (e.g. @harrybiddle) sends @rhero the output of this, he will put it onto the docs.

**Comment by harrybiddle** [comment]
@rhero I've sent this over to you

**Comment by rhero** [comment]
Finally got around to this. #1699
