### ISSUE TITLE
Regression in Postgres DBKVS perf benchmarks

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1479]
It looks like the changes from #1468 introduced two performance regressions in our benchmark tests. We should probably fix these or determine if they are unavoidable given the change we're making. Tagging @gbonik for SA.

Regression (CONFIDENT)
- TransactionGetBenchmarks#getRangeDirty-POSTGRES 
- KvsGetRangeBenchmarks#getSingleLargeRangeDirty-POSTGRES

The graphs for those respective tests are below.

![screen shot 2017-01-18 at 2 43 59 pm](https://cloud.githubusercontent.com/assets/7671354/22086627/83537fd2-dd8e-11e6-854a-d07d7f8af290.png)
![screen shot 2017-01-18 at 2 42 13 pm](https://cloud.githubusercontent.com/assets/7671354/22086629/859624ca-dd8e-11e6-98ed-b8c5e563e305.png)

**Comment by rhero** [comment]
Potentially related benchmarks are:

Regressions (CONFIDENT):
- KvsGetRowsColumnRangeBenchmarks#getAllColumnsUnaligned-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017
- KvsGetRowsColumnRangeBenchmarks#getAllColumnsAligned-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017
- TransactionGetBenchmarks#getRange-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017
- KvsGetRangeBenchmarks#getSingleLargeRange-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017

Improvements (CONFIDENT):
- KvsGetDynamicBenchmarks#getAllColumnsExplicitly-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017
- TransactionGetDynamicBenchmarks#getAllColumnsExplicitly-POSTGRES changed on Wed Jan 18 19:38:00 UTC 2017

**Comment by davidscottcohen** [comment]
@gbonik is working on a fix

**Comment by gbonik** [comment]
The fix for getRange() is here: https://github.com/palantir/atlasdb/pull/1480
Will look at getRowsColumnRange separately

**Comment by gsheasby** [comment]
Resolved by the above issues.
