### ISSUE TITLE
Timelock Server Truncates Logs on Restart

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1481]
If I `kill -9` the timelock server and then start it with `init.sh start`, the only log file that comes by default (`atlasdb-timelock-server-startup.log`) gets truncated.

I would expect to find the following by default, all appended to rather than truncated:

- an `atlasdb-timelock-server.log` which contains all of the server output
- an `atlasdb-timelock-server-requests.log`, which contains the Jersey request logs
- an `atlasdb-timelock-server-startup.log`, which contains any output from the go Java launcher, but none of the server logging output.

**Comment by rhero** [comment]
@harrybiddle do you know if this is a dropwizard specific thing or are the logs being moved to some place other place? Was this done locally or on a full stack of AtlasDB services with our service management product?

We should try this out on our own stacks to confirm (maybe on the perf stack?).

**Comment by tpetracca** [comment]
I would say the -startup.log should indeed get truncated on each startup (it makes identifying issues in a specific start-up run easier to identify). The entire contents of that log should also appear in the -server.log which doesn't get truncated ever. I'm fairly confident that's how our internal stuff logs.

**Comment by rhero** [comment]
Yep, just confirmed that is indeed how all the other services do it, and I don't think we should be different with our default logging behavior. Going to close this out as expected behavior.

Harry let me know if you disagree.

**Comment by harrybiddle** [comment]
Sounds good to me, thanks for clarifying @tpetracca
