### ISSUE TITLE
LeaderElectionService should be able to query any valid adresses

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1502]
The current impl of the leader election service forces the timelock server to be on the root applicationContextPath. Ideally, the host should be able to talk to a Paxos cluster where the application path is set. This will break public facing `PaxosLeaderElectionService` which however, has no known users.

**Comment by rhero** [comment]
We're not going to do this because the timelock server doesn't need an applicationContextPath anymore.
