### ISSUE TITLE
Best effort client-side validation of timestamp correctness

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1505]
We currently run our Timelock service against 3 Jepsen nemeses: 1) service failure, 2) disk loss, and 3) network partitioning. The service passes all of these, but this obviously doesn't cover all of the real world scenarios.

I would like to see some best-effort mechanism that can detect if we've ever handed out timestamps that weren't monotonically increasing. One way that comes to mind is having a timestamp verifier that runs on AtlasDB clients. This verifier would keep the last timestamp or some history of timestamps and ensure that they are monotonically increasing. Not sure if it's possible to do this without sacrificing performance, but I don't believe we have a way of detecting a scenario that causes our timestamp service to break its guarantees, i.e. we will fail silently in a case of potential data corruption.

**Comment by harrybiddle** [comment]
Robert, @jkong and I talked about this this morning.

The situation I have in mind here is that a deployment loses the timelock cluster, or migrates to new instances, and doesn't have enough knowledge of timelock to know that they need to fast-forward.

If we had a simple, client-side memory of the last highest timestamp that the server gave out, we could at least protect against the timelock server starting from 0 again.

**Comment by rhero** [comment]
We'd want to make sure that a solution doesn't hurt performance too much. Might have issues if there are many concurrent threads for the timelock clients and they're trying to update the same value.

**Comment by jboreiko** [comment]
These calls are all routed through a single thread safe object that could house these sanity checks, but I agree with rob that perm should be a concern when implementing this solution.

**Comment by sandorw** [comment]
We've implemented a fix for this. We now compare a recent timestamp from the punch table vs. a fresh timestamp to make sure that we're not moving backwards in timestamp-space.
