### ISSUE TITLE
Automated migrations on starting up against timelock

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1511]
If we detect a service with the timelock client, we should fast-forward timestamp and run migration steps to prevent accidental data corruption.

**Comment by tpetracca** [comment]
We need to consider the effect of live reloading configurations in our implementation. If this auto-migration only happens in the startup path we should be sure that you can't swap from embedded to timelock live because then we'll miss the migration (unless we make sure the migration happens there as well).

**Comment by jeremyk-91** [comment]
@tpetracca The plan as far as I know is to run these steps in `TransactionManagers.create()`; if I'm not wrong any config changes would require us to create a new transaction manager, at least at the moment (it might be possible to avoid this for certain specific changes e.g. turning on background sweeps, but for anything requiring a change of the KVS or lock and timestamp services I'm pretty sure you need to go through there). Any thoughts?

**Comment by jboreiko** [comment]
This is going to somewhat dependent on whether or not we are going to make portions of the AtlasDBConfig live reloadable.  Currently we don't adopt any live config changes, regardless of whether a product supports them.  As jeremy notes, for certain things the remediation is simple (and in fact certain portions used to support live reloading prior to being open sourced) but in other cases the path is less straight forward.  Might be worth outlining something of a state machine here.  I can't imagine it being too complex as long as we isolate the change to the `TransactionManagers.create()` method.

**Comment by jeremyk-91** [comment]
This was completed in #1579 with the change isolated to `TransactionManagers.create()`.
