### ISSUE TITLE
No current version of key, all cells flagged for garbage collection

### ISSUE THREAD

**Issue by tkleingarn** [palantir/atlasdb#1523]
We observed a row key where all start timestamps were flagged with the garbage collection sentinel (-1), with no active version of that key, which resulted in read failures when attempting to load the most recent visible version of the key.  While the read failure is expected, there should be no situation where a garbage collection sentinel appears without a piece of data above it.  Copying @jboreiko's comment from internal ticket is QA-97586.

It is essential that a reader fail when encountering a garbage collection sentinel, as this is the lynch pin that keeps sweep from silently missing reads in our transactions.
Now, there should be no circumstance in which a garbage collection sentinel appears without a piece of data above it (as occurred here).

I would be more interested in coming up with a theory on how that could have happened. I'm imagining something around a sweep and a scrub running simultaneously with the scrub targeting a cell on which sweep was relying (for it's remaining valid data) and sweep relying on the cell about to be scrubbed, they would then both add garbage collection sentinels and happily remove their respective cells (all of this occurs extra transactionally) resulting in the current state. Interestingly we could use something like the backup lock to prevent this theoretical state in the future.

**Comment by rhero** [comment]
@tkleingarn has this happened more than once?

If this has only ever happened at one place, then we'll keep it around to track, but we're not going to look into this issue immediately. If internal products hit this issue, they should attach logs to the QA ticket. Backlogging for now.
