### ISSUE TITLE
Batching of client timestamp requests

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1534]
This is an extension of #1517 to the client side. It comes with the same caveats (in that it might hit latency). Timestamp clients can batch together a bunch of calls to getFreshTimestamp and make a single getFreshTimestamps call to the timelock server that corresponds to these requests.

Note that because getFreshTimestamps is not required to return the full amount asked for, a check needs to be done after that. I think you're pretty much stuck with dumping the entire range returned and asking for another batch.

As always with something like this, be _very_ careful with concurrency.

**Comment by rhero** [comment]
Will only prioritize after we have reason to improve timelock perf.

**Comment by jeremyk-91** [comment]
This was actually implemented in #2083
