### ISSUE TITLE
Don't export jmock

### ISSUE THREAD

**Issue by uschi2000** [palantir/atlasdb#154]
timestamp-impl exports jmock, but probably should not.

  451 |    +--- com.palantir.atlasdb:timestamp-impl:0.3.5
  452 |    |    +--- com.palantir.atlasdb:timestamp-api:0.3.5 (*)
  453 |    |    +--- com.palantir.atlasdb:atlasdb-commons:0.3.5 (*)
  454 |    |    +--- junit:junit:4.11 -> 4.12 (*)
  455 |    |    \--- org.jmock:jmock:2.5.1
  456 |    |         +--- org.hamcrest:hamcrest-core:1.1 -> 1.3
  457 |    |         \--- org.hamcrest:hamcrest-library:1.1
  458 |    |              \--- org.hamcrest:hamcrest-core:1.1 -> 1.3

**Comment by uschi2000** [comment]
ping

**Comment by uschi2000** [comment]
@tjwilson90 @rjullman

**Comment by clockfort** [comment]
fixed in #229

**Comment by uschi2000** [comment]
cheers Chris.
