### ISSUE TITLE
Backup docs are out of date

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1554]
Question came in:
"in the docs for atlas, backups are done using
`$ ./bin/atlasdb --config <config-file> --config-root <path-to-atlas-block> timestamp fetch --file <backup-directory>/backup.timestamp`.
Is `./bin/atlasdb` the same as `./bin/atlasdb-cli`, and what config file or path to atlas block do i use?

Answer:
Should use the dropwizard command instead of a 1-off CLI. There's a how do I backup the internal platform post you can follow.

Task: make the docs reflect the advice on this post.

**Comment by rhero** [comment]
@gsheasby should take care of this as part of #1509.

**Comment by rhero** [comment]
Can confirm that this was taken care of as part of #1509.
