### ISSUE TITLE
Unused hamcrest dependency in timestamp-impl

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1559]
@pnepywoda found that we have the Hamcrest matchers on the main path of timestamp-impl, for some bizarre reason. I suspect it's an artifact of when we might have used awaitility for something.

Link:
https://github.com/palantir/atlasdb/commit/9ebad923cd2fa324b10712d13aa557f8e146b113#diff-16e15791db9c1fb4abf7e95ae30e86fbR7

**Comment by jboreiko** [comment]
Closed as per #1578 @pnepywoda thanks for the flag, it had snuck into quite a few places (as you can see from the lock file changes).   Cheers
