### ISSUE TITLE
Fails to store empty blob

### ISSUE THREAD

**Issue by akroy** [palantir/atlasdb#156]
With a schema like this:
```
schema.addTableDefinition("blobs", new TableDefinition() { {
                rowName();
                rowComponent("id", ValueType.STRING);

                columns();
                column("blob", "b", ValueType.BLOB);
            }
        });
```
Storage and retrieval works fine in general, but if you store an empty byte array (i.e. length zero), then retrieval will fail to find anything. It will give an Optional.empty when you look up that row.

I tried to force Atlas to be aware of empty blobs as such:
```
schema.addTableDefinition("blobs", new TableDefinition() { {
                rowName();
                rowComponent("id", ValueType.STRING);

                columns();
                column("blob", "b", ValueType.BLOB);
                column("timestamp", "t", ValueType.VAR_LONG);
            }
        });
```
Then the row would be found (not Optional.absent), but the blob itself would be null.

**Comment by tjwilson90** [comment]
Thanks, this is an issue that has been known for a while. It comes up when storing any empty value, not just blobs, e.g., empty protos. It happens because and empty byte array is used as the deletion sentinel value.

No plans have been made to fix it since it's a minor issue with workarounds and actually changing the deletion sentinel (or making some kind of an empty value sentinel) is a pain.

**Comment by akroy** [comment]
I'd like to politely push back on not bothering to fix this. This issue means that a user further can't trust the results of even simple Atlas queries. Between this and that Atlas sometimes returns lots of extra rows (QA-91733), very simple uses of Atlas keeping hitting basic brokenness.

If we want Atlas to be adopted and trustworthy, we do need confidence that it accurately stores data. If there are easy workarounds, can we just bake them into Atlas itself?

**Comment by joelea** [comment]
Hey @akroy this is going to be hard to fix in a general way in Atlas, but is pretty easy to fix for an individual product, hence @tjwilson90's comment above. However, this is definitely odd behaviour and we're going to look into how high a priority this is. We'll start an email thread about this and include you on it to figure it out.

**Comment by joelea** [comment]
We also need to make sure #549 is not present before we merge this.
