### ISSUE TITLE
Configurable max for the number of tombstones background sweep is allowed to set

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1563]
At the moment, sweep deletes all of the data it can find. In extreme cases this can be more than 100k tombstones, which means that Cassandra will stop serving requests for that table. Sweep also doesn't trigger a compaction (#1550), so this has to be done manually.

If we set a max and trigger a compaction, then sweep can continue to tombstone the rest of the cells in remaining runs.

This is a particular problem for our customers who are just starting to turn background sweeps on, and came up with a sweep we ran.

We probably want the cli to continue to delete all data.

**Comment by rhero** [comment]
Noting that #1597 will allow users to do a dry run of sweep and confirm that they have not generated more than 100k tombstones for a given table.

**Comment by rhero** [comment]
I went and filed a separate ticket to track the real issue which is "Sweep can put cassandra into a state where it drops reads". This ticket seems to focus on a solution where there's a configurable limit to how much sweep can delete, and then forcing compactions immediately. This would be a good way to enforce we remove data in a timely fashion, but there may be other ways to actually prevent the core issue. Filed as #1683.

**Comment by gsheasby** [comment]
This is going to be sidestepped by just increasing Cassandra's tombstone limit to a very large value in our internal Cassandra distribution.
