### ISSUE TITLE
Improve sweep backoff logic

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1564]
When running background sweep recently, we found that it made Cassandra *very* unhappy, but only backed off once.

One key problem here is that it will try a read operation (e.g. of 1000 rows) six times, because of the logic in the cassandra pool. By the time we decide to back off the batch size we've already hammered cassandra. We might want to only try this once for sweep.

A second problem is that the backoff is only in the number of rows (`sweepBatchSize`). We should also back off on the number of columns we read (`timestampGetterBatchSize`).

This is going to be a big problem when we start turning on background sweep in the field.

**Comment by gsheasby** [comment]
Have we done anything on this P1 issue yet? @rhero @harrybiddle

**Comment by rhero** [comment]
Don't believe anybody got to it last week despite putting it on the weekly plan.

**Comment by gsheasby** [comment]
I think we sidestepped this by reducing the batch size to 100 - backlogging for now.

**Comment by gsheasby** [comment]
Fixed by a combination of #1911, #1943, #2060.
