### ISSUE TITLE
Cassandra timestamp backup runner brings in the entire KVS

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1572]
The Cassandra timestamp backup runner brings in the whole CassandraKeyValueService with it. This can be avoided with some careful refactoring.

What we actually need are:

1. The ability to create tables,
2. the client pool,
3. the tracing query runner, and
4. the `CassandraTables` table manager (note: it only does gets)

2-4 are already easily available through getters on CassandraKeyValueService. 1 is not, so fixing this probably means we need to isolate the table creation logic from CassandraKeyValueService to some new class. Note that this needs the ability to grab the schema mutation lock.

**Comment by rhero** [comment]
We're going to time box work on this. If it's not easy to do, we'll backlog or close.

**Comment by jeremyk-91** [comment]
We'll do this refactor at an appropriate time when we next touch this code, but this probably isn't something worth investing in specifically tracking.
