### ISSUE TITLE
Allow AtlasDB clients to easily enforce Timelock usage

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1595]
On PR #1579:

> jboreiko 10 hours ago
> Maybe beyond the scope of this PR, but it seems like were currently missing a way to have a dev programmatically specify that their product no longer accepts other configurations. Can be easily added later
> 
> gsheasby an hour ago 
> Could we do this by having something like TransactionManagers.createWithTimelock alongside TransactionManagers.create (not necessarily as part of this PR but possibly pre-release)?

Of course, devs can already do this if they want to (since they can validate `config.timelock().isPresent()` just before creating the TransactionManager), but it's nice to provide an easy way of doing it, plus a layer of abstraction from how the config is structured.

**Comment by rhero** [comment]
Pinging @ellisjoe and @j-baker for SA in case you guys have thoughts here (I think we've chatted about this in the past).

**Comment by hsaraogi** [comment]
Can open again if we see some value for the products.
