### ISSUE TITLE
Bump gradle-java-distribution dependency 1.3.0 -> 2.0.0

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1612]
Note from @uschi2000:

gradle-java-distribution is now called sls-packaging and is available in version 2.0.0: https://github.com/palantir/sls-packaging/releases .
All products should upgrade to this release as soon as possible since it fixes run-time behavior in out-of-memory situations. Further, this release allows products to specify product dependencies which will in the near future be consumed by our log gathering product to make upgrade decisions.

I'm not sure how relevant the second point is to us, but the first point certainly looks like motivation to upgrade. Our upstream dependencies will presumably be taking this bump, so it would also help to keep in line with them.

**Comment by uschi2000** [comment]
+1 Let me know if you run into issues.

**Comment by hsaraogi** [comment]
Fixed by  #1881.
