### ISSUE TITLE
Use HTTP/2 without ALPN boot jar / java-agent

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1636]
AtlasDB clients should be able to connect to the timelock server via HTTP/2 even in the absence of alpn-boot in the java boot classpath. This has been fixed by jetty in https://github.com/eclipse/jetty.project/issues/441 and AtlasDB timelock clients should use jetty#HTTP2Client() and `setUseALPN` to false.

@markelliot

**Comment by jeremyk-91** [comment]
Note: Offhand I didn't see an easy way of accomplishing this in OkHttp, which suggests that a migration to using Jetty's clients might be needed...

**Comment by markelliot** [comment]
Sorry yeah. Read a bit deeper here. Looks like the ALPN stuff is required on the client for OkHttp, not sure where I read otherwise. Let's just go down the path of putting it on the boot classpath.

**Comment by jeremyk-91** [comment]
OK. We'll proceed with the current impl, and can revisit this once people start transitioning to Java 9.

**Comment by hsaraogi** [comment]
Fixed by #1594.
