### ISSUE TITLE
Simplify the PersistentLockService api

### ISSUE THREAD

**Issue by ashrayjain** [palantir/atlasdb#1653]
We could have something like `PersistentLockServiceResponse` that could basically encapsulate an `Optional<LockEntry>` along with any other things we want to return like a string response, etc.

**Comment by rhero** [comment]
If you or @SerialVelocity wants to submit a PR for this, we'd be happy to take it. We're probably not going to make any changes to it in the near future given other priorities though. I believe you're the only consumers of the API right now, so there's not much risk in breaking it.

**Comment by gsheasby** [comment]
Closing as #2246 is our preferred approach here.
