### ISSUE TITLE
AtlasDb CLIs should have ETE tests

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1657]
We should have CLI ete Tests that test with leader block or timelock blocks in the config. Currently, we only test with the config:

```
atlasdb:
  keyValueService:
    type: memory
```

This becomes increasingly important as with the timelock server the online CLIs will perform migrations and we want to ensure that the CLIs do not behave incorrectly.

**Comment by gsheasby** [comment]
@jeremyk-91 believes this is already satisfied by dropwizard tests. Also, CLI support is going away soon, so it seems unlikely that this work will be valuable.
