### ISSUE TITLE
ETE Testing for AtlasDB Timelock Migrations

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1667]
We already have #1619 and #1661, but I'm creating this ticket as a reminder that Part III still needs to be done, as I pick up higher priorities.

* Part III involves setting up the ETE Server under the old configuration, _changing its configs to the new configuration_ and bouncing it, verifying data integrity across this bounce.
* This is likely to be achieved by mounting a volume and updating the configuration on the volume, and then restarting the server. Be careful - the AtlasDB ETE Server doesn't seem to always respond properly to init.sh stop.
* Also, because of the need to start/stop containers and/or docker-exec things, it's unlikely we can use EteSetup in its current form (we need direct access to the DockerCompose object).
* Furthermore, if we go the start/stop route, be aware of https://github.com/palantir/docker-compose-rule/pull/122 (in particular, it was *not* merged).
* I have some partial hacky work, will push up a branch tomorrow with what's done so far.

**Comment by gsheasby** [comment]
In review: #1676

**Comment by jeremyk-91** [comment]
The PR #1676 was merged a fair while back, closing out.
