### ISSUE TITLE
AtlasDB service server is not in the best state.

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/atlasdb#1672]
- Doesn't have `addBundle(new AtlasDBBundle<>())`
 - `TableMetadataDeserializer` doesn't work (`deserializeDynamicCol` calls `deserializeRowish` which tries to do `node.get("row")` when I think it should be `node.get("col")` for the column case
 - Uses custom serialisers/deserialisers so that http-remoting cannot be used to hit it.

**Comment by gsheasby** [comment]
@SerialVelocity what's the value of fixing these things? Does it block anything? They look unrelated; should we split into separate issues?

**Comment by rhero** [comment]
Is this part of any larger work that requires the use of the AtlasDB service server? I'm only aware of its use in relation to console, and we're not prioritizing any work in that area right now. I'm going to close this out, but feel free to re-open if you have more thoughts.
