### ISSUE TITLE
Timelock Should Support Rolling Restarts

### ISSUE THREAD

**Issue by harrybiddle** [palantir/atlasdb#1679]
Timelock may not support rolling restarts.

In particular, I found one case where, on a running stack, I made a configuration change (a heap bump) and restarted each timelock node in a three-node cluster one by one, waiting for the healthcheck to pass before moving on to the next node. During this period a product using the timelock cluster failed an operation it was trying to do, with the error:

`Remote exception of type feign.RetryableException thrown: status 503 reading TimestampService#getFreshTimestamp(); content:`

Why is it important for us to work on rolling restarts? It makes maintenance an *awful* lot easier if you can make configuration changes without downtime. Worth nothing that we could also get a lot of this by supporting live-reload of config.

When doing this work we could consider:

- Was the error I saw definitely caused by this rolling restart? What happened to the cluster & clients at this time?
- The mechanism performing the rolling restart should probably leave the leader until last, so that we only do one leadership election.
- How does the timeouts & retries in our remote proxy compare to startup times? I could imagine that we could be very unlucky, and have a well-behaved rolling restart but the client happens to hit the wrong node at the wrong times, and still fail.
- Should our healthcheck only be green when the node has successfully joined the cluster and is ready to become a leader if needed? (This may already be the case, I've forgotten how the healthchecks work..!)

**Comment by gsheasby** [comment]
Further investigation is needed: we need to better understand why the failure happened - could the attempted rolling restart have happened too fast? Did the upstream service get unlucky?

**Comment by harrybiddle** [comment]
Farewell, old friend.
