### ISSUE TITLE
Run DBKVS benchmarks against earliest convenient version

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1690]
We introduced DBKVS in AtlasDB 0.7.0, and benchmarks for Postgres and Oracle weren't available until AtlasDB 0.25-ish. We've detected at least one important regression by running tests against historical versions, and so we should probably run benchmarks against an early version of AtlasDB so we can see if there are any other glaring regressions.

A large internal product will be performing their own regression tests across major versions, and having data for an earlier AtlasDB version will help with narrowing down any regressions we've introduced.

**Comment by rhero** [comment]
We're going to try and do this as a stretch goal for this week if it's easy. If it's more difficult than expected, then we may punt it.

**Comment by hsaraogi** [comment]
Doesnt seem very high value to do this. All benchmarks are unlikely to run if the benchmarks are backported to 0.7.0.
