### ISSUE TITLE
Consider using MOE to maintain AtlasDB open source

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1701]
@ashrayjain pointed at this a little while ago and I just got a chance to look at it now.

https://github.com/google/moe

MOE could be a solution for keeping our iteration/discussion quick using internal tooling/jargon but continue to offer AtlasDB and the associated discussions available on the OSS github page.  This has been lower priority since we got internal builds working, but this likely offers a cleaner solution.

**Comment by rhero** [comment]
We're going to close this because we're pretty happy with just keeping everything open source for now.
