### ISSUE TITLE
Allow Certain C* DDL Operations to Occur in Degraded State

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#1705]
CC @ellisjoe @jboreiko @clockfort @rhero 

Following up on our discussion this afternoon, I caught up with CLocks about allowing schema mutations with a Cassandra node down. Generally we came to the agreement that it's safe for us to allow mutations of the form `CREATE *`. For AtlasDB this means `CREATE KEYSPACE` and `CREATE TABLE`, and would allow AtlasDB clients starting for the first time as well as starting after upgrades that involve schema additions to be able to do so with a C* node down. The create workflow dominates the majority of cases of DDL operations in AtlasDB that would prevent availability of an AtlasDB client.
DDL operations we explicitly don't want to support in degraded states are `DROP` and `TRUNCATE` (C* will fail the truncate anyway).

There's a broader question of whether or not we want to allow `ALTER` statements. I believe a while back I had made some changes the `CassandraKeyValueService` to disallow it from making `ALTER` replication factor statements and that it would fail if your config != the actual setting on the table (requiring changes to be made manually so we don't accidentally do something like change RF without doing proper repairs, etc.). I still like this concept, but I think there's value in say being able to do something like modify `gc_grace_seconds` on a table if the default value for that property has changed in AtlasDB (which is a PR I plan on putting in soon). Happy to discuss the right thing here further.

For related reading see #930

**Comment by rhero** [comment]
This seems worthwhile and we'll want to do this, probably around the same time we tackle #930 (or shortly after as that one is probably higher priority). Going to throw this in the backlog, but mark it as a P1.

**Comment by clockfort** [comment]
Re:  think there's value in say being able to do something like modify gc_grace_seconds on a table if the default value for that property has changed in AtlasDB

The reason I didn't merge #1620 (which is a different setting, but same idea) is that unfortunately a bunch of the table altering operations are n^2 (with n = number of tables) and doing all the alters in [customer who uses a data integration tool that makes several tables per context and thus arrived at a high # of tables scale] cluster would take several hours, which is not something we can safely do during Atlas connector startup.

**Comment by tpetracca** [comment]
why n^2? I thought we just came to the conclusion that each table is it's own statement. But yea either way I get why this would be problematic.

**Comment by clockfort** [comment]
I can't give you a more exact answer again without looking at my chat logs from a long time ago, but I remember internally some operations ended up rereading or rewriting the entire keyspace rather than just parts of it referring to a single table, for some `alter table` operations.
There we also issues with operations that had to range scan over the entire keyspaceworth of tables _as well as the dead lesser-timestamp versions of that keyspaceworth of tables_ in the same table.

I also believe the problem I'm thinking of went away with a rewrite of the schema for the system schema table that happened in 3.x C*

**Comment by jboreiko** [comment]
Out of interest is this a common failure mode?  I agree there is value here, but while attempting to prioritize it I'm struggling to think of instances where we have wanted to install services onto degraded clusters?

**Comment by tpetracca** [comment]
There are workflows in the "dynamic table name" use cases that make this more common (which is why we hit this at a PG deployment).

**Comment by fryz** [comment]
Looks like this came up in https://support-jira.yojoe.local/browse/PDS-56320, which prevented HA MP from starting up due to MP trying to do a Schema Migration. 

Comment from @rhero 

```
I think it's a current limitation of AtlasDB clients that we can't perform certain DDL operations (creating, dropping, modifying tables/schema). We've seen a lot of services perform migrations on startup, and depending on the error handling logic there, you could see a service fail to start-up.
```

**Comment by fsamuel-bs** [comment]
Fixed by the startup ordering chain of PRs.
