### ISSUE TITLE
Rate Limiting TimeLock

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1719]
Currently the timelock server can be DDoS'd by a single client if it gets a bit hyperactive in requesting lots of locks (especially requesting the same lock many many times, and saying "block indefinitely"). We should control this in some way.

The failure mode is as follows: Hundreds of a single client's threads would all try to acquire the same lock, perhaps owing to some upstream bug - and this would consume hundreds of timelock’s threads (since a thread that's blocking on something does consume a timelock thread).

---

For timestamps I think we can use similar approach to large internal product through the `RateLimitedTimestampService`. There shouldn't really be too much contention for timestamp requests as far as I know.

I think the more interesting case is for locks... I know we have `BLOCK_INDEFINITELY` requests, but not sure if we should generally speaking allow these. I'm thinking ideas could include failing out a request if it has been stuck for some amount of time (say 60 seconds), and/or restricting the length of lock queues to say 10 threads or something.

**Comment by jeremyk-91** [comment]
Timestamp side is actually already captured by #1534 but we should think about the locks side of things

**Comment by jeremyk-91** [comment]
We should write an ADR for this.

**Comment by gsheasby** [comment]
Fixed by #1785.
