### ISSUE TITLE
Reduce gc_grace_seconds for Cassandra tables

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1725]
Given our solution to #1683 will be to just increase the `tombstone_failure_threshold` in Cassandra and that our deletes are performed at consistency ALL, there isn't a good reason to keep `gc_grace_seconds` at 4 days. 

I don't think we want to set `gc_grace_seconds` to 0 because Cassandra will not replay hints that are older than `gc_grace_seconds`, and we like hints.

@tpetracca, @clockfort, @jboreiko - What are your thoughts on what this value should be changed to? Also, is there any issues with having `max_hint_window_in_ms` be larger or equal to `gc_grace_seconds`? Does this have any impact on rolling out changes to our default internal Cassandra configs?

**Comment by tpetracca** [comment]
Per JB's PR, I like the idea of setting it at an hour for now and keep hinted handoff expiration at 20 minutes (our distribution's current default). Hinted handoff expiration must be lower than gc_grace_seconds for correctness reasons.

**Comment by rhero** [comment]
Can you elaborate on your last sentence? I was under the impression that Cassandra won't issue hints if it's been longer than `gc_grace_seconds` (per [datastax docs](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateTable.html#tabProp__cqlTableGc_grace_seconds)), so there isn't actually an issue with setting the `max_hint_window_in_ms`.

If there's a correctness concern, then I think we'll need to coordinate releases to make sure nobody takes the newer AtlasDB version before taking the newer Cassandra version, or we should add some check ourselves in AtlasDB so we don't set too low of a value for `gc_grace_seconds`.

**Comment by tpetracca** [comment]
Oh wow, I totally didn't realize they TTL hints with the minimum gc_grace_seconds of the tables affected by the hints. Which means that we do not have to worry about lowering of gc_grace_seconds causing correctness issues (because of revived deletions).

Good catch. And so there's no coordination necessary (there wasn't anyway because the hint expiration is still less than the new gc_grace_seconds) default.

@clockfort @jboreiko

**Comment by rhero** [comment]
Oh, I didn't realize it was already set to a small number ha. Okay, not an issue for multiple reasons then. We can just close this once #1726 merges.
