### ISSUE TITLE
1.0 of TimeLock Service

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1728]
This is an epic ticket tracking our move towards a 1.0 timelock service.  The versioning of which is maintained internally.

Some thoughts:
- This one 1.0 should not include any REST API breaks
- This should not have any known stop the world bugs
- We should avoid untested optimizations (to make sure we get it out the door in short order ~1 month)

**Comment by rhero** [comment]
I believe we should also include #1664, which is improving the error message when trying to use an embedded service post timelock migration. Doing this before a broader rollout would be much preferred or we'll have some very confused users that try to just change their config.

**Comment by tpetracca** [comment]
#1741

**Comment by hsaraogi** [comment]
Tracking 1.0 requirements separately.
