### ISSUE TITLE
Verifying benchmarks are not broken

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#1739]
We should have automated checks that would verify benchmarks will run correctly. An easy way would be to just have a minimal test as in this branch:
https://github.com/palantir/atlasdb/compare/benchmark/test
This takes about 15 minutes to run, and should catch most of the bad behaviour.

Alternatively, we could set up a check that only runs if atlasdb-perf has been modified and run a full benchmarking run, or run the minimal test only in this case.

**Comment by gmaretic** [comment]
Note that there seems to be a strange issue when running the unit test above on Cassandra. TransactionGetRowsColumnRangeBenchmarks encounters an assert failure in IteratorUtils.mergeIterators (line 178)

**Comment by rhero** [comment]
Given our recent benchmark outages, we want to have some assurance that benchmarks are running because the cost of going back to fix them is very high. Throwing into to do.

**Comment by gmaretic** [comment]
The above should detect most of the causes of benchmark outages
