### ISSUE TITLE
Slow Log for the Lock Service

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1740]
We should set up logging to determine when locks take a long time to acquire (or fail out when we try to acquire them). We already have this for the Lock Refreshing Remote Lock Service, but we don't do this when _acquiring_ the locks for the first time (at least as far as I know to be the case).

**Comment by jboreiko** [comment]
Mentioned this is person, but my flag here is that we want to be wary that some internal products may intentionally have long waiting locks and since we want to be sure this log is high signal it may be worth allowing for a configurable filter of something of a similar ilk.

**Comment by hsaraogi** [comment]
Fixed by #1769.
