### ISSUE TITLE
Project cannot be compiled in IntelliJ

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1742]
Trying to make in Intellij gives the following error:

```
Error:java: cannot access dagger.Module
  class file for dagger.Module not found
```

**Comment by berler** [comment]
This is related to the shadow configurations in a recent change clockfort made.  Either there is something wrong in how we are using shadow configurations, or Intellij simply doesn't handle these configurations properly.

**Comment by rhero** [comment]
@gsheasby can you take point on just trying this out to see if it's still a problem? This may have been fixed with the recent shadowing of Cassandra deps?

**Comment by gsheasby** [comment]
It still doesn't compile for me using latest Intellij (2017.1 CE) and the latest develop. @gmaretic can you confirm your intellij version, as you say that an upgrade fixed it?

**Comment by gmaretic** [comment]
Seems like the latest develop now doesn't work for me, although getting a different error:
Error:(106, 33) java: cannot access com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService
  class file for com.palantir.atlasdb.keyvalue.impl.AbstractKeyValueService not found

**Comment by gsheasby** [comment]
That's the same error I get.

**Comment by jboreiko** [comment]
I continue to get this error on develop (0.38.0-22-gbfbe55e / bfbe55e21665f3879d92bd223d8ca377921a06fe) even after #1524 was reverted in #1775
