### ISSUE TITLE
We should also show the mean of benchmarks in the dashboard

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#1745]
We are currently only showing the median and p90, and reporting on the median. This really does not show the whole picture as some operations can be very efficient 90% of the time and have horrible perf a small percentage of the time.

This is well illustrated in the TimestampServiceBenchmarks benchmarks. Probably the most extreme case is manyThreadsGetBatchOfTimestamps that has the following stats:
p50: 1 us
p90: 3990 us
mean: 190399.821 us!

Since we are already storing the means for all benchmarking runs, this is simply a matter of showing the data in the dashboard. If you agree it is valuable, I will look into it.

**Comment by schlosna** [comment]
Would be nice to be able to show the higher percentiles (e.g. p99 and p99.9) as well

**Comment by gsheasby** [comment]
Looks like this is done now - closing.
