### ISSUE TITLE
createInMemoryTransactionManager supports more than one schemas.

### ISSUE THREAD

**Issue by zzrabbits** [palantir/atlasdb#1746]
We are able to create a transaction manager which supports multiple schemas 

https://github.com/palantir/atlasdb/blob/develop/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L110

But in the test setup, I can't find a way to create an in-memory transaction manager with multiple schemas https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java#L85

**Comment by zzrabbits** [comment]
@jeremyk-91 does this make sense to you?

**Comment by jeremyk-91** [comment]
Yeah it does - `InMemoryAtlasDbFactory` currently doesn't have a constructor with multiple schemas. I can look at this when I get back, though if it's a high priority do push on it with other members of the team!

**Comment by zzrabbits** [comment]
Multipass has a forked version to support multiple schemas.

https://github.palantir.build/elements/multipass/blob/0fe661208872261b58b170527fed8d5cfde535c4/multipass-atlas/src/main/java/com/palantir/multipass/atlas/MultipassTransactionManagers.java#L54

I am doing a similar thing in Compass.

**Comment by j-baker** [comment]
Hey - there's a really easy way of doing this - you can just do:

```
    private final SerializableTransactionManager transactionManager =
            TransactionManagers.create(
                    ImmutableAtlasDbConfig.builder().keyValueService(new InMemoryAtlasDbConfig()).build(),
                    ImmutableSet.of(SCHEMA1, SCHEMA2),
                    x -> { },
                    true);
```

don't know why you need to copy all the code!

**Comment by jeremyk-91** [comment]
I'm closing out as this is supported in the new API (in #1784).
