### ISSUE TITLE
TimestampAllocationFailures - previousAllocationFailure might not need to be volatile

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1748]
https://github.com/palantir/atlasdb/pull/1718#discussion_r108387307

We added a volatile boolean to check whether an MRTSE had happened before in PR #1718. Because writing a volatile variable flushes even nonvolatile variables modified by a thread to main memory, we might not need `previousAllocationFailure` to be volatile. There is a caveat to this, that we might get a slightly stale error when telling people why the timestamp service is no longer operational, but that's probably OK.

Not sure if it's worthwhile though, as we save one volatile read on an unhappy path case.

**Comment by rhero** [comment]
Yeah we're not going to address this given we'll only want to do this if we add the proper testing and benchmarks, so probably won't be getting to anytime soon.
