### ISSUE TITLE
Do a stress test verifying that PR #1524 fixed issue #1654

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#1753]
From the release notes of [1524](https://github.com/palantir/atlasdb/pull/1524)

> - Cassandra depedencies have been bumped to newer versions; should fix a bug (#1654) that caused AtlasDB probing downed Cassandra nodes every few minutes to see if they were up and working yet to eventually take out the entire cluster by steadily building up leaked connections, due to a bug in the underlying driver.- Cassandra depedencies have been bumped to newer versions; should fix a bug (#1654) that caused AtlasDB probing downed Cassandra nodes every few minutes to see if they were up and working yet to eventually take out the entire cluster by steadily building up leaked connections, due to a bug in the underlying driver.

We should consider verifying that this has actually been fixed now.

**Comment by hsaraogi** [comment]
Closing as tracking on #1654.
