### ISSUE TITLE
Move persistent lock to timelock

### ISSUE THREAD

**Issue by ashrayjain** [palantir/atlasdb#1767]
#1714 for more context. Essentially, we can get rid of the kvs dependency for the persistent lock and make it paxos backed instead.

**Comment by tpetracca** [comment]
Benefits to this:
- Interacting with Persisted Locks can be done while the Atlas client is offline. This is beneficial for being able to take "offline" backups.
- Atlas clients will no longer have any reason to mount any endpoints, as all required endpoints they used to mount will be on timelock.
- We can *potentially* move schema mutation lock over to a persisted lock and remove all the snowflakiness there.

**Comment by ashrayjain** [comment]
For #2, we do expect other endpoints like clean transactions range etc. to still need mounting.

**Comment by gsheasby** [comment]
Not going to do this. Will instead create an immutable timestamp lock to replace backup lock.
