### ISSUE TITLE
Server-side Blocking Timeouts on the Lock Service

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1772]
The "fixed" retry logic in #1747 to address #1680 (really, asking the application layer to handle retrying) caused internal AtlasDB clients to fail tasks outright, when backing off for a while would have worked. We should avoid breaking them by adding a safe way of having a lock request that doesn't fail except under adverse circumstances.

**Comment by gsheasby** [comment]
@jeremyk-91 is this done?

**Comment by jeremyk-91** [comment]
@gsheasby At the time of your message it was code complete and we verified that the fix worked on large internal stack under load, but it hadn't merged. It now has, so I'm closing this out.
