### ISSUE TITLE
Initialize Timelock namespaces via API and not config

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1776]
As @tpetracca has noted on #1771 and #1741, there are some upsides to removing config-based clients for Timelock. 

- Consumers that attempt to read at a namespace that hasn't been migrated to yet will receive whatever the "this namespace doesn't exist" error is instead of an incorrect value
- It allows for arbitrary consumers of timelock without modifying config
- No need to reason about how live-reloading works with Paxos
- No reason to bounce timelock for a new client

This may not be a huge issue long-term since we don't expect to be adding new AtlasDB clients very often, and it's a one-time cost for users, but it does make reasoning about namespace availability difficult.

**Comment by tpetracca** [comment]
It's also worth noting that this is likely *significantly* simpler and faster to implement than #1771.

**Comment by harrybiddle** [comment]
Very much in favour of this change!

**Comment by rhero** [comment]
It's not immediately clear to us if this method is preferred to the config based approach. The owner of the live reloading config PR is going to do an analysis of this approach sometime this week. Throwing into To Do.

**Comment by rhero** [comment]
Actually, I just had another thought about this (not fully fleshed out so bear with me). 

If we're in a world where many services are using a single Timelock cluster, and then we decide some of those services should migrate to a separate Timelock cluster for performance reasons, I think we're going to require downtime for the services that need to migrate. Creating/removing endpoints via config isn't atomic, so we could have multiple Timelock clusters serving timestamps for the same cluster of clients, and the only way to guarantee that all of those clients are using the same Timelock cluster is by taking them offline and modifying their config. So I think I'm in favor of endpoints to initialize and deprecate endpoints as a long-term solution.

Short-term though... I'm still leaning towards whatever is easiest to allow customers to migrate to Timelock without bouncing Timelock.

**Comment by hsaraogi** [comment]
Live reloading clients block in the timelock server config is already in progress. We will not get to this after that as it does not provide additional value apart from aesthetics :p.
