### ISSUE TITLE
Have some way of dumping a table to CSVs and re-importing

### ISSUE THREAD

**Issue by mglazer** [palantir/atlasdb#1777]
Ran into this issue a while ago, but we have some tables that are pretty simple, and basically of the form:

object_id, investigation_id, data_event_id

It would be good if there was some way to export this to some sort of CSV of sorts, and then enable us re-import that table into another instance. Basically, the same concept of exporting a database table from one database, and importing it into another database.

**Comment by clockfort** [comment]
It's a little extra legwork, but you pretty easily roll your own version of this with atlas shell ruby script or atlas console python script.

**Comment by hsaraogi** [comment]
We will not prioritize this as there is not sufficient interest in the feature.
