### ISSUE TITLE
Asynchronous Lock Service

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1789]
**Why?**

Current scheme of allowing indefinite blocking whilst avoiding resource starvation is a rather painful workaround, and the thread per request model ultimately limits the scalability of TimeLock. An asynchronous API would make more sense as outstanding requests don't have to consume a thread each. If we want to consider websockets in the future this would also be beneficial.

**How?**

* Use an asynchronous system which either returns lock grants, or GUIDs indicating deferral. GUIDs can be 'checked on' later to see if the request is still in process or has been completed.

* We still need to clean up stale GUIDs in case a server actually crashed, but this can be done at a much more leisurely pace (e.g. an hour or a day instead of a minute), and clients can have the responsibility of renewing a request.-

**Comment by rhero** [comment]
Backlogging this because it would be a significant API break/addition, but agreed it's the long-term solution we'd prefer for #1724.

**Comment by gsheasby** [comment]
Looks like this was done a long time ago!
