### ISSUE TITLE
TimeLock uses both Jackson 2.6 and 2.7

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1800]
Observed in #1796.

We have some deps on 2.6 and some deps on 2.7, which feels wrong. Ideally we should upgrade everything to 2.7.8 as that's what Dropwizard 1.0.6 uses, but this might require some care to ensure the minor version bump is safe.

**Comment by rhero** [comment]
We're probably not going to prioritize this on its own so we're just going to close it for now.
