### ISSUE TITLE
Sweep locks get released when sweep processes get interrupted

### ISSUE THREAD

**Issue by jamding** [palantir/atlasdb#1804]
I ran an atlas sweep with the --dry-run flag, waited a while, then decided I wanted to run it live, so I control-c'd on my shell and proceeded with the sweep. Waiting for logs and a jstack later I realized the backup-lock had never been released, so I followed docs https://palantir.github.io/atlasdb/html/troubleshooting/index.html?highlight=release%20lock, but didn't have logs for the instanceId, learned later that I could use cql and the blobAsText to get the instanceId for the lock. 

nit: docs suggest $ curl -X POST --header 'content-type: application/json' '<product-base-url>/persistent-lock/release' -d '"instanceid"' but the actual endpoint should be 'persistent-lock/release-backup-lock'.

After clearing the lock and restarting the sweep, I waited a long time before seeing any logs. Maybe there's another feature here or docs update to put future sweepers at ease.

This was hard. I wish this was easier. It'd be great for sweep processes like the AtlasCli to release their locks when they receive SIGINT or similar.

@tpetracca @ashrayjain

**Comment by SerialVelocity** [comment]
I just had a look at the code and I don't think this is the case.

Here's where the lock is taken out:
https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java#L101-L107

Here's where that method is called for sweep:
https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTaskRunnerImpl.java#L259-L261

So if you perform a dry-run you won't acquire the backup lock.

**Comment by jamding** [comment]
Code path makes sense--it's possible the lock was held by a wet run from a
long time ago

**Comment by hsaraogi** [comment]
Does not seem to be a bug. Tracking a similar issue here @gsheasby.
