### ISSUE TITLE
Flaky BindExceptions in WireMock tests

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1811]
Very occasional flake (I think so at least, not having seen this before).

See internal build 2843; WireMock could cause a `BindException` if multiple tests that use it run with it in parallel and use the same port. This led to the issue above (`AtlasDbHttpClientsTest` and `TimeLockMigratorTest` both use port 8080). 

I think it suffices to ensure the port numbers in these tests don't overlap, since the URI is determined by WireMock itself (so it shouldn't be shared with other tests). It would be better if we can find a way to defensively select a port for testing, though.

**Comment by hsaraogi** [comment]
Fixed by #1829.

**Comment by fsamuel-bs** [comment]
Builds are still flaking (see 2973 build in internal infrastructure).

**Comment by jeremyk-91** [comment]
Alright. Currently we have:
`AtlasDbHttpClientsTest` - 8080, 8081
`TimeLockMigratorTest` - 8082
`TransactionManagersTest` - **8080**

I think we previously just used 8080 everywhere and #1829 fixed the timelock migrator, but we still need to bump one of the 8080s.

**Comment by jeremyk-91** [comment]
We should be able to close this as I believe #1840 fixed it. We can reopen if this resurfaces.
