### ISSUE TITLE
Shadowed errors being thrown out of atlasdb-config

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1813]
With the current dependency shadowing changes, client exceptions are going to have the type `com.palantir.atlasdb.shaded.com.palantir.remoting2.errors.RemoteException`, which can potentially be thrown out to the client. This is potentially confusing, since clients that don't use http-remoting have no idea what we're talking about, and those that do are vulnerable to this:

```
RemoteLockService foo = ...;
try {
  foo.lock("me", someRequest); // throws a com.palantir.atlasdb.shaded.com.palantir.remoting2.errors.RemoteException
} catch (RemoteException e) { // a com.palantir.remoting2.errors.RemoteException
  handle(e); // not called
}
```

We could fix this by having some kind of wrapper (duplicates http remoting but doesn't force people to use it), which I think is not unreasonable.

Kind of blocks #1808 in that it makes it difficult to write meaningful tests for the not found stuff...

**Comment by gsheasby** [comment]
Fixed by #1831.
