### ISSUE TITLE
Dropwizard healthchecks for Cassandra/database state

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1819]
This is necessary so that the application is aware of the database state. We should have representation of the following 5 states:
1. The database is completely unreachable (No nodes are up)
2. The database is reachable but the configuration is out of sync with the database state. (eg: Replication factor is different)
3. Less than a quorum number of nodes are reachable. [No operations can be performed]
4. Quorum or more but not all are reachable. [Operations requiring quorum consistency will still run like reads/writes]
5. All nodes are reachable.

This healthcheck will be in the form of performing a simple operation like describe_keyspaces on each node. Also, each available node should have a valid partitioner.

This is a pre-requisite to #930.

**Comment by ashrayjain** [comment]
Do we actually need a distinction between 3 and 1 here?

**Comment by tpetracca** [comment]
For 4, what is our definition of "quorum of nodes are available". I see two possibilities:

1. All nodes but 1 are available - This is the simple/easy to implement and allows for majority of degraded state cases
2. All nodes in a quorum of rack are available - essentially this means you can have more than 1 node be offline as long as they're all in the same rack (and you have numRacks=RF). This is probably a little more in-depth to implement but supports more failure scenarios then 1.

Maybe start with 1 and we can improve to 2 at a later date?

**Comment by tpetracca** [comment]
Agreed with Ashray that 1 and 3 are effectually the same and we should just tread them that way.

**Comment by hsaraogi** [comment]
@tpetracca: I visualize 4 as whether read/write operations can be successful.. I would dig more into option 2, but agree that 1 is the easiest way to achieve that, however with false negatives.

@ashrayjain: Yes, it does make sense to have them as one as no operations can be performed afaik. Can the application do anything differently if only a single db node is available? Then it might be good to give transparency to the application on this.
