### ISSUE TITLE
PaxosQuorumChecker can leave hanging threads 

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1823]
At a high level, the main "body" of PaxosQuorumChecker works as follows:

```java
try {
  while (not enough responses received) {
    pollForResponses();
  }
  while (we still have responses) {
    addResponses();
  }
} finally {
  cancelRemainingFutures(false); // don't interrupt
  reinterruptIfInterrupted();
  logStuff();
}
```

Suppose we have 3 nodes A, B and C; for some reason C is unreachable. Then a PaxosQuorumChecker call on A will succeed with responses on A and B and cancel the call on C - but if the call on C has already started running, we do not interrupt it. This call on C might block for long periods of time, and is also subject to OkHttp (though not Feign) retry logic.

Since this is created with an unbounded newCachedThreadPool() in the timelock server, this can be dangerous behaviour. Although we do not limit the non-Jetty threads in timelock, this can (and has) led to significant thread buildups with noticeably many threads waiting on OkHttp readIo. Eventually, since we need to allocate buffers etc. for this IO, we get an OOM.

**Comment by nziebart** [comment]
Well, looks like OkHttp actually does not respond to interrupts. The underlying problem is that it uses `SocketInputStream#socketRead`, which ignores interrupts (see related discussion at https://github.com/docker-java/docker-java/issues/346)

This is pretty unfortunate, I don't see a simple solution here. Some ideas would be
- use a bounded thread pool (probably should be doing this anyway)
- reduce the timeout on the http client

**Comment by schlosna** [comment]
See https://publicobject.com/2015/01/02/okio-watchdog/ , https://github.com/square/okio/blob/master/okio/src/main/java/okio/AsyncTimeout.java , andand https://github.com/square/okio/blob/master/okio/src/main/java/okio/Source.java as we likely need to close the underlying source to trigger timeout / exception

**Comment by nziebart** [comment]
Screenshot of threadcounts seen in the field. As we can see it's possible for this scenario to propagate to all nodes in the cluster, as they all become unresponsive and cause timeouts/errors for the paxos verifications.

Note that thread counts also spike around rolling restarts (in the image, ~18:10 and ~23:40 are rolling restarts).

![screen shot 2017-07-21 at 6 05 22 am](https://user-images.githubusercontent.com/2740512/28449835-f487b132-6dda-11e7-9009-b49e456754d0.png)
