### ISSUE TITLE
Move ThreadPooledWrapper and ThreadPooledWrapperTest to a different library

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#1837]
Both of these classes were created in #1785 to be reused when needed. Should be moved from the lock-impl module to some other module where it can be reused more easily (e.g. atlasdb-commons).

**Comment by gsheasby** [comment]
Do you mean ThreadPoolWrapper + Test?

**Comment by jboreiko** [comment]
Following logic around 'tragedy of the commons' in software we are going to avoid moving this into a commons library for the time being.  If we find it would be useful elsewhere we will considering moving it out.
