### ISSUE TITLE
TimeLockServerConfiguration should have a builder

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1839]
We have 4 arguments and this grows to 5 after PR #1808; while not immediately serious since the arguments have different types, it soon gets unwieldy trying to read something like

```
TimeLockServerConfiguration configuration = new TimeLockServerConfiguration(
        null,
        CLUSTER,
        CLIENTS,
        null,
        null);
```

**Comment by gsheasby** [comment]
Blocked on #1808.

**Comment by hsaraogi** [comment]
This config class is not used anymore post #2168.

**Comment by gsheasby** [comment]
It does seem to be in use on develop (32 usages).
If it actually isn't in use (or shouldn't be used), let's remove the dead code.
