### ISSUE TITLE
ADR for how the lock retrying works

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1851]
Lock retrying via `BlockingTimeoutException` is a rather funky implementation, and was chosen over several alternative solutions (e.g. client-side lock-time splitting, 'just' bumping the idle timeout to 1 day etc.) after internal discussion.

The PR is #1808.

I'd like to document how we came to this decision.

**Comment by tboam** [comment]
PR for the docs is #1885 but we don't want to merge until the work actually merges to avoid confusion - #1808 .

**Comment by jeremyk-91** [comment]
Both the 'work' and 'docs' PRs have merged, so closing this out.
