### ISSUE TITLE
Pull in Netty based Lock, Timestamp, and Leader Election

### ISSUE THREAD

**Issue by schlosna** [palantir/atlasdb#186]
@rjullman We should pull in the Netty based service that uses protobuf RPC for lock, timestamp, and leader election.

**Comment by markelliot** [comment]
Is that going to be compatible with the Dropwizard setups we're using in a number of places now?

Sent from my iPhone

On Feb 1, 2016, at 11:58 AM, David Schlosnagle <notifications@github.com<mailto:notifications@github.com>> wrote:


@rjullman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rjullman&d=CwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=xzg13yTbFy66cTCsQHaBvz8A6XsM2splVQmP90Xwn6Q&s=pCGCZorqngDCM9VE0o9zs0Cq7JYN2T1ty1x8qNJMlAo&e=> We should pull in the Netty based service that uses protobuf RPC for lock, timestamp, and leader election.

**Comment by tjwilson90** [comment]
The netty version runs as a tcp server instead of an http server and has a hand written client. We could configure it to run alongside the http interface on a separate port.

**Comment by markelliot** [comment]
Why would we want to force this? What's the benefit?

**Comment by tjwilson90** [comment]
I don't think anyone's saying we should force it. We should allow it as an option in addition to the http interface.
Benefit is performance (pacman may have numbers to give you).

**Comment by markelliot** [comment]
Probably worth committing some benchmarks. 

One thing I've been thinking might be good here is to pull lock and timestamp severs into separate repos -- they likely change a lot less frequently than other stuff here, and should be decoupled IMO. Maybe this is a good opportunity for that?

**Comment by jboreiko** [comment]
@schlosna is this still something we should be interested in?

**Comment by schlosna** [comment]
I haven't had any cycles to port this over or do an apples to apples benchmark to compare the two. I'm fine closing this out for now and we can reopen if we decide to later.

@davidscottcohen and @rjullman for thoughts.
