### ISSUE TITLE
Test createTables, truncateTables for DbKvs

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1906]
#1788 changes the behavior of these APIs, we should test that the parallelism is appropriate here.. 
- does changing the ``poolsize`` have any negative impact? (eg: setting maxConnections to one?)
- make sure 16 parallel operations is a sane number.. eg: test creation of 16,32, 50 tables?

**Comment by gsheasby** [comment]
Is this a performance or a correctness test?

**Comment by hsaraogi** [comment]
This will be a correctness test.

**Comment by hsaraogi** [comment]
Blocked on #1788.

**Comment by hsaraogi** [comment]
Closing as the PR does not provide immediate benefits.
