### ISSUE TITLE
Reintroduce Static Analysis

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1918]
When we upgraded Baseline to 0.13.0, we shifted from findbugs to error-prone for static analysis. However, as @ashrayjain points out we've encountered certain unpleasantries with the error-prone compiler, such as a [varargs issue](https://github.com/ePaul/error-prone-compiler-bug).

To ensure safety, given that our trust in said compiler is thus limited, we removed the errorprone plugin before releasing 0.41 in #1914. However this means we have no static analysis tools active, and I think these have been pretty useful at catching accidental errors in the past. We also lose a check for [safe logging](https://github.com/palantir/gradle-baseline#baseline-error-prone-checks).

Either of the following solutions seems good:
1. Reenable findbugs (note: this doesn't seem that easy because findbugs was removed from 0.13.0, and I have qualms about downgrading Baseline after the hard work in #1853; reenabling plain non-baselined findbugs generates a pile of errors)
2. Introduce a shim that compiles with both but only keeps the javac artifacts.

We aren't likely to move to errorprone till July or so when Java 9 GAs and thus the compiler the errorprone compiler is based on is likely to be more stable...

@gsheasby for SA - or if I'm being silly about how to reenable findbugs, which is plausible.

**Comment by gsheasby** [comment]
I'm sure the findbugs error reports used to look nicer, but you're right that there are a fair few errors. It looks like introducing a shim would be a good alternative. Does it get easier if we rescope the problem to "only add the safe logging check"?

**Comment by fsamuel-bs** [comment]
Static Analysis added back with #1924.
