### ISSUE TITLE
Have AtlasDB update CF defs without TableMetadata changes

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1929]
See #1726 for origin / more background.

In the general case AtlasDB will only issue schema updates if it find the TableMetadata to have changed.  Because we gate on TableMetadata updating anything in the default CfDef we have will not result in a schema update on Cassandra.  

In particular this means our current table creation will not update tables to have the newly updated gc_grace_seconds value we would like existing tables to have.

**Comment by hsaraogi** [comment]
Looks like this is already done, https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L263
https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L167
https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1891

Is this a known issue in the field?

**Comment by tpetracca** [comment]
@hsaraogi I'm not sure, but like you said it looks like this should already be auto-updating `gc_grace_seconds` in the field.

**Comment by jboreiko** [comment]
Look at what guards the inclusion of the cf updates in that line you highlighted:

https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1864-L1877

At the top of this block you see a comparison of just the metadata to gate whether cfs are updated.

**Comment by hsaraogi** [comment]
Yes @jboreiko, thanks for pointing this out.. will test the method and update the check accordingly.

**Comment by hsaraogi** [comment]
Fixed #2129.
