### ISSUE TITLE
Further improve Feign retry logic

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1940]
Two improvements have been suggested to the Feign retry logic, as part of #1939. They're orthogonal, but might still be implemented in the same PR (neither is huge).

 - [x] Incorporate jitter in `pauseForBackoff` (see https://www.awsarchitectureblog.com/2015/03/backoff.html )
- [ ] ~Make the backoff after each node has returned NotCurrentLeaderException configurable~

Labelling as P1 as we'd like to get this in for the release after the next release (i.e. 0.43.0)

**Comment by hsaraogi** [comment]
Backlogging to get to Make the backoff after each node has returned NotCurrentLeaderException configurable later.
