### ISSUE TITLE
Drop support for Cassandra 1.2 on develop 

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1957]
Compatibility with Cassandra 1.2 will be maintained on the 39.x branch.

Develop will no longer support C* 1.2.

From @clockfort (who can fill out additional clean up):

cleanup of the code around dealing with some C* 1.2 specific bugs, code dealing with not having good lightweight transaction support, and workarounds for not having a good version of CQL protocol yet.

**Comment by clockfort** [comment]
Started this, but it looks like some of the jank related to KVSs-that-dont-support-CAS can't be removed until JDBCKVS and RocksDBKVS are removed, as they also lack support.
Is there a plan for that?

**Comment by tpetracca** [comment]
@clockfort we discussed in a meeting today that they've been deprecated for forever and we should finally pull the trigger. We can probably just put up a PR and I think @tboam will confirm will cool with actually merging it.

**Comment by gmaretic** [comment]
Blocked on https://github.com/palantir/atlasdb/pull/1966 and https://github.com/palantir/atlasdb/pull/1967

**Comment by fsamuel-bs** [comment]
See #1967 for further context on this.

**Comment by clockfort** [comment]
🎉 we did this, go us 🎉 
(ticket closing spree 2019)
