### ISSUE TITLE
Sweep should detect deletion failures and retry with smaller batch size

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1975]
Cassandra rejects mutations more than 32MB (at least this was the previous default on an internal fruity deployment - is it the global default @ashrayjain?)

Therefore, hefty sweep deletes on cassandra KVS can fail with a "mutation above max mutation size" exception.

Current behaviour: we fail the sweep iteration, and retry it, only to fail again (infinitely and relatively quietly)
Expected behaviour: retry the delete with a smaller batch size, until it works.

**Comment by tpetracca** [comment]
We have a default `commitlog_segment_size_in_mb` of 32, so the out of the box largest allowed mutation is 16mb.

Doesn't this problem just go away with the delete batching? Or is the fear that someone will make the default delete batch size bigger than the default max allowed mutation size? Feels like an edge we should just avoid with smart defaults.

**Comment by hsaraogi** [comment]
Pending testing on internal test stack.

**Comment by fsamuel-bs** [comment]
Sweep was manually tested on a large internal customer with sane defaults and proved to be able to sweep successfully. And a better understanding of the behavior of sweep - in particular the batching on CassandraKeyValueService.deleteOnSingleHost -, along with #2060 should avoid this problem in the future.

The defaults used on the internal large customer were:
```
AtlasDbConfig:
readLimit: 1000
candidateBatchHint: 1
deleteBatchHint: 1000

CassandraKVSConfig:
timestampGetterBatchSize: 1000
```

We're releasing background sweep with them.
