### ISSUE TITLE
Log all paxos rounds

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#1985]
https://github.com/palantir/atlasdb/pull/1974 added metrics around leader election events. As a follow up, we should add logging for each round of paxos for debugging purposes

We should distinguish between the `TimestampBoundStore` and the `LeaderElectionService` in the logs

**Comment by hsaraogi** [comment]
@nziebart wanted to confirm if #2166 fixes this issue?

**Comment by tboam** [comment]
@nziebart is there more logging to add here?

**Comment by nziebart** [comment]
Yes - this issue is for logging every paxos round. We don't do that currently.

This is probably as simple as adding a log message in `PaxosLearner#learn`
