### ISSUE TITLE
Don't get a timestamp for a readonly transaction that doesn't perform any reads

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#1986]
Currently, `TransactionManager#runTaskReadyOnly` results in the transaction being committed in the end. This results in us fetching a timestamp at https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L1194

Some products that use in-memory caching with fall through rely use a pattern where they open a transaction, but may never read any data. In this case we shouldn't make any remote calls.

**Comment by schlosna** [comment]
There are at least a few other things wrong with the start timestamp handling in there:

* We should probably be wrapping the start timestamp supplier in a memoizer as it shouldn't change once locked in for snapshot & serializable transactions.
* We should not be doing expensive operations for the debug logger, when debug logging is not enabled, and should audit this class and package.

**Comment by nziebart** [comment]
Just to note, the start timestamp actually is wrapped in a memorized supplier.

**Comment by schlosna** [comment]
If it's already memoized it shouldn't fetch another

**Comment by nziebart** [comment]
The issue is that it was fetching 1 timestamp where it should be fetching 0. (SnapshotTransaction does not actually get the start timestamp until you do a read, or as we saw here, commit)

**Comment by schlosna** [comment]
Ok, gotcha

**Comment by schlosna** [comment]
Actually, why is it a SnapshotTransaction as opposed to ReadOnlyTransaction where start timestamp should be immutable timestamp?
