### ISSUE TITLE
Opt Out of Specific CassandraVerifier Checks

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2004]
See PDS-53324 for an example of this.

CassandraVerifier does a various number of sanity checks around your atlas config, the actual configuration of the cassandra keyspace, and various other aspects of the cassandra cluster. In some cases deployments fail one of these checks because they're in an unideal layout (but correct for their limiting circumstances). The most common of these is having greater than 3 nodes with RF3 all in the same rack due to hardware constraints on-premise.

It would be great if we could override a single check and still opt-in to the rest of them in these cases. Currently setting `safetyDisabled` to `true` disables ALL the checks.

Also CassandraVerifier could generally use a refactor/cleanup.

**Comment by clockfort** [comment]
Sounds like a reasonable FR to me; we'll want to rewrite a small part of the more complicated C* maintenance docs to accommodate the change, as well
