### ISSUE TITLE
KeyExists() support

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#2019]
I'm writing a caching layer that falls back to atlas. As part of it, I need to check if a key exists in the backing atlas table to inform how I update the cache. Currently, this means fetching the row via get(). Could we consider supporting a lighter weight keyExists() method, especially with existing bloom filters? It should be more performant than fetching the row.

**Comment by clockfort** [comment]
We've mused about adding a KVS call for this in yesteryear, we just didn't have an application that wanted it.
I believe all underlying KVSs can support this in a faster way than the existing API allows; usually as either a primary key index-only lookup or a bloom filter rejection.

**Comment by sandorw** [comment]
It turns out I don't need this. Closing the ticket.
