### ISSUE TITLE
Make Immutables use Java Optionals

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2022]
Despite the fact that #2016 switches to Java Optionals, whenever Immutables actually needs to use an Optional in an Immutable* class it uses Guava. I think this is a setting we have to change somewhere.

**Comment by hsaraogi** [comment]
Blocked on #2020.

**Comment by felixdesouza** [comment]
Can't see any instances of this in the repo, I imagine an immutables bump probably fixed it?
