### ISSUE TITLE
putUnlessExists in generated table code is misleading

### ISSUE THREAD

**Issue by tjwilson90** [palantir/atlasdb#2047]
Example of code as it is generated today
```
@Override
    public void putUnlessExists(Multimap<BucketsRow, ? extends BucketsNamedColumnValue<?>> rows) {
        Multimap<BucketsRow, BucketsNamedColumnValue<?>> existing = getRowsMultimap(rows.keySet());
        Multimap<BucketsRow, BucketsNamedColumnValue<?>> toPut = HashMultimap.create();
        for (Entry<BucketsRow, ? extends BucketsNamedColumnValue<?>> entry : rows.entries()) {
            if (!existing.containsEntry(entry.getKey(), entry.getValue())) {
                toPut.put(entry.getKey(), entry.getValue());
            }
        }
        put(toPut);
    }
```

Before looking at the implementation, I would have expected `putUnlessExists` of a `(row, col, val)` triple to write that triple if the cell `(row, col)` does not exist in the table. This is e.g., what `java.util.Map#putIfAbsent` does if you consider the cell to be a key.

Instead it writes the `(row, col, val)` triple if that entire triple does not exist in the table, allowing you to overwrite an existing triple with a different value.

Now, this is a perfectly reasonable method to have, and may indeed have been what the author intended, but it is very misleading given different behavior of similar functions like `java.util.Map#putIfAbsent`.

What I'd like to see happen is for a method that acts like `java.util.Map#putIfAbsent` to be added, and for the current `putUnlessExists` method to be renamed to something else (as a deliberate compilation break so clients notice that there are two reasonable behaviors).

Feel free to bikeshed, but reasonable names to me are `putUnlessCellExists` and `putUnlessCellAndValueExists`.

**Comment by nziebart** [comment]
is this for dynamic columns or a normal table?

**Comment by tjwilson90** [comment]
I think this example came from a named column table, but I think we should do the same thing for named and dynamic columns.

**Comment by hsaraogi** [comment]
Better names are good, however this will be a major API break. We can look into deprecating the method and add the new one or maybe a better JavaDoc would suffice?

**Comment by tpetracca** [comment]
It's worth noting that I don't believe in practice anyone has ever used the generated `putUnlessExists` code and that there are other known issues with it. For example, #613 seems to indicate that writes in PUE are done at timestamp 0 and thus violate the transaction protocol.

@tjwilson90 is doing a read and then a write within a transaction not sufficient for your use case here? Given the issues around it, I'd almost prefer us to just delete PUE from the generated code as it's definitely not usable in its current state.

CC @tboam

**Comment by jkozlowski** [comment]
Can we please go on and remove this (or deprecate)? 

I also have just discovered this confusing method and would've used it (I want to make sure I don't overwrite values, so I thought this was a nice method to try to use).

**Comment by tpetracca** [comment]
@tboam @nziebart I think we delete this. We really do not want people using it. You can write the effective equivalent of a PUE in a transaction using get and put

**Comment by tboam** [comment]
We can probably change the existing code generation to mark this as @Deprecated and then not include it in the new generated code.  cc @amarzoca

**Comment by bkrieger** [comment]
@tpetracca it looks like there are multiple `putUnlessExists` methods, and only 1 of them is deprecated. Can we get rid of all of them (or at least deprecate all of them)?

**Comment by tpetracca** [comment]
^^ @sandorw @tboam this comes up every few months and we basically all respond about how bad these methods are every single time. Can we just delete them?

**Comment by tboam** [comment]
@tpetracca Agreed, I'll put something in our weekly plan that someone can work on between other tasks.
