### ISSUE TITLE
verbose/spammy logging

### ISSUE THREAD

**Issue by sjrand** [palantir/atlasdb#2048]
Hi friends,

I'm seeing multiple services which use this library log things to the effect of:

```
com.palantir.timestamp.DebugLogger: Timestamp allocator-1881 calling cassandra host <host>/<ip>:9160 started at <time>, [CAS] Setting cached limit to <some_number>
```

Unfortunately, the logs of the affected services are pretty hard to make any sense of, as this message appears many times per second.

**Comment by ash211** [comment]
@sjrand is the attached what you have in mind?

**Comment by sjrand** [comment]
Yep, I think so. The `Timestamp allocator-<number> calling cassandra host <host>` part seems to be the name of a thread, so presumably that part will go away too with your patch.

Thanks for fixing that!
