### ISSUE TITLE
Lock Service should 503, not 500 when leadership is lost

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2057]
Currently, if leadership is lost, we close the lock service, which results in an `InterruptedException` being thrown for all blocked threads. This translates to a 500 error to the client.

We should detect this scenario and return a 503 so that clients can fail over to the new leader.

**Comment by hsaraogi** [comment]
Just map InterruptedException to 503(so it retries on different hosts).  500s dont retry atm.
