### ISSUE TITLE
Remove slf4j-style placeholders in logs

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2074]
The sls-spec (see service logs section in logging page) designates that we should be avoiding using slf4j-style placeholders and that `SafeParams` will not be correlated with placeholders via substitution. We should update our logs to avoid using this.

Instead logs of the following style are preferred:
```
log.warn("Put failed", SafeArg.of("table", tableName), SafeArg.of("txStartTs", startTs), UnsafeArg.of("rowKey", row));
```

**Comment by SerialVelocity** [comment]
@tpetracca This will make Circle builds really hard to debug as there will never be any arguments in our logs anymore.

**Comment by fsamuel-bs** [comment]
We have an internal large consumer of AtlasDB which needs the placeholders on the log lines.
