### ISSUE TITLE
Remaining items for async lock

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2101]
Tracking the remaining items needed for async lock to be in release candidate state:
- [x] `AsyncTimelockResource` implements `Closeable` for the `AwaitingLeadershipProxy` (https://github.com/palantir/atlasdb/pull/2103)

- [x] Add a timeout parameter to lock requests (both for sanity and because we have a product that would like to use the lock service in a nonblocking way (i.e., timeout of 0)) (https://github.com/palantir/atlasdb/pull/2114)

- [x] Add metrics and logging around lock blocking time / Consider adding the thread name to the request for debug logging

- [x] Stress tests 

- [x] Check test coverage on all new classes, add test for 500/503 fix for async lock

--------------------------------- 

- [] ~Re-organize class locations (consider creating a new timelock project rather than having classes in lock-api and lock-impl)~

**Comment by hsaraogi** [comment]
Done.
