### ISSUE TITLE
AtlasConsole `pp table('_namespace').getRange()` deletes namespace rows

### ISSUE THREAD

**Issue by dxiao** [palantir/atlasdb#2105]
Used to work, but now reading the _namespace table from atlasconsole deletes rows...which means that namespaced tables lose references and get remapped...which means you lose all your data. From a read only transaction.

Likely caused by 
https://github.com/palantir/atlasdb/pull/916/files#diff-bf062bd4c13b8c0022080ca8ef49c4d2L943

Can also get rid of letting folks see hidden tables in atlasconsole.

**Comment by berler** [comment]
Opened #2106

**Comment by berler** [comment]
Backport for 0.39.x #2110

**Comment by hsaraogi** [comment]
Fixed by #2106.
