### ISSUE TITLE
BlockingTimeLimitedLockService for Embedded Services (with Leader)

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2108]
Flight deployment observed a problem with the lock service on internal navigation product; consider PDS-54356.

There was a pattern of requests highly reminiscent of #1680, with clear periodicity of 1 minute (which is the default Dropwizard idle timeout).

To fix this we could consider moving them to TimeLock and/or implementing construction of this for non-leaders.

**Comment by schlosna** [comment]
for timelock on Dropwizard, probably worth disabling gzip to avoid `Deflater#end` contention when the Jetty thread local `Deflater`s are finalized, or potentially using something like https://github.com/palantir/http-remoting/blob/develop/jersey-servers/src/main/java/com/palantir/remoting2/servers/jersey/CompressionFilter.java if we need compression (probably don't for timelock).

See https://bugs.openjdk.java.net/browse/JDK-8179001 for more context.

**Comment by nziebart** [comment]
@schlosna witchcraft solves the deflater problem with a special gzip filter, right?

**Comment by schlosna** [comment]
@nziebart WC bumps up the minimum gzip threshold to 1MB

**Comment by fsamuel-bs** [comment]
This is an expected, but rare issue. We're pushing forward with async lock service, which should be the long term solution for this problem. Track async lock on #2101.

**Comment by fsamuel-bs** [comment]
This should be fixed, or at least avoided, with #2091, on one-node configurations (with or without the leader block), since we bypass the HTTP stack with that change. For three-node configurations, we should still recommend the timelock async lock service.

**Comment by hsaraogi** [comment]
We expect people to use async timelock to bypass the retry issue.
