### ISSUE TITLE
AtlasDB-Commons, Java 6 and Canids

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2111]
Internal canid product can't upgrade AtlasDB, because for other unrelated reasons they are forced to use Java 6. The main issue is `atlasdb-commons`; we should also check which other AtlasDB projects said product uses.

Ideally we would also maintain devs' ability to work without necessarily requiring a Java 6 compiler. Like what we do with ErrorProne, we could possibly implement this by having a separate compilation configuration for those projects with Java 6, and ensure that this is tested in CI. We would also need to publish artifacts with Java 6.

@gmaretic this is likely to mean that JAR publish might require a Java 6 compiler. Would that be okay? If not we can probably put in an additional publish config, though we'll need to be very careful that only the 'real' one is actually called when we really do publish e.g. to bintray.

@schlosna @twilson-palantir for SA

**Comment by tpetracca** [comment]
I was under the impression as of a couple months ago we no longer had to support java6?

**Comment by tjwilson90** [comment]
My understanding of why we still need java 6 is that we support patching branches on lts releases that are still on java 6.

**Comment by fsamuel-bs** [comment]
We do support Java 6 on our LTS branches, 0.4.x and 0.39.x, and we backport fixes to them whenever needed. If backporting becomes painful, we can think of a better solution, but right now we'll continue with our current setup (0.41 onwards Java 8 only support).

**Comment by hsaraogi** [comment]
Internal candid product needs Java 6 as they have client side applications in environments where only Java 6 in available. These depend only on AtlasDB commons. We can reintroduce the Java6 support by specifying multiple targets in the gradle config, just as we did before. This will help them take the latest sweep improvements and move to higher Atlas versions going further. @carrino for SA.

**Comment by carrino** [comment]
this is all we need: https://github.com/palantir/atlasdb/pull/2122
it's not all of commons, but just executors

**Comment by carrino** [comment]
we may have a workaround where the 1.6 projects depend on an old version and the 1.8 projects a newer version and gradle will just bump up the deps if you depend on 1.6 and 1.8 stuff

**Comment by fsamuel-bs** [comment]
Fixed by #2122.
