### ISSUE TITLE
Refactor Timelock registration code for use with internal web framework

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2132]
We need to get TimelockServer into a state such that it can be instantiated within the internal web framework. Currently `PaxosTimelockServer` is fairly generic, in the sense that it depends only on a `TimelockConfiguration` and an `Environment`, so the work required here shouldn't be too involved.

@tpetracca for SA

**Comment by jeremyk-91** [comment]
Development for this is on the `feature/timelock-refactor` branch. This issue covers up to and including the full switch to a `PaxosAgent`, but not live reloading.

**Comment by hsaraogi** [comment]
Fixed by #2168.
