### ISSUE TITLE
Lock service should not be shutdown by TM.close()

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2138]
The large internal product creates and passes its own Lock service and expects to use it after TM.close() too. TM.close() is auto-closing the lock service since #2102, which causes unexpected behavior.

**Comment by fsamuel-bs** [comment]
Fixed by a recent pr which made LockService.close idempotent. I'll update this ticket with the number later.

**Comment by fsamuel-bs** [comment]
Related PR is #2144.
