### ISSUE TITLE
Mount new Timelock APIs on embedded clients

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2147]
It would simplify things significantly to just mount the new timelock APIs for embedded clients. This would also expose the `lockImmutableTimestamp` endpoint for the internal backup&restore product.

One consideration here:
Currently `LegacyTimelockService` does some hacky wrapping of the `LockRefreshToken` to get around the fact that `BigInteger` cannot be converted to `UUID` if it's more than 127 bits. If we can enforce that this will never happen, we can remove that hackiness and just convert between the two as in `LockTokenConvertingTimelockService`. This probably involves enforcement in `RemoteLockServiceImpl`, and confirming that no existing services use more than 127 bits, for back-compat.

**Comment by fsamuel-bs** [comment]
Currently, `lockImmutableTimestamp` is in the async-lock branch, which will merge to develop soon. Let's talk with @ashrayjain and @SerialVelocity about this.

**Comment by gsheasby** [comment]
Wontfix - embedded configs will be deprecated.
