### ISSUE TITLE
Use a truststore from the config if ssl is set to true for cassandra

### ISSUE THREAD

**Issue by sh4nth** [palantir/atlasdb#215]
`CassandraClientFactory` should require a truststore in the config if ssl is enabled and use the trustore from the config to create an SSL socket factory preferably using: `com.palantir.remoting.ssl.SslSocketFactories` from `http-remoting`?

Currently it relies on JVM-wide SSL settings via `-Djavax.net.ssl.trustStore`

**Comment by markelliot** [comment]
Yeah, interestingly the CassandraJmxCompactionConfig takes a trustStore, we should clean this up.

**Comment by joelea** [comment]
Being handled in #638

**Comment by jboreiko** [comment]
What is this waiting on?

**Comment by jboreiko** [comment]
@rhero for a ticket like this what are the requirements for closing it (ie moving it out of To Ship)?

**Comment by rhero** [comment]
I think we said that going from To Ship --> Close means we've observed someone use this. So just confirming that a product team has specified their truststore using the new way.

**Comment by jboreiko** [comment]
And who is driving this process of finding a product team that has done it?  Is the expectation that the commiter assign themselves and do it or will you?

**Comment by tpetracca** [comment]
I don't think we need to think about the process that much?

**Comment by tpetracca** [comment]
Confirmed an internal product (the one Shanth was working on when he opened this) is using the sslConfiguration block (thus addressing this issue) in place of the ssl parameter

**Comment by j-baker** [comment]
As is mine.
JB

On Wed, 17 Aug 2016 at 13:50, Tom Petracca <notifications@github.com<mailto:notifications@github.com>> wrote:

Confirmed an internal product (the one Shanth was working on when he opened this) is using the sslConfiguration block (thus addressing this issue) in place of the ssl parameter
