### ISSUE TITLE
Make lock timeout configurable for SnapshotTransaction

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2150]
Large internal product and others may rely on the current behavior for acquiring locks, which is to block indefinitely (in practice, probably limited to ~5 mins depending on how many times okhttp will silently retry)

We should probably make this configurable, and possibly set a higher default value (current is 1 minute). If we do increase the defaukt timeout, we should increase the okhttp timeout as well

**Comment by hsaraogi** [comment]
Fixed by #2158.
