### ISSUE TITLE
AtlasDB clients can't be shut down if BG Sweeper dies with persisted lock persistently unavailable

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2163]
Reference: PDS-54701

`PersistentLockManager.shutdown()` is synchronized on the same object as `acquirePersistentLockWithRetry()`, so if the persisted lock is persistently unavailable then acquire never returns, so the service can never shut down.

**Comment by tpetracca** [comment]
I think the path forward here is to move the backup stuff to using the immutable ts lock and deleting the persisted locks everything.

**Comment by nziebart** [comment]
we could fix this fairly easily depending on how far off the immutable ts lock stuff is - would be nice to unblock a certain deployment that is hitting this frequently

**Comment by hsaraogi** [comment]
The issue is that the shutdown hook and the sweeper thread might deadlock in rare cases. Backlogging for a while as we might prioritise immutable ts lock stuff.

**Comment by gauravtiwari89** [comment]
@hsaraogi @nziebart This happens reliably everytime we try and shut down foundry catalog on lava staging. The only difference between catalog and other services running the same version is that catalog gets a fairly high number of requests per second. 

This is currently blocking promotion of apollo agents/continuous deployment on our stack. Apollo tries to stop the service and fails after X minutes -- blocking the entire upgrade plan. 

-Gaurav
