### ISSUE TITLE
lock CQL KVS use to >= C* 2.2.11

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#2169]
Pretty likely this bug would make our paging sometimes incorrect https://issues.apache.org/jira/browse/CASSANDRA-11223
it's fixed in (soon to be released) C* 2.2.11+

It's not clear whether our read paths would be affected by this and CASSANDRA-8272, CASSANDRA-8273 (Which will be fixed in 3.x)
https://issues.apache.org/jira/browse/CASSANDRA-8272
https://issues.apache.org/jira/browse/CASSANDRA-8273 #

**Comment by hsaraogi** [comment]
@clockfort not sure how close we are to switching from thrift to CQLKVS yet, are you actively working on this, this week?

**Comment by clockfort** [comment]
No intention of working on this issue this week, I just filed this to remind myself to eventually get around to this, as I was reading the commitlog/release notes for this newer C* version

**Comment by hsaraogi** [comment]
I guess this is correctly placed in the backlog then.. Thanks.

**Comment by fsamuel-bs** [comment]
Moving to new issues as we're planning on getting some work done on CQLKVS this week. What's our C* official internal version? 2.2.9? @tpetracca @clockfort

**Comment by tpetracca** [comment]
yea, but bumping to latest soon

**Comment by fsamuel-bs** [comment]
Cool, leaving this thread up to track that, as it's relevant to us. Feel free to close it when a version of 2.2.11 has been released internally.

**Comment by clockfort** [comment]
🎉 we did this, go us 🎉 
(ticket closing spree 2019)
