### ISSUE TITLE
Globally false use of `equals` in ManyClientPoolingContainer

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#218]
My IDE threw a warning on

    private PoolingContainer<Client> delegateForHost(InetAddress host) {
        for (Map.Entry<InetSocketAddress, PoolingContainer<Client>> entry : containerMap.entrySet()) {
            if (entry.getKey().equals(host)) {
                return entry.getValue();
            }
        }
        log.warn("Unrecognized host {}, falling back to a randomly chosen client", host);
        return delegate();
    }

and it looks like a legit bug. Specifically host is of type InetAddress and entry.getKey() is of type InetSocketAddress and so the error case is returned every time.

**Comment by schlosna** [comment]
This could lead to a bad perf regression as it essentially disables token aware routing. @bullman

**Comment by rjullman** [comment]
Fixed by https://github.com/palantir/atlasdb/commit/2dcc482f04d94c994740d99658269f170d7c8d11.
