### ISSUE TITLE
Lower compaction logging to DEBUG/remove

### ISSUE THREAD

**Issue by sarahfbeller** [palantir/atlasdb#2187]
Atlas logs a lot around compaction in a way that made it more difficult to troubleshoot the real root cause of an issue in PDS-54710.

The log line (at ERROR) is

```
com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService: No compaction client was configured, but compact was called. If you actually want to clear deleted data immediately from Cassandra, lower your gc_grace_seconds setting and run `nodetool compact <keyspace> <tablename>`.
```

**Comment by tboam** [comment]
We should move this log line to the initialisation phase so that it is only logged once and downgrade to INFO.

@ashrayjain @tpetracca we should consider if we want to initialise the compaction client by default.

**Comment by tpetracca** [comment]
The compaction client for Cassandra in Sweep is useless unless `gc_grace_seconds` is effectively `0`. Currently we have it at 1 hour.

**Comment by hsaraogi** [comment]
Can we not schedule to run compaction after an hour(+x minutes) once a table is swept?

**Comment by tpetracca** [comment]
yea but I don't actually want to do to that in all cases. A major compaction can have serious performance implications on large tables and take a very long time.

The only reason I'd want Atlas auto-kicking it off is because I have contractural/legal requirements around Hard Delete.
