### ISSUE TITLE
Disable okhttp retries 

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2194]
We've seen issues in the field recently with HTTP/2 connections apparently getting stuck in a retry loop. I've also been able to (unreliably) reproduce this by simulating heavy load and connection errors.

However, today I came across this issue after doing a rolling bounce. There was no load on the stack; only background sweep. A few minutes later two of the nodes had high CPU usage.

timelock-1 was showing 95% usr CPU
90 threads in `latestSequencePreparedOrAccepted`
2 threads in `getLearnedValuesSince`

timelock-3 shows 45% usr CPU
4 threads in `getLearnedValuesSince`

All of the above threads had similar stack traces:
```
 - java.lang.Throwable.fillInStackTrace(int) @bci=0 (Compiled frame; information may be imprecise)
 - java.lang.Throwable.fillInStackTrace() @bci=16, line=783 (Compiled frame)
 - java.lang.Throwable.<init>(java.lang.String) @bci=24, line=265 (Compiled frame)
 - java.lang.Exception.<init>(java.lang.String) @bci=2, line=66 (Compiled frame)
 - java.io.IOException.<init>(java.lang.String) @bci=2, line=58 (Compiled frame)
 - okhttp3.internal.framed.FramedConnection.newStream(int, java.util.List, boolean, boolean) @bci=49, line=238 (Compiled frame)
 - okhttp3.internal.framed.FramedConnection.newStream(java.util.List, boolean, boolean) @bci=5, line=224 (Compiled frame)
 - okhttp3.internal.http.Http2xStream.writeRequestHeaders(okhttp3.Request) @bci=53, line=134 (Compiled frame)
 - okhttp3.internal.http.CallServerInterceptor.intercept(okhttp3.Interceptor$Chain) @bci=32, line=42 (Compiled frame)
 - okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpStream, okhttp3.Connection) @bci=205, line=92 (Compiled frame)
```

I think it should be fine to disable retrying at the okhttp level, as we already have retry logic at the Feign level.

**Comment by jeremyk-91** [comment]
Yep, this should be safe. We already disabled silent retry for RemoteLockService as part of the original debugging of #1680; can confirm that we either go through the Feign default retryer or the failover feign target on all Feign targets from `AtlasDbFeignTargetFactory`.
