### ISSUE TITLE
Sweep shouldn't run during migration

### ISSUE THREAD

**Issue by titatoverheks** [palantir/atlasdb#2209]
Atlas Sweep shouldn't run while doing Atlas migration, as it will change amongst other things, the sweep priority table. Also see https://github.com/palantir/atlasdb/issues/2137.

**Comment by fsamuel-bs** [comment]
Backlog for the same reason as #2201.

**Comment by gsheasby** [comment]
We think this could be fixed by having the migration CLI hard-code the config to disable sweep.

We might be able to get to this next week.
