### ISSUE TITLE
Do we need cache control in ClockService?

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2219]
For various services such as the timestamp service's fresh-timestamp and RemoteLockService's current-time-millis, we use POST because we can't allow caching (I'm not sure if specifying a suitable `Cache-Control` header would also have worked?).

Not sure if this is a concern for the Clock Service (this currently uses GET for `getSystemTimeInnanos`).

**Comment by nziebart** [comment]
oh yeah, i thought i commented on that PR but guess it got lost. we should just make it `POST` for consistency with everything else

**Comment by fsamuel-bs** [comment]
Fixed by #2234.
