### ISSUE TITLE
Poll for KVS on startup

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2239]
**Goal**: TransactionManagers.create does not throw but polls indefinitely on startup.

1. This should be an opt-in feature.
2. Good backoff
3. This was the first impl for #1923. We then decided to do with a different route where we initialize the kvs and other services asynchronously.

Separated the impl off to a branch https://github.com/palantir/atlasdb/tree/kvs-backoff and wanted to keep the ticket around for future. Might be good to backlog for now.

**Comment by tpetracca** [comment]
> This should be an opt-in feature
What is default behavior then?

**Comment by fsamuel-bs** [comment]
Linking to #2260, since it's related and could be done in the same chain of PRs.

**Comment by hsaraogi** [comment]
Closing out as we have asyncInitialize in place and are tracking rollout actions separately. This can now be implemented by a product using:

```
SerializableTransactionManager createTrasactionManager() {
  ...
  SerializableTransactionManager tm = TransactionManagers.builder()...
                                                       .serializable()
  while (!tm.isInitialized());
  return tm;
}
```
