### ISSUE TITLE
Prevent accidentally changing the timelock client name

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2253]
Currently, if you accidentally change the timelock client name in your atlasdb client config, you can get data corruption because you'll likely restart at timestamp 0.

A potential fix here is to store the timelock client name in the db. We could do this alongside the timestamp bound migration step that we already do. Another potential solution @jeremyk-91 mentioned was getting the (approximately) highest known timestamp by checking the _punch table, and confirming that all received timestamps are greater.

**Comment by tpetracca** [comment]
I would actually like to remove keyspace / timelock-client-name from the config and have a generic "namespace" config point in AtlasDbConfig. This controls **both** your cassandra keyspace and timelock-client-name so if you change it you basically start from scratch on both.

**Comment by ashrayjain** [comment]
Tom's suggestion will also make sense for the other kvs's, where the "namespace" will just be used for timelock! :)

**Comment by jeremyk-91** [comment]
@ashrayjain For Postgres does this need to flow through to the db name? I'm not too sure what the conventions typically are for people on DbKvs.

This is rather edge-casey, but an offshoot of this is an awkward user break if you're using a timelock client name >48 characters (assuming that we require the same string for both). At the moment we thankfully require `[a-zA-Z0-9_]*` which is same as Cassandra, but you can also get a user break if a Postgres user decides to have a db name with dollar signs (which is permitted - see [Postgres docs 4.1](https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html)) which TimeLock doesn't allow.

It can be resolved by doing a suitable FF of a new shortened namespace and then stop-bouncing the cluster though.
