### ISSUE TITLE
Make Cassandra (KVS) Tracing Directly Configurable

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2257]
Issue title is bad, sorry. Basically I want to be able to set my tracing configuration via a live-reloadable part of my overall Atlas configuration. I don't want it to be a magic separate file that is looked for in a magic place by my governing process.

**Comment by gsheasby** [comment]
Closing as a duplicate of #1307 (which, incidentally, is tracked as a "dumb bug" that we'd like to fix before 1.0-ing).
