### ISSUE TITLE
Enums with non-final fields in CharacterLimitType.java

### ISSUE THREAD

**Issue by abaker14** [palantir/atlasdb#2258]
Auto-bump job can't pull in 0.53.0 to our internal project due to tests failing with the following message:

"The classes below  are Enums with non-final fields or non-unique @UniqueValue fields. Bugs should be filed on the owners  of these classes: com.palantir.atlasdb.table.description.CharacterLimitType"

Breaking change introduced here: https://github.com/palantir/atlasdb/pull/2220/files

Maybe there should be a checkstyle rule for this?

**Comment by hsaraogi** [comment]
Fixed by #2259.
