### ISSUE TITLE
Sweep and scrub should share more code

### ISSUE THREAD

**Issue by twilson-palantir** [palantir/atlasdb#2266]
Sweep and scrub fundamentally perform the same action, they delete old versions of cells that are no longer visible. The  only fundamental difference to how they work is that the sweeper tries to clean up every cell in a table, while the scrubber only looks at cells that are put on a queue (the ScrubberStore).

Sadly, they share almost no code in common. While the sweeper has seen many improvements lately, the scrubber has not benefitted from any of them. The scrubber also has no tests (at least not within atlas itself).

**Comment by fsamuel-bs** [comment]
This is something we do want to get. But we don't have bandwidth for this now. Backlogging.

**Comment by sandorw** [comment]
Largely tracked elsewhere and is the goal given targeted sweep rollout.
