### ISSUE TITLE
Timelock uris should be live-reloadable for atlasdb clients

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2267]
When running in kubernetes, clients won't know all of the timelock URIs at startup. We'll need to move the timelock client block to `AtlasDbRuntimeConfig`, and support reloading the list of URIs.

@jlz27 @tpetracca  for SA

**Comment by jeremyk-91** [comment]
We fixed this via a chain: #2621, #2622, #2647 and #2648.
