### ISSUE TITLE
"No cassandra node alive" log line appears too frequently

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2273]
A bunch of AtlasDB products have reported that the following log line is the most frequent ERROR seen:
> There are no known live hosts in the connection pool matching the predicate. We're choosing one at random in a last-ditch attempt at forward progress. 

Although these products dont see a lot of 5xx errors, this message can be alarming. To reduce the occurrence of these errors we have some options:
1. The background thread that does the whitelisting is scheduled more frequently (5 minutes currently)
2. There are more retries on hosts before blacklisting. This will make sense only if we reduce the read timeouts for Cassandra (a config parameter).

**Comment by clockfort** [comment]
I'd prefer option 1 rather than option 2.
It's not ideal, but in the current state of things a lot of our operations take multiple seconds to stream back from Cassandra, so lowering the timeouts further could lead to troubles.

**Comment by clockfort** [comment]
The atlas default timeouts for this are also made to match up with default timeouts for the actual C* service configuration's own intra-node timeouts
