### ISSUE TITLE
0.54.0 Release is Ambiguous

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2287]
There are no release notes, and in GHE the tag is not marked as the latest release.

**Comment by hsaraogi** [comment]
I guess they were missing at the time of sending the release email on Friday, but is now fixed.
Release notes: http://palantir.github.io/atlasdb/html/release_notes/release-notes.html, Tag: https://github.com/palantir/atlasdb/releases/tag/0.54.0
