### ISSUE TITLE
Remove sweep dry-run

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2289]
Sweep dry-run was created when our trust in sweep was rather low. It's also rather pointless - you still do a lot of the hard work (the reads), only to skip the deletes, which (in most cases!) is the useful bit. Running dry-run doesn't make the full sweep any quicker, and adds unnecessary complexity to the code.

We should delete the dry-run option.

Possibly blocked on #2231 _et al_ merging.

**Comment by tpetracca** [comment]
+1

**Comment by sandorw** [comment]
Not going to prioritize this separately from wholesale deleting legacy sweep.
