### ISSUE TITLE
Add the schema mutation lock to the shutdown hook

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2296]
Seen in an internal stack: the schema mutation lock was lost probably due to a bounce of the the server that was starting up. The starting server was probably bounced because of the message:
```
Found a table {} that did not have persisted AtlasDB metadata. If you recently did a Palantir update, try waiting until ...
```

We should unlock the schema mutation lock when shutting down cleanly.

**Comment by hsaraogi** [comment]
Backlogging pending new occurrences.
