### ISSUE TITLE
Findbugs warnings in generated schema code

### ISSUE THREAD

**Issue by uschi2000** [palantir/atlasdb#23]
Hi folks,
I get findbugs warnings EI_EXPOSE_REP and EC_BAD_ARRAY_COMPARE on generated XyzIdxTable code for indexes; any chance this could get fixed? Thanks!
  Robert

**Comment by rhero** [comment]
Hey @uschi2000 -- we're not going to get to this anytime soon so we're going to close out for now to keep our backlog manageable. As a longer term goal we'd like to generate schema code with an annotation processor instead of with code.
