### ISSUE TITLE
Timelock server should have a config option that allows using the TimestampBoundStore

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2313]
This is required for the large internal product to start using timelock.

@datval  for SA.

**Comment by hsaraogi** [comment]
Should dbkvs be bundled with the timelock-server?

**Comment by tpetracca** [comment]
I would prefer to see the distribution used by both ecosystems be exactly the same. So yes, will need a runtime dependency on DbKvs.
