### ISSUE TITLE
BatchingVisitableView#immutableCopy should not use a 100k batch size

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2321]
`BatchingVisitableView#immutableCopy` overrides the provided batch hint, and fetches results with a batch size of 100k. The rationale here is probably that since you're loading all values into memory anyway, the result set should be fairly small.

However, we've seen this cause timeouts and cassandra OOMs due to improper usage. It's probably best to reduce this batch size and/or just honor the provided batch hint instead of overriding it.

**Comment by nziebart** [comment]
cc @tpetracca @ashrayjain @jnelson15

**Comment by jnelson15** [comment]
Won't we ignore the 100k if we hint previously?
```
    public static <T> BatchingVisitableView<T> hintPageSize(final BatchingVisitable<T> bv, final int pageSize) {
        Preconditions.checkArgument(pageSize > 0);
        return BatchingVisitableView.of(new AbstractBatchingVisitable<T>() {
            @Override
            protected <K extends Exception> void batchAcceptSizeHint(int batchSizeHint,
                                                                        ConsistentVisitor<T, K> v) throws K {
                bv.batchAccept(pageSize, v);
            }
        });
    }
```

**Comment by jnelson15** [comment]
May be understanding that backward. But either way agreed 100k is probably too high for a default.

**Comment by nziebart** [comment]
The impl of `immutableCopy` ignores the batch hint:

https://github.com/palantir/atlasdb/blob/develop/atlasdb-commons/src/main/java/com/palantir/common/base/BatchingVisitableView.java#L225

**Comment by jnelson15** [comment]
Yeah but if you called `BachingVisitables#hintPageSize`, it'll override `AbstractBatchingVisitable #batchAcceptSizeHint` method, ignoring the value passed. So when `immutableCopy` calls `batchAccept`, we'll hit the overriden method in https://github.com/palantir/atlasdb/blob/develop/atlasdb-commons/src/main/java/com/palantir/common/base/AbstractBatchingVisitable.java#L44 which still uses the original hint.

**Comment by tpetracca** [comment]
I think part of the weirdness here is that the column range scans and the row range scans all use the same abstract code for batchingvisitables, etc., and that different KVS' likely should have different numbers here. I would almost prefer these values were both KVS and row-vs.-dymanic-column specific.

**Comment by gsheasby** [comment]
This code is KVS-agnostic, and _some_ default is needed. The range scan code path goes through the KVS layer, so if desired, finer-tuned defaults can be added there (assuming the user didn't already specify a batch size).
