### ISSUE TITLE
StreamStore v2

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2323]
The current stream store has hotspotting issues. It also has an API that is difficult to use (you have to provide it an `InputStream`).

We should:
- investigate why the current store hotspots, and figure out a way to redesign the schema not to
- consider alternative APIs, potentially one that gives the caller an `OutputStream` to write to

@amarzoca FYSA - this could become a candidate for the v2 codegen stuff

**Comment by SerialVelocity** [comment]
🎉 
Afaik, the current store hotspots because the row key is [timestamp (VAR_LONG), block ID (VAR_LONG)] or something like that

**Comment by hsaraogi** [comment]
1. Plan streamstore impl for not hotspotting
2. Discuss with the internal Search and indexing team.

**Comment by sandorw** [comment]
Closing - clients can hash their row components on the stream store to avoid hotspotting, and I don't think this otherwise sees enough usage to be worth the overhaul at the moment.
