### ISSUE TITLE
New Scrubber queue can cause migrations to fail

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2334]
1. No one actually runs the CLI on upgrade and we just start using the new table ignoring the old one.  Even if someone runs it, scrub migration just truncates the old table, doesnt delete it. This leaves a stray table around.

2. Migration tries to migrate the tables, finds the `_scrub` table and fails. Either migration should ignore the `_scrub` table or scrub migration should do the right thing.

**Comment by twilson-palantir** [comment]
Kvs migration should just ignore _scrub.

It was very much intended for the scrub migration task to be optional.
