### ISSUE TITLE
RequestBatchingTimestampService metrics are probably reported incorrectly

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2335]
See internal dashboard [jkong] RBTS, v.2 (test).
Apparently we can get metrics with `TimelockService.getFreshTimestamps.p99` as 8.7 ms, but `TimestampService.getFreshTimestamp.p99` as 2.6 s. Yet, the p99 of a higher-level operation that does use AtlasDB is less than 2.6 s, suggesting that the metrics may not be reported correctly.

For context:
```
RequestBatchingTimestampService
calls TimelockTimestampServiceAdapter
calls LockRefreshingTimelockService
calls TimelockService (Feign Proxy)
calls the remote service - 8.7 ms
```
with the whole process claiming to require 2.6 seconds.

**Comment by hsaraogi** [comment]
This is probably as the remote service is wrapped in the tritium instrumentation proxy twice one at the service level and once at the `RequestBatchingTimestampService` level. @schlosna for thoughts.

**Comment by jeremyk-91** [comment]
(Ticket was created in error - stack had multiple clusters of the same product, which reported different metrics!)
