### ISSUE TITLE
3rd party evaluation of Atlas storage

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2352]
AtlasDB forms the backend for persisting data across a number of applications.

Bugs like #2226 tell us that not all read-write paths are well tested.

After the internal retrospective meeting on whys, we were thinking if it is worth getting some 3rd party audit of the data storage patterns in AtlasDB.

**Comment by tboam** [comment]
Closing as I think there's very limited value in this approach.  Not clear to me who would do this work or why we think they are more likely to find bugs than we are, particularly given the team's level of knowledge of Atlas vs the ramp up time.

Building and maintaining our own testing stack is more likely to uncover bugs IMO.
