### ISSUE TITLE
Explore publishing artifacts internally for P0s and externalising later.

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2355]
External builds can take upto 25 minutes and are more flaky than internal ones. In P0s situations, this can be significant overhead. Should we have a better story for publishing patch releases faster?

**Comment by hsaraogi** [comment]
We can have a Jenkins job that can point to a patch release to get fast publication.

**Comment by tboam** [comment]
Needs documenting

**Comment by gsheasby** [comment]
Tracking as internal docs PR 10.

**Comment by gsheasby** [comment]
Done.
