### ISSUE TITLE
Add Sweep FAQ to docs

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2359]
A large portion of the support traffic (both tickets and questions) revolves around sweep. Questions like:
* Is it OK to sweep while the cluster is up?
* How can I tell what sweep is doing?
* Sweep is too slow / too heavy - can I do anything about it?
* I swept, but the data size on disk is the same. How can I recover disk space?
* How can I check/set `gc_grace_seconds` for a given table?

**Comment by hsaraogi** [comment]
It should include how to look at the sweep tables via the console.

**Comment by hsaraogi** [comment]
Also, add docs for the sweep priority table schema so users are able to understand the values from the table.
