### ISSUE TITLE
[Docs] When are range scans (not) evil?

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2369]
Had discussion with Harish, @fsamuel-bs and @amarzoca on estimated perf of a given range scan, which seemed OK. Would be nice to have guidance/best practices for what exactly makes a range scan good/bad.

**Comment by tpetracca** [comment]
Am working on stuff that gets at this internally but specifically for CassandraKVS. One of the things thats hard here is that we have an abstract KVS layer but the schema you choose should actually be targeted at the KVS you know is practically going to be used in the field. For example:
- Postgres is good at row range scans, but bad at dynamic columns
- Cassandra is bad at row range scans, but good at dynamic columns

**Comment by hsaraogi** [comment]
@nziebart I think there was an internal document running in this context. Should we add parts of that to our external docs?

**Comment by nziebart** [comment]
this is fixed by https://github.com/palantir/atlasdb/pull/2394
