### ISSUE TITLE
When will 1.0 get released? Been waiting for some time now.

### ISSUE THREAD

**Issue by jugaadi** [palantir/atlasdb#2380]
Is it stable enough to be used in production? 
It would be great if you can occasionally share your experiences in blogs, etc.

**Comment by tboam** [comment]
Hi,

AtlasDB is already a production-ready product, indeed it is used by a number of production systems within our own company.  There may API breaks in future releases but we try to minimise the impact of these.

We don't have an estimate for when we will move to version 1.0.  There are some improvements we want to make before we declare the first version complete (e.g. improving schema generation) and these have to be prioritised alongside other features.

We don't currently have plans to write blogs about AtlasDB, but this could be something we look at in the future.  In the meantime this blog talks about how we implemented a distributed Git server using AtlasDB: https://medium.com/@palantir/stemma-distributed-git-server-70afbca0fc29

Thanks,
Tom
