### ISSUE TITLE
Monitor metrics of all cassandra client pools

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2403]
Currently, we monitor metrics for the first Cassandra client pool registered. We probably want to monitor the metrics for all client pools.

**Comment by hsaraogi** [comment]
This is part of https://github.com/palantir/atlasdb/issues/2341. However, currently the metrics are not aggregate but for the first one that manages to register.

**Comment by jnelson15** [comment]
Ah @hsaraogi did this happen because we removed the host names from the metric name?

**Comment by hsaraogi** [comment]
Yes @jnelson15, that is exactly why this happened :(.

**Comment by fsamuel-bs** [comment]
For more in-depth explanation: per Cassandra node, we create a client pool and register metrics to monitor it. Since #2322 and #2324, as @jnelson15 suggests, we removed the host name from the metric name, and we register the same metric per client pool.

Solutions for this could have a standard prefix per metric, as in "pool1", "pool2"... so that we don't blow up the number of metrics, or having an aggregate metric across pools.

**Comment by tboam** [comment]
Will be fixed by #2400 and related work which will effectively add tags to metric names.  Closing
