### ISSUE TITLE
ClockSkewMonitor gets noisy when node(s) are down

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2410]
If a node is down, each node that is up will attempt to ping it every second, which causes a lot of noise in the logs.

I think we want to preserve the currency of our clock skew estimates, so one possibility is a log blacklist system, perhaps a simpler version of what we do in the Cassandra client pool. In other words, keep a set of hosts known to be unavailable, and for this kind of connection failure log only when they enter or exit the set. This won't work so well if the network is spotty rather than nodes being down, but that seems to be a rarer condition.

@tpetracca, @nziebart for SA

**Comment by tboam** [comment]
This code was only added to measure the 'correctness' of leadership leases.  Given the riskiness of this features we have decided not to invest in it now so let's delete the ClockSkewMonitor code.

We should also verify that we have an appropriate metric which shows which Timelock nodes are 'up' as this actually functioned as a ping for us!

**Comment by nziebart** [comment]
I think there is still value in the monitor, as it gives us data on which to base future decisions about whether leadership leases are viable.
