### ISSUE TITLE
Use Ranged or Row Deletes in Cassandra

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2478]
Currently we issue a DELETE for every unreadable version of a cell, resulting in an equivalent number of Cassandra tombstones as there is old data. Can make this drastically more performant (both on the sweep side as well as overall Cassandra perf not being affected by tombstone volume) by using a different methodology for deleting multiple cells at once.

**Comment by hsaraogi** [comment]
Figure out if thrift supports it.

**Comment by nziebart** [comment]
Looks like thrift supports this. The delete just takes a `SlicePredicate`: https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java#L1359

I think we'd need to add a new KVS method that would accept a range of cell versions to delete, rather than a set of them. Currently, the method can't be sure that they represent a contiguous range.

**Comment by nziebart** [comment]
Thinking about this more.. we could probably leverage this to optimize sweep as well. Currently we must read every timestamp from a row and explicitly delete all of them. In reality, we could probably just do a `limit 1` query for everything less than the unreadable timestamp, and if we find anything, issue a range delete for `[col, ts]` everything between the sweep sentinel (exclusive) and the unreadable timestamp.

**Comment by tpetracca** [comment]
What you describe likely only helps us in the static column case. For dynamic columns we still have the issue of not actually knowing the column names up front. Also I'm not sure sweep even has the column names up front to able to form the query intelligently. Now that I htink about it, how does sweep even do it's deserialization I guess it just assumes the timestamp is the very last piece of the column name and can back it out that way and then not care what the schema/makeup of the column1 is

**Comment by nziebart** [comment]
Yeah this would not work as well for dynamic columns. You could maybe select the distinct column names, and then use the above process, but that probably doesn't buy you much as Cassandra would likely scan the whole row to compute the unique columns.

**Comment by sandorw** [comment]
Implemented as part of targeted sweep.
