### ISSUE TITLE
Range scans unnecessarily pull in too much data for Cassandra

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2479]
In `RowGetter` (which is used by the `getRange` implementation), we construct a `SliceRange` that fetches every cell in every row. Then, in `ValueExtractor#internalExtractResult`, we discard everything except the most recent version of each cell. We could be MUCH smarter and just fetch the most recent cell that is less than our `startTs`.

In the implementation of `loadWithTs`, we construct a `SliceRange` that fetches the most recent value prior to our `startTs`. We should be able to do almost the exact same thing for range scans, because both `multiget_slice` and `get_slice_ranges` take the same `SlicePredicate` object. In fact, the only difference between these two APIs is that one takes a set of keys, while the other takes a range of keys.

The only slight complexity here is that, when fetching more than one column, we'll need to issue parallel range queries, one for each column. A v1 here could just include an optimization for fetching one column.

**Comment by tpetracca** [comment]
Big +1
