### ISSUE TITLE
Metrics docs are out-of-date

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2487]
I've noticed that our sweep metric docs are out of date:
- metrics docs: http://palantir.github.io/atlasdb/html/miscellaneous/dropwizard-metrics.html?highlight=metrics
- sweep metrics: https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepMetrics.java

We should probably double check that our metrics are sane, now that we have a better internal ingestion platform.

**Comment by hsaraogi** [comment]
Probably delete the metric docs page.
