### ISSUE TITLE
Sweep targeted at specific rows

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2508]
Internal fiery deployment observed certain rows from an internal project that are known to be highly versioned, and would like to sweep them specifically. Under the old implementation of Sweep this was possible by curling the Sweep endpoint with certain choices of parameters. The new implementation of Sweep changes the semantics of some of the parameters, and we thus don't quite have this functionality any more.

**Comment by hsaraogi** [comment]
Validate that its still possible to sweep one entire row via an endpoint.

**Comment by hsaraogi** [comment]
Add a sweep-one-row endpoint.

**Comment by gsheasby** [comment]
Fixed by #3094 🎈

**Comment by gsheasby** [comment]
Well not quite (in fact I think we already have a sweep one row endpoint?), but targeted sweep should eliminate the need to do this in the long run.
