### ISSUE TITLE
Use Jackson tags for logging objects

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2545]
Our internal framework uses Jackson to serialize objects. We need to tag our objects, in particular, Immutables, otherwise they won't be logged. We need:

```
@JsonDeserialize(as = ImmutableSweepBatchConfig.class)
@JsonSerialize(as = ImmutableSweepBatchConfig.class)
@Value.Immutable
public interface SweepBatchConfig {
```

**Comment by tpetracca** [comment]
Probably don't need the `@JsonDeserialize` but it doesn't hurt

**Comment by hsaraogi** [comment]
If we find objects that are not logged properly, we should ensure they are json serializable. In general, its not a good practice to log entire objects.
