### ISSUE TITLE
We should ignore `__CLASS_HASH` changes on Schema tests

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2548]
On `SchemaTest`, we check if the generated classes and the old classes are the same, to detect api breaks. We compare the files and require all the lines to be the same. As the `__CLASS_HASH = <hash>` line is not part of the api, it should be ignored when comparing the two files.

**Comment by hsaraogi** [comment]
Can we get rid of the __CLASS_HASH?
