### ISSUE TITLE
[TimeLock] Conflicting Path Param Names in Lock Service

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2553]
We have on timelock a possible path `/{client: [a-zA-Z0-9_-]+}/lock/lock/{client: .*}`

Internal request log framework doesn't quite like requests where path parameters overlap, since it uses a map to store params. Note that this isn't (I think) a problem in Async Lock.

**Comment by nziebart** [comment]
Possible related to https://github.com/palantir/atlasdb/issues/2527

If you're referring to the same issue I don't think it's actually a result of the duplicate parameters (though that may cause other problems)

**Comment by jeremyk-91** [comment]
@nziebart I think it's a separate issue, though this won't actually cause any problems until #2527 is fixed (see comment on that ticket).

Currently if you do

```
jkong$ curl -XPOST -k https://localhost:1234/timelock/api/foo/lock/get-tokens/bar
```

(foo is the timelock client, bar is the lock service client)

You'll get something like

```
{"type":"request.2", <snip>, "path":"/{client: [a-zA-Z0-9_-]+}/lock/get-tokens/{client: .*}","params":{"client":["bar"] <snip>},<snip>}
```

Eventually I'm not sure what we'll get (maybe ["foo", "bar"]?). This ticket is more about the potentially ambiguous behaviour we get once _both_ are working.
