### ISSUE TITLE
Fix the clean-cass-lock-state cli

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2572]
```
Exception in thread "main" java.lang.IllegalStateException: Multiple schema mutation lock tables have been created.
This happens when multiple nodes have themselves as lockLeader in the configuration.
Please ensure the lockLeader is the same for each node, stop all Atlas clients using this keyspace, restart your cassandra cluster and run the clean-cass-locks-state cli command.
```
Users were unable to run the cli, and had to manually drop the extra lock tables.

1. Why is the CLI broken?
2. Why don't we fix this automatically?

**Comment by tpetracca** [comment]
> This happens when multiple nodes have themselves as lockLeader in the configuration.

Were they using TimeLock? The `lockLeader` is determined using the `LeaderConfig` and if you're in HA with external TimeLock, then they don't have a leader configuration. My guess is that then leads them to each choose themselves as the leader.

This is bad :( We need a way to pick lock leaders that doesn't require being aware of the other atlas clients. I wonder if there is something we do with the LockService here instead.

**Comment by hsaraogi** [comment]
@tpetracca filed #2583 for the above issue, we can create a _lock table from all nodes and cassandra will take care of the race condition if it createIfNotExists does what I think it does.

**Comment by hsaraogi** [comment]
Add docs for the `clean-cass-lock-state` after running the CLI on a test stack.

**Comment by sandorw** [comment]
Schema mutation lock tables are dead. 🎉
