### ISSUE TITLE
SlowLockLogger should log at WARNING rather than INFO

### ISSUE THREAD

**Issue by aggie05engineer** [palantir/atlasdb#2577]
From PDS-59157 - we should log lines like:

`com.palantir.lock.impl.SlowLockLogger "Blocked for {} ms to acquire lock {} {}.`

at the `WARN` level vs the `INFO` level. When locks are taking longer than anticipated this isn't informational - something is extending past thresholds.

**Comment by hsaraogi** [comment]
We cant tell whats a typical long period of time for the product using the lock service for their own service.

We should add logging at the client side as the client has more context on what is a long blocking time for the lock request.

**Comment by aggie05engineer** [comment]
I'm not really advocating an increase in thresholds here. 10s is likely long enough for the various reasons you'd want to take a lock in production.

**Comment by tboam** [comment]
PR up #2828

**Comment by tboam** [comment]
Closing as this PR merged, the next release of Atlas (0.73, probably week 1 2018) will include this.
