### ISSUE TITLE
Release notes around 0.61.0 to 0.63.0 a bit confusing

### ISSUE THREAD

**Issue by a-k-g** [palantir/atlasdb#2588]
There's a few issues here- 

- https://github.com/palantir/atlasdb/compare/0.62.0...0.63.0 shows that 
`support persistables in v2 tables` was introduced after `0.62.0` whereas in the release notes it's documented as being in `0.62.0`
- The published release notes suggest changes introduced in `0.62.1` and `0.62.2` whereas on https://bintray.com/palantir/releases/atlasdb there's no artifacts for those versions.
- `0.61.2` and `0.61.3` are tagged and artifacts for them exist but there's no release notes.

**Comment by fsamuel-bs** [comment]
This should be fixed with #2586. We also don't usually publish release notes for long-lived  branches (0.4.x, 0.39.x, 0.61.x), as they're usually backports of develop for the large internal product consumption.

**Comment by tboam** [comment]
Closing as PR has merged
