### ISSUE TITLE
Should sweep take and release the backup lock for every batch

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2605]
Sweep does deletions in batches of 1000 currently and we see that it takes and releases the persistent lock for every batch.

This seems like an overhead. Sweep should hold the lock throughout the delete phase and not release after each iteration (Which lasts for less than 30s), and it releases and grabs in the same microsecond. We can have an optimization here where we release the lock after every 1000th iteration.

**Comment by tpetracca** [comment]
Would prefer for sweep to only ever hold the lock if it's actually deleting data. If we think it's cycling through the lock too frequently I'd prefer if we instead did something like wait for much larger batches of deletes to queue before actually deleting them. Can still issue the actual deletes themselves in batches of 1k or whatever we think is best, but don't attempt to do the deletes at all until you've hit X many cells to delete (or the end of the table).

**Comment by gsheasby** [comment]
I read this issue as "we *are* waiting to batch deletes, but are then repeatedly grabbing and releasing the lock when deleting several batches in quick succession. That sounds like a bug anyway (but could happen if a read batch generates a ton of delete batches).

Sweep should be something like:
```
while (more_data_to_read) {
    cells = readCells(READ_BATCH_SIZE);
    cellsToDelete += getCellsToDelete(cells);
    if (cellsToDelete.size >= DELETE_BATCH_SIZE) {
        delete(cellsToDelete);
    }
}
```

Where `delete` does "grab lock, kvs.delete, release lock".
If `cellsToDelete > 2*DELETE_BATCH_SIZE`, we may want to do multiple delete calls - In this case, should we do:
```
grabLock();
for batch in batches { delete(batch;) }
releaseLock();
```

or:
```
for batch in batches {
    grabLock();
    delete(batch);
    releaseLock();
}
```

**Comment by tboam** [comment]
@tpetracca does the backup product use the immutable timestamp for locks yet?

**Comment by gsheasby** [comment]
Noting that starvation again occurred in PDs-60862.

The backup product will soon release a version that uses the immutable timestamp locks, so we won't need to do anything here - closing the ticket.
