### ISSUE TITLE
Ensure that if there's nothing to delete in sweep that we don't take the delete lock.

### ISSUE THREAD

**Issue by tboam** [palantir/atlasdb#2635]

**Comment by gsheasby** [comment]
This is covered in a test case in [CellsSweeperShould](https://github.com/palantir/atlasdb/blob/0.68.0/atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/CellsSweeperShould.java#L102):
```
    @Test
    public void ensureNoActionTakenIfNoCellsToSweep() {
        sweeper.sweepCells(TABLE_REFERENCE, ImmutableMultimap.of(), ImmutableSet.of());

        verify(mockKvs, never()).delete(any(), any());
        verify(mockKvs, never()).addGarbageCollectionSentinelValues(any(), any());
        verify(mockPlm, never()).acquirePersistentLockWithRetry();
    }
```

We exit the `sweepCells` method early if there are [no cells](https://github.com/palantir/atlasdb/blob/0.68.0/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java#L79) to sweep (i.e. delete).
