### ISSUE TITLE
Flaky tests: Cassandra heartbeat

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2666]
AKA the Heartflake: an annoying, occasional flake where the schema mutation lock fails to be updated.

This is possibly linked to compactions or cluster load, leading to a first-attempt approach #2566 - but this still produced the Heartflake.

**Comment by jeremyk-91** [comment]
This is partially mitigated by #2843 which releases the SML and retries when these tests fail, but there's still scope to fix this.

**Comment by gmaretic** [comment]
We removed the schema mutation lock
