### ISSUE TITLE
Make sweep smarter about creating tombstones

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2691]
1) Thorough sweep (and sweep in general) should be more conscious of the amount of tombstones it's creating in Cassandra, and wait for compactions to occur before sweeping again. E.g. if we sweep a table and notice we delete 1 million cells, and then sweep it again an hour later, Cassandra is going to have to page through lots of deleted data. It would be better to wait ~1 day or force  Cassandra compaction

2) Sweep should recognize if it fails many times in a row due to timeout (potentially due to the issue mentioned above), and move to a different table. Currently, it will repeatedly try the same query indefinitely and get "stuck"

**Comment by gsheasby** [comment]
Fixed by #2732 and #2733.
