### ISSUE TITLE
Provide more customizable sweep API

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2692]
Currently sweep gives you three options for sweep strategy: thorough, conservative, or none.

Some apps have write patterns where the full-table sweep doesn't work so well, e.g. if they have millions of rows, most of which are immutable and therefore pointless to sweep. We could provide an api similar to `SweeperService` which gives apps the ability to sweep certain ranges at will. 

One caveat is that we should ensure we wait for the immutable/unreadable timestamps to pass before actually sweeping, so this may require creating a background queue similar to the current scrub queue.

**Comment by nziebart** [comment]
@j-baker for SA

**Comment by tboam** [comment]
Would current work to track number of writes to specific token ranges help here?  We can then target specific areas for sweep automatically without requiring API users to declare what to sweep?

This doesn't help non-Cassandra backed apps though.

**Comment by nziebart** [comment]
Closing this in favor of Targeted Sweep (see https://github.com/palantir/atlasdb/pull/2787)
