### ISSUE TITLE
Use ExponentiallyDecayingReservoir instead of HdrHistogramReservoir for histograms

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2694]
See http://taint.org/2014/01/16/145944a.html

In `MetricsRule.java` we do use `MetricRegistries.createWithHdrHistogramReservoirs()`, but that is only used for tests. In `AtlasDbMetrics` we end up calling new `MetricRegistry()`.

Moreover, there is currently no implementation of `TaggedMetricsRegistry` other than the one that uses `ExponentiallyDecayingReservoir`. If we decide to action on the above, we will also have to implement it for tagged metrics.

**Comment by schlosna** [comment]
We’re moving in direction of exponentially decaying for all histogram reservoirs in order to provide more immediate feedback.

@ellisjoe for SA

**Comment by ellisjoe** [comment]
Correct. Using `MetricRegistry` and `TaggedMetricRegistry` with the `ExponentiallyDecayingReservoir` is the right thing to do.
