### ISSUE TITLE
Table LogSafety Not Consistent

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2750]
In debugging an issue yesterday I noticed an inconsistency in when a table is decided to be marked safe vs. unsafe.

The particular product's schema sets tables to be safe via:
```
tableNameLogSafety(LogSafety.SAFE);
```

It uses neither
```
allSafeForLoggingByDefault();
```
nor
```
namedComponentsSafeByDefault();
```

Log lines in the `kvs-slow-log` were writing table names to the `service.log`'s `params` map, while lines in `SnapshotTransaction` were writing them into `unsafeParams`.

**Comment by tpetracca** [comment]
Turns out there's just a bunch of logs in `SnapshotTransaction` that aren't wrapped in one of `SafeArg.of` `UnsafeArg.of` or `LoggingArgs.<method>`

**Comment by tpetracca** [comment]
We should probably come up with our baseline check (or something similar) to be able to tell if all log lines are using this or not. Though I guess that might be hard because the last arg can be an exception which wouldn't need the wrapping.

**Comment by tboam** [comment]
Closing as main issue has been resolved.  I doubt we'll get to write compile time checks for this any time soon.
