### ISSUE TITLE
Do not retry 6 times for timed out range scans

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2769]
Currently, we retry any Cassandra request 6 times upon a timeout. For expensive queries such as range scans, this is dangerous as Cassandra may not necessarily have interrupted the query processing (once a query enters the read stage, it won't be aborted).

Some preliminary investigations show that queries that have to retry more than once tend to retry 6 times and fail. We should investigate this pattern more, and consider limiting requests to a single retry upon a `TimedOutException`.

**Comment by nziebart** [comment]
There may be a QoS component here as well: queries that take a long time / time out should be recorded as expensive queries from a QoS perspective.

We already have the query duration as part of the `QueryWeight`, but currently we don't action on it.

**Comment by nziebart** [comment]
We should further investigate the retry behavior in context of the type of error. For example, retrying on a "client pool exhausted" error is fairly intuitive - we are just waiting because there are too many concurrent requests (though a better behavior might be to wait for x seconds and then throw a throttling exception).

TimedOutExceptions are the most dangerous to retry on, for the reason given in the initial comment above.

**Comment by tboam** [comment]
Closing in favour of #2557
