### ISSUE TITLE
Remove partitionStrategy if not used

### ISSUE THREAD

**Issue by gregakinman** [palantir/atlasdb#2803]
https://palantir.github.io/atlasdb/html/schemas/tables_and_indices.html#partitioners

@gmaretic @j-baker @gsheasby

**Comment by gsheasby** [comment]
So partitionStrategy does indeed seem to be unused.

It predates the "partitioning" PR, #124, and is unrelated. Indeed, it predates the move to OSS AtlasDB, although it is used in a couple of our internal products (our internal auth product, and our internal citrus product)

**Comment by hsaraogi** [comment]
Tagging @tboam for FLUP.

**Comment by tboam** [comment]
@gregakinman for my understanding: looks like this is a clean up task to remove this functionality to simplify schema creation by users.  Is that correct?  The existence of this functionality adds some time to writing schemas but isn't blocking development work, correct?

**Comment by gregakinman** [comment]
According to @j-baker specifying `partitionStrategy` is a no-op. It should be removed because it adds the illusion that it does something when it in fact does not. It adds time to writing schemas in the sense that it's additional characters being typed for no effect I guess?

**Comment by tpetracca** [comment]
Is it actually always a no-op? If so, we should almost certainly be removing it. The time added is likely someone seeing it in the API and actually tryign to understand what it is and if/why they should use it.

**Comment by gregakinman** [comment]
Yep, believe Jeremy has a PR up to remove it.

**Comment by jeremyk-91** [comment]
We've released 0.73.0, so I'm going to merge the PR today. Sorry about the delay!
