### ISSUE TITLE
CoalescingSupplierTest can be flaky

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2820]
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
supplier.get();
Wanted 2 times:
-> at com.palantir.paxos.CoalescingSupplierTest.batchesConcurrentRequests(CoalescingSupplierTest.java:73)
But was 3 times. Undesired invocation:
-> at com.palantir.paxos.CoalescingSupplierTest$FreezableSupplier.get(CoalescingSupplierTest.java:177)
```

Internal build 8392.

**Comment by hsaraogi** [comment]
We can make the test less specific. 

Also, try out the test retrying annotations @jeremyk-91 :)

**Comment by jeremyk-91** [comment]
In the end we didn't annotate this with retrying annotations as the original test is probably slightly overspecified. This was fixed by changing it to be _between 2 to N-1 actual calls_ in #2843.
