### ISSUE TITLE
Backport hiding old versions of sweep progress to internal product LTS branches

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2917]
https://github.com/palantir/atlasdb/pull/2911 hides sweep_progress1_5 on develop, we should make sure that this is backported to LTS branches after 0.39.x, along with sweep_progress2 if necessary

**Comment by hsaraogi** [comment]
We should backport to 0.39.x and 0.61.x.

**Comment by hsaraogi** [comment]
@dxiao are these branches the only LTS branches?
