### ISSUE TITLE
Whenever sweep fails N times for this table, skip it

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2934]
We've had several issues of sweep not being able to sweep a table due to:
1. finding `null`s in the transactions table
2. we tried to sweep tables that should not be swept

This could be solved by skipping this table after `n` times. We need to think which exceptions allow us to skip it.

**Comment by jeremyk-91** [comment]
This appears especially pertinent when failed client upgrades are rolled back and said rollback involves crossing a version where a new hidden table based on CAS was introduced.

**Comment by sandorw** [comment]
Unlikely to do this at this point given the existence of targeted sweep.
