### ISSUE TITLE
Tagged sweep metrics are not useful

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2949]
Looks like the default `ExponentiallyDecayingReservoir` that we use in histograms decays our data points too fast to make the metrics of any use other than to determine which table we are sweeping currently.

We should instead use a Gauge<String> that answers this question and probably remove the tagged Histogram altogether.

**Comment by gmaretic** [comment]
PR for the Gauge: https://github.com/palantir/atlasdb/pull/2951

**Comment by gsheasby** [comment]
Remaining work:
- Remove the exponentially decaying histograms
- Merge #2951

**Comment by sandorw** [comment]
Any further work here?

**Comment by gmaretic** [comment]
nope
