### ISSUE TITLE
Online CLIs Can't Run Against Non-HA Atlas Clients

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#295]
I’m trying to work through the concept of an “online atlas-cli”, as in I want to run a CLI against atlas where there is already a service (and thus a lock/timestamp service) running against that atlas keyspace.  If that service is using an embedded lock/timestamp services, then it is impossible for the CLI to then piggy back on that lock/timestamp service because the endpoints never get registered.

So I see a couple of things here:

1. We require services in non-HA environments to use leadership election in order to enforce the creation of the endpoints.  The CLI would just not be leader-eligible.

2. We simply register the endpoints, even when running in embedded mode.  In which case we would make some sort of localServer uri config mandatory for AtlasDBConfig (like it is in the leader block) so it knows where to register them, and the CLI would just have to specify lock/timestamp blocks like it would if it were connecting to an external lock/timestamp

From what I understand @rjullman, the future sounded like we want to enforce external timestamp/lock services.  Not sure what you think the better work around in the immediate term would be then, but both should be relatively straight forward to implement.

**Comment by tpetracca** [comment]
Confirming that option 1 of making the service specify a leader block where quorum is 1, leaders is just itself, and localServer is itself, and then making the CLI specify lock/timestamp blocks where the servers list is just the same array as the service's leaders array worked correctly (as it should).  For the time being my guess is that this is a reasonable work around to the problem.

**Comment by tpetracca** [comment]
So further testing makes me think this is also impossible when attempting to use HA (i.e. leader election).  Let's say I've got 3 clients belonging to the same service that together use leader election to determine who the lock/timestamp server is.  In this case we don't want to configure the CLI with a lock/timestamp block because we don't know who the leader is and even if we did the config would have to change every time the leader changes.  Therefore we want it to be leader election aware, but by giving it a leaders block, the assumption is that the local server is also leader eligible which we also don't want because the CLI is most likely short lived.  So I guess there is a need there around allowing services to use lock/timestamp servers created via leader election without actually being an eligible leader yourself.

Or is this why the servers block in lock and timestamp configs are an array and not a single server?  Because you'd put all the potential leaders in that block and it'll figure out which one to use?  Yea after diving into the code I think this is the case, I just don't have a good dev environment for it.

**Comment by joelea** [comment]
Your analysis at the end sounds right. This is all pretty confusing at the moment, so we're looking at massively shrinking the different config options and separating out "how do we decide who the leader is",  "where is my lock/timestamp service" and "how do I start up a lock/timestamp service". 

We still need to do some investigation into how this is going to affect current consumers, but the first step (that is in progress) is creating a TimeLock Server which lets you easily spin up a HA cluster of lock and timestamp services and try and move people away from running embedded lock/timestamp not in dev.

**Comment by markelliot** [comment]
There was an explicit request from @punya not to expose Lock and Timestamp services when leadership election is unused.

I think the simple solution here, default configure products to offer leader blocks with a single member.

CLIs and followers should list all leaders (if there is more than one) in the lock/time server blocks.

**Comment by tpetracca** [comment]
Closing issue given workaround of just using single node leader election for services.
