### ISSUE TITLE
QosRateLimiter has a thread leak

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2954]
Even when you close the TM, the threads for refreshing the read and write limits are not closed.

Internal reference PDS-63159 (though it's not the full story)

**Comment by gsheasby** [comment]
Consider also creating threads later in the setup process (e.g. after something that's likely to fail)

**Comment by jeremyk-91** [comment]
Should be fixed in https://github.com/palantir/atlasdb/pull/2964
