### ISSUE TITLE
CLIs that need to fast forward timestamp cannot be used with TimeLock

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#2959]
We don't create a `TimestampManagementService` in TransactionManagers when configured to use timelock. This means that clients cannot fast forward their own timestamp, which is a good thing. But this also means that the KvsMigrationCli cannot fast forward timestamp when configured to use timelock, which just makes it unsusable with timelock.

**Comment by gsheasby** [comment]
@fsamuel-bs have we seen pain in the field due to this?

**Comment by fsamuel-bs** [comment]
Nope. Just noticed while doing some other PR.

**Comment by gmaretic** [comment]
Looks like this has been fixed in the meantime
