### ISSUE TITLE
Uneccessary null returned from Persistables

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2963]
Atlas generates the code for persistables:
```
        public SomeValue getValue() {
            byte[] bytes = row.getColumns().get(PtBytes.toCachedBytes("t"));
            if (bytes == null) {
                return null;
            }
            SomePersistedClass value = SomePersistedClass.BYTES_HYDRATOR.hydrateFromBytes(bytes);
            return value.getValue();
        }
```
The `null` here should never be possible as the write was done via serializing an object.

This causes an additional check for getValue returning null, when trying
`getValue().getSomeField()`.

**Comment by schlosna** [comment]
I believe you can still get a null if your schema adds a column but you don’t have a migration task to populate it

**Comment by jeremyk-91** [comment]
Yep - the main concern here would be with schema changes. Is there a specific performance-related need here?

**Comment by hsaraogi** [comment]
No performance related need, closing out. Thanks.
