### ISSUE TITLE
Reusing Cassandra clients after an exception has been thrown can lead to errors

### ISSUE THREAD

**Issue by gbonik** [palantir/atlasdb#2973]
CassandraClientPoolingContainer.runWithGoodResource() returns a client to the pool, unless an exception of a specific type was caught (basically, TTransportException or TProtocolException). The problem is that those exceptions can sometimes be wrapped in a RuntimeException or similar, thus bypassing the "blacklist". This might result in broken connections being returned to the pool, and manifest as test flakes like QA-111187.

See also https://github.com/palantir/atlasdb/pull/2971 . In that pull request, I attempted to address the issue where a client was in a bad state right after checkout from the pool. While that PR should fix an immediate problem (NPE), further discussion with @clockfort revealed that the problem might be deeper. It seems like sometimes we get a connection from the pool that already has unread data in its buffer from a previous query. The only way this can happen in Thrift seems to be when it throws an exception in the middle of a call.

For example, see CassKVSImpl.createTablesInternal():
```
                } catch (TException thriftException) {
                    if (thriftException.getMessage() != null
                            && !thriftException.getMessage().contains("already existing table")) {
                        throw QosAwareThrowables.unwrapAndThrowRateLimitExceededOrAtlasDbDependencyException(
                                thriftException);
                    }
                }
```
This code re-throws a thrift exception as an unchecked exception. Therefore, CassandraClientPoolingContainer still returns it to the pool, and the next call that checks out the same connection from the pool will potentially get a broken connection.

**Comment by gbonik** [comment]
I think the proper way to fix this would be to handle exceptions immediately after each call to the thrift client, and mark `CassandraClient` as invalid if we caught one of the "bad" exceptions (TTransportException or TProtocolException). To enforce this, we'd need to remove `rawClient()` from `CassandraClient` and add wrappers for every thrift call we use to `CassandraClient`.

When returning a connection to the pool, `CassandraClientPoolingContainer` would then check the "invalid" flag on `CassandraClient` and only return the connection to the pool if the flag is not set.

**Comment by fsamuel-bs** [comment]
Yeah, I think we introduced this as a part of the work to wrap exceptions from Cassandra to our consumers (#2550) :(

I don't know the behavior of reusing a connection that threw `TTransportException` or `TProtocolException` though, so I believe we should address this soon, even though this might be fine with our default retry logic.

**Comment by gbonik** [comment]
> I don't know the behavior of reusing a connection that threw TTransportException or TProtocolException though

It seems that one possible result of that is the read buffer still having data from a previous request. Then the next request that reuses the same connection will read the garbage left over from the previous one, instead of reading the actual response. This is pretty bad.

**Comment by gokcanozakdag** [comment]
Closing the issue as pr addressing this issue is merged: https://github.com/palantir/atlasdb/pull/3063
