### ISSUE TITLE
Sweep should batch loads from _transactions

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2979]
Saw this message when sweeping a wide row on a production stack:
```
Re-batching in getLoadWithTsTasksForSingleHost a call to {} for table {} that attempted to multiget {} rows; this may indicate overly-large batching on a higher level. {}
tableRef: "_transactions"
rows: "117147.00"
```
And again with rows = 116123, 7300, and 109687

Sweep attempted to fetch over 100,000 rows from the `_transactions` table. This gets rebatched to a maximum of 5000 rows; we should do some batching ourselves, perhaps `min(16*maxCellTsPairsToExamine, 5000)`.

**Comment by gokcanozakdag** [comment]
Is this worth re-batching given that it is already batched safely. @gsheasby

**Comment by tboam** [comment]
sweep is fine to get this many timestamps so no need to add batching

**Comment by jeremyk-91** [comment]
Still an issue. PDS-69180
