### ISSUE TITLE
SnapshotTransaction ignores ColumnSelection when there are local writes

### ISSUE THREAD

**Issue by nartmal** [palantir/atlasdb#3007]
I was trying to run ``table.getRowColumns(tableRow, table.getColumnSelection(NamedColumn.my_column))`` where tableRow was written within the same atlasTransaction. 

Instead of getting back my single ``NamedColumn.my_column``, I got all the columns from my local write.

@hsaraogi says ``extractLocalWritesForRow`` and the lines below it doesn't take into account the specified columnSelection

https://github.com/palantir/atlasdb/blob/a7c40bd52b48e4904d4496c34d89302f7e107d11/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L379

**Comment by hsaraogi** [comment]
We get all the inmemory writes to the row back instead of just for the column selected.
