### ISSUE TITLE
Docs feedback: "troubleshooting/index" page

### ISSUE THREAD

**Issue by Supalosa** [palantir/atlasdb#3016]
**Page:** docs/source/troubleshooting/index.rst

Specifically regarding "Clearing the schema mutation lock":

* I'm not sure if there's an internal equivalent of the `atlasdb` cli, but I couldn't find it - it would be nice to clarify this (i.e. whether it exists or not, and how to reach it)
* On a more recent Atlas client, the `_locks` table was actually named something like `_locks_700d20d1_419a_4496_9820_775ae02a2b56`, the docs may need to be updated to indicate that the hexadecimal string is present.

**Comment by Supalosa** [comment]
(my slack username is rgrant if you want further clarification)

**Comment by tboam** [comment]
We're moving to endpoints rather than the CLI for some uses, this still requires better documentation though.
