### ISSUE TITLE
ScheduledRefreshingClient is no longer necessary

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#3017]
In #2680, we added ScheduledRefreshingClient to dodge the okhttp integer overflows in square/okhttp#3670. The underlying issue has been fixed in okhttp 3.10, so we could now remove the workaround.

**Comment by gsheasby** [comment]
Marking as P2 and filing mainly for SA, as I don't think there's high value in doing this unless `ScheduledRefreshingClient` causes us problems. Do we get regular short outages while the client is refreshed?

**Comment by pkoenig10** [comment]
Done in https://github.com/palantir/atlasdb/pull/4561
