### ISSUE TITLE
BackgroundSweeper can fail to shut down correctly

### ISSUE THREAD

**Issue by chrisalice** [palantir/atlasdb#3021]
The BackgroundSweeper is a daemon thread but on shutdown, a non-daemon thread interrupts it, and then blocks waiting for it to stop. Unfortunately, if the sweeper is in PersistentLockManager.waitForRetry, the InterruptedException will be swallowed, meaning the thread never shuts down. This is causing an internal auth product to fail to stop gracefully, requiring a kill -9. (Logs demonstrating the exact sequence of events available on request.)

Recommended steps to solve:
 - [x] Fix PersistentLockManager.waitForRetry to correctly call Thread.currentThread().interrupt()
 - [ ] Audit Atlas for any other mishandling of InterruptedException
 - [x] Use a CountDownLatch as well as daemon.interrupt() to signal shutdown
 - [x] Replace all calls to Thread.sleep() with latch.await() in BackgroundSweeperImpl
 - [x] Add a timeout to the join() call in BackgroundSweeperImpl

This should provide a robust long-term solution that cannot be easily broken by any InterruptedException mishandling in future.

**Comment by tboam** [comment]
Done and released on 0.78 (available but not announced yet).

**Comment by chrisalice** [comment]
Note that I did not audit Atlas for any other mishandling of InterruptedException.
