### ISSUE TITLE
Sweep Livelocks On Consistently Appended Tables

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#3043]
Sweep currently decides it is done with a table based on whether the starting and ending row in its batch are the same.

Now consider a table with two rows R1 and R2. As part of sweep, we'll clear everything in R1, and maybe some cells from R2. We'll then consider the iteration done and go to sleep.

While sleeping, suppose a new row R3 is written. As part of sweep, we'll clear everything in R2, and maybe some cells from R3. We'll then consider the iteration done and go to sleep.

Thus, for systems that continuously append rows to tables in a lexicographic order (at least as far as byte ordering is concerned) at a frequency consistently greater than the sweep batch interval plus some epsilon, sweep will never finish (even if the batch size is very large). This can happen for `FIXED_LONG` counters.

Reference: PDS-64566

**Comment by sandorw** [comment]
I don't see us fixing this, given that targeted sweep is our solution to uneven table sweeping. Any complaints with closing it out?

**Comment by jeremyk-91** [comment]
@sandorw I must have missed your comment 2 months ago, but came across this again when searching for something for a support ticket. Targeted Sweep is the way to go here
