### ISSUE TITLE
Enable @Ignore-d Tests in AbstractSweeperTest

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#308]
This will probably require refactoring the BackgroundSweeper to allow the test to control table priority selection.

**Comment by joelea** [comment]
@jboreiko / @SerialVelocity did you already do this?

**Comment by jboreiko** [comment]
We had a commit to unignore these, but it resulted in the same problematic failures.  This should be tackled as part of the sweep refactor when we can properly isolate the logic we want to test.

**Comment by gbrova** [comment]
We should do this before we can make sweep be enabled by default
