### ISSUE TITLE
Fix lock service test build flakes

### ISSUE THREAD

**Issue by markelliot** [palantir/atlasdb#31]
seeing these on Travis (where I guess timing is less predictable?):

    com.palantir.lock.AllLockTests > com.palantir.lock.impl.ClientAwareLockTest.testInterruptibleTryLock FAILED
        java.util.concurrent.TimeoutException at ClientAwareLockTest.java:320

**Comment by rjullman** [comment]
A few other tests are flaky.  I've run across the following:

```
com.palantir.atlasdb.keyvalue.rdbms.PostgresKeyValueServiceTest > classMethod FAILED
    org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException at PostgresKeyValueServiceTest.java:60
        Caused by: org.postgresql.util.PSQLException at PostgresKeyValueServiceTest.java:60
```

```
com.palantir.atlasdb.keyvalue.impl.partition.PartitionedKeyValueServiceTest > testDelete FAILED
    java.lang.AssertionError
```

**Comment by joelea** [comment]
These flakes are probably out of date by now - closing this and will create new issues for new flakes that come up.
