### ISSUE TITLE
Backport spaced vacuums to 0.61.x

### ISSUE THREAD

**Issue by jonathanjgo** [palantir/atlasdb#3114]
**Goals (and why):**

Internal reference PG-114821

**Implementation Description (bullets):**

@jeremyk-91 this is basically a clone of https://github.com/palantir/atlasdb/pull/3031.  Can you help out here?

**Priority (whenever / two weeks / yesterday):** soon

**Comment by jeremyk-91** [comment]
@jonathanjgo I don't seem to have permissions to access said internal ticket. That said, could you check if this is already addressed by #3099 (which looks very much like what we want)? If that is, then we can take 0.61.6

**Comment by jonathanjgo** [comment]
Yes sir, this is indeed a dupe of https://github.com/palantir/atlasdb/pull/3099.  Thanks!
