### ISSUE TITLE
Release schema-mutation lock on shutdown

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#3122]
We release the backup/sweep lock on shutdown, but not the schema-mutation lock. There's been a number of issues recently where services were double restarted after an upgrade, leading to a large number of lost locks. Since the restarts are graceful shutdowns, we could in theory release the lock during the process.

If we consider this, we should confirm that there's no correctness issue if we release the lock, but C* is still processing our createTable command.

**Comment by sandorw** [comment]
Discussed offline, we just need to make sure we wait for a createTable command to complete before releasing the lock and shutting down. Given that, we may want to decrease the timeout for waiting to grab the lock (currently 60s).

**Comment by sandorw** [comment]
We'll certainly do it this week - will update the ticket when it's complete and a release is out.

**Comment by tboam** [comment]
Released in 0.83
