### ISSUE TITLE
Cassandra rolling restarts cause Atlas to be unavailable for a refresh interval

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#3139]
At several internal deployments, it is possible for Cassandra hosts to remain blacklisted for considerably longer periods of time than the nodes are actually down for. This pattern tends to be brought about by a rolling restart of Cassandra nodes.

There is a background thread that is scheduled with a fixed configurable delay that unblacklists nodes. However, setting this to say <10 seconds will cause a lot of network requests. Having say 200 nodes (across all Atlas-using services) all fire their refreshes to a 6 node cluster every 5 seconds, say, could be troublesome.

Quoting from the ticket:

>Ideally:
>1. If things are blacklisted then generally skip them
>2. If you can't contact enough hosts, try the blacklisted ones (maybe just once)
>3. If you try a blacklisted host, and it works, take it off the blacklist

Internal reference: PDS-66807

**Comment by gmaretic** [comment]
We could hit `Blacklist.checkAndUpdate()` or `CassandraClientPoolImpl.refreshPool()` when too many nodes are blacklisted to try to recover
