### ISSUE TITLE
Improved C* compaction performance for delete-heavy stream stores

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#3164]
This ticket tracks atlas-side changes to fix issues we've seen where the stream store, while swept correctly, doesn't easily free up space via C* compactions in some layouts. In particular, `appendHeavyAndReadLight` config causes us to use the size-tiered compaction strategy, which is problematic in practice when streams are frequently deleted and very few streams are live at a time.

Proposed changes include switching back to leveled compaction for these workflows or otherwise tweaking compaction criteria. It's also unclear if we would run into the same problem if background sweep was performant and running regularly throughout the lifetime of the stream store use.

https://github.com/palantir/atlasdb/issues/3154 is related

**Comment by tboam** [comment]
Need to either add a config option or force products tp release mutliple versions to handle migration - tracking on email for now

**Comment by gokcanozakdag** [comment]
Keeping in mind for future schemas.
