### ISSUE TITLE
kvs.dropAllAndClose?

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#3192]
what does london-atlas think about a kvs-level API  for being able to drop the active keyspace and then immediately close the kvs?

%product-with-high-multi-tenancy% is a bit weird in that its going to have lots of open different atlas txn managers, and when we want to delete the contents of one , we can delete all of the tables, but we leak the keyspace that was created for us, and it's not possible in current atlas API to delete it.

**Comment by tboam** [comment]
In the weekly plan for someone to talk to @clockfort about this.

**Comment by clockfort** [comment]
I believe we came to the agreement that a different piece of software would handle this workflow.
