### ISSUE TITLE
VAR_LONG docs suggest that it supports negative values

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#3214]
![screen shot 2018-05-31 at 9 59 36 am](https://user-images.githubusercontent.com/8271534/40772961-5aba80da-64b9-11e8-922c-eb6a65496234.png)

but on the other hand, in `ValueType.VAR_LONG`:

```
@Override
public byte[] convertFromJava(Object value) {
     Preconditions.checkArgument(value instanceof Long);
     return EncodingUtils.encodeUnsignedVarLong((Long)value);
}
```

**Comment by tboam** [comment]
Don
