### ISSUE TITLE
Online vs. Offline CLI

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#322]
I think I already know the answer to this, but wanted to put it out here for others to sanity check and provide thoughts on the last point.

I originally wanted to build out a more structured concept of offline vs. online CLIs but I ran into the following telling me it was impossible/a waste of time:
- Off the top of my head I can't think of a use case for why an "online" CLI shouldn't be runnable "offline".  So no reason for doing anything here.
- The much more interesting use case is making sure a CLI is run when there are no time/lock services running against the atlas context/keyspace, but in the current world this is impossible to actually know.

My only other thought is somehow adding a concept of putting the keyspace in a locked state.  I dont' know enough about lock server or generally how the transaction protocol works, but maybe at the start of an "offline" operation you spin up special lock/time server that sets a global lock, that timestampservice's have to check on spin-up and prevents clients from starting/commiting txns, and then you invalidate any in progress txns, do w/e work you need to, unset the lock, and exit successfully.

**Comment by jboreiko** [comment]
@tpetracca can we get an example of an offline and an online cli that we can associate with this ticket to track the progress of the discussion with concrete changes.

**Comment by tpetracca** [comment]
So for restore we have the clean-transactions and fast-forward CLI commands.  I can't think of a context in which they are either useful or even okay to be run while an actual atlas client is up and running.  For context on what these do see https://github.com/palantir/atlasdb/pull/646.

**Comment by rhero** [comment]
This will be supported with the `--offline` flag as part of #696.

**Comment by gbrova** [comment]
#696 has merged, this just needs a docs update.
