### ISSUE TITLE
Want a 'ConflictHandler.SERIALIZABLE_INDEX'

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#3232]
AtlasDB indexes use dynamic columns. These are only written to with the indexed table, meaning that any write write conflict will necessarily also be a write-write conflict elsewhere.

So, we'd like the write write conflict handling of the ignore_all conflict handler, but the read write conflict handling of serializable (since i needn't read the index with the main table).

Additionally, serializable locks at the level of the row, which is a big perf hit with dynamic columns (and indexes). So, it'd be good to additionally lock at the level of the cell, as with, WRITE_WRITE_CELL.

**Comment by sandorw** [comment]
Done!
