### ISSUE TITLE
Switching from targeted sweep thorough to conservative is broken

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#3242]
the range tombstones will cover the sweep sentinel but new sweep sentinels will be dominated by the tombstones until #3224 merges.

**Comment by gmaretic** [comment]
Switching is also broken on a deeper level, since the strategy is determined at the time writes are added to the queue.

**Comment by gmaretic** [comment]
Document changing sweep strategy needs additional steps

**Comment by sandorw** [comment]
Next steps here? The timestamp changes have merged.

**Comment by gmaretic** [comment]
I'm inclined to say this is a won't fix. The way the sweep queue is implemented is that we have separate queues for conservative and thorough sweep. Therefore all the writes happening before the switch will still be swept using the old strategy, and I would argue this is not incorrect. Fixing this problem would require us to recheck the sweep strategy for each table every time we are about to put a ranged tombstone into it which I find hard to justify.

**Comment by sandorw** [comment]
Agreed, let's make sure we send out some related comms before closing.
