### ISSUE TITLE
KVS slow log could use some cleanup for our newer logging system

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#3243]
`KVSProfilingLogger` / `ProfilingCassandraClient` never had a really ideal way of doing logging; it worked okay when we only had on disk logs, but the way it shows up nowadays is much worse in %our_centralized logging_product%; the way the `primaryLogger` and `additionalLoggerWithAccessToResult` are combined in `KVSProfilingLogger#maybeLog` results in two different logging events rather than a single unified one.

Even worse, it looks like at least from the loglines I'm seeing, the way all this logging infra is oddly constructed in these classes seems to result in no traceId being logged, so its more annoying in our product to massage these loglines back together just based on origin/datetime/message etc.

**Comment by jeremyk-91** [comment]
Hey @clockfort, what version of Atlas is this on?

Regarding the continuation log lines I do see lines like `CassandraClient.get_range_slices({}, {}, {}, {}) at time {}, on kvs.{} took {} ms and returned {} rows with {} bytes` in %internal_logging_viewer% (which does correctly combine both logging functions). There was some code in #2474 that adds a log aggregator to condense these messages - but that is quite old so it's rather unlikely you're on a version that doesn't have it. Are there any specific examples you're still seeing in the viewer that we might have missed in that PR?

Tracing also _seems_ like it works based on a few examples that I looked at (e.g. internal indexing product) - if you have a trace that's broken please do point me to it. Thanks!

**Comment by clockfort** [comment]
🎉 we did this, go us 🎉 
(ticket closing spree 2019)
