### ISSUE TITLE
Targeted sweep keeps an unbounded commitTs cache

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#3246]
`SweepableCells` creates a `CommitTsLoader`, which looks a lot like a cache, but never removes entries and has no size limit. This is bad. Also, in practice, targeted sweep may actually stay current enough that it could share the TransactionManager ts cache.

See also my long rambly comments on https://github.com/palantir/atlasdb/pull/3245.

**Comment by gmaretic** [comment]
Fixed in https://github.com/palantir/atlasdb/pull/3256
