### ISSUE TITLE
Backport logging to leadership election

### ISSUE THREAD

**Issue by jonathanjgo** [palantir/atlasdb#3304]
Internal ticket: PDS-58339

To debug clustered lock issues on 0.39.x and 0.61.x.

Related to https://github.com/palantir/atlasdb/pull/3275

@datval FYSA

**Comment by gsheasby** [comment]
0.61.x: https://github.com/palantir/atlasdb/pull/3344

**Comment by gsheasby** [comment]
Fixed by #3296, #3347, and #3344.
