### ISSUE TITLE
cross-AZ traffic reduction

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#3315]
We can optimistically reduce some amount of cross-AZ traffic by 
- allowing atlas service nodes to discover their own AZ
   - with some fail-through logic for zone discovery via use of AWS/gcloud/azure service URI + cassandra rack info, local hostname and cassandra node hostname parsing, and just giving up and defaulting to old behaviour
- altering the cassandra pool logic to, after establishing the set of 3 nodes with the requested data range's ownership, then have a small weighting/stickiness towards making the initial connection to the data owner of the same AZ

I did run the numbers on cost benefit and it seems worth impl'ing, even though I'm miffed that it adds complication to a codepath in atlas that is already fairly complex / state-machine-y. 

(The data I looked at was traffic costs in USD per impl at our biggest cloud impls; since I couldn't get numbers for just atlas traffic, I fudged it a bit by also looking our cassandra traffic metrics and being logical about how much of the traffic would be to and from services instead of intra-cassandra-node traffic)

**Comment by tboam** [comment]
Going to pull some numbers on this this week to measure the benefit
