### ISSUE TITLE
Cassandra Quorum Deletes

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#332]
We should definitely leave default delete consistency to ALL, but I don't think we should necessarily be preventing people from using cassandra's features here.  People should be able to run deletes at quorum consistency with the understanding they are then responsible for proper maintenance (i.e. repairing) of their cluster.

**Comment by jboreiko** [comment]
I would like to see a justification of why this would not be a dangerous feature to allow anything but ALL on deletion.  Is it a real use case that someone would accept the danger of resurrecting data when it could well break the transactional guarantees?  If so I would like to see a written description of what the trade off would be if the DELETE consistency were dropped to QUORUM.

**Comment by Peter-Cooper** [comment]
Beyond the safety arguments, I view the upside of doing deletes at consistency quorum to be small. Most of our Cassandra deletes are asynchronous to the client application anyway, due to them being performed by sweep.

**Comment by tpetracca** [comment]
I forget the context of who wanted this.  But yea it mostly is important if you want things like sweep/scrub to be HA.

**Comment by gsheasby** [comment]
Closing this as we aren't going to prioritise any time soon.
