### ISSUE TITLE
Atlas could invest in better wide row functionality and avoid using the ByteOrderedPartitioner

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#333]
**Summary:**
Atlas uses ByteOrderedPartitioner which is deprecated for a good reason. It has only one advantage (being able to do range scans on row keys, which is of questionable utility), but the price you pay for it is high. There is a justification that one can implement virtually any schema efficiently by using wide rows with a Random/Murmur partitioner instead. In addition, wide row functionality is missing in Atlas which is probably its greatest deficiency.

**Comment by jboreiko** [comment]
This will be made available in #653.  This does not appear that it will be prioritized anytime soon.
