### ISSUE TITLE
Cassandra KVS putUnlessExists/checkAndSet impls break on cells different in their column component

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#3348]
```
    @Test
    public void putUnlessExists() {
        TableReference tableRef = TableReference.createFromFullyQualifiedName("abc.def");
        keyValueService.createTable(tableRef, AtlasDbConstants.GENERIC_TABLE_METADATA);

        byte[] data = { 1, 2, 3 };
        keyValueService.putUnlessExists(tableRef, ImmutableMap.of(Cell.create(PtBytes.toBytes("row"), PtBytes.toBytes("column")), data));
        keyValueService.putUnlessExists(tableRef, ImmutableMap.of(Cell.create(PtBytes.toBytes("row"), PtBytes.toBytes("anotherColumn")), data));
    }
```

The test passes on DbKvs and in-memory KVS, and my understanding of the javadoc is also that it is meant to work at the cell level - it says things like `concurrent writes to the same Cell will not both report success` and `A single Cell will only ever take on one value`.

However this test throws with a `KeyAlreadyExistsException` on the second call, if using Cassandra KVS. It's a consequence of the way we use the thrift API. Thrift CAS (which in Cassandra KVS backs both KVS pUE and CAS) requires you to provide a list of all old columns and new columns. The current implementation assumes that there are no existing columns (for pUE) / 1 existing column only (for CAS).

One option is to move to CQL for these kinds of statements.

```
cqlsh:boo> insert into "default__todo" (key, column1, column2, value) values (0x12, 0x34, 56, 0x78) if not exists;

 [applied]
-----------
      True

cqlsh:boo> insert into "default__todo" (key, column1, column2, value) values (0x12, 0x343434343434, 56, 0x78) if not exists;

 [applied]
-----------
      True
```

This blocks `_transactions2` work as the proposed schema uses pUEs with dynamic columns.

**Comment by j-baker** [comment]
I think this may well end up a 1 line fix in the current KVS; isn't it just a case of doing a currentValue.orElse(null) instead of not providing a list of current columns? I _think_ C* ignores the timestamp for PUE.

**Comment by jeremyk-91** [comment]
@j-baker Not sure I'm following correctly. Loading the current values and using them would definitely work, but that requires loading the values for the row involved which seems excessive. My current understanding is that the problem is the Thrift version of CAS operates on an entire row basis, as opposed to on a column basis.

**Comment by j-baker** [comment]
ahhh, I get it - you only get to pass the whole new row.
