### ISSUE TITLE
Poor test coverage: SweepStatsKeyValueService

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#3354]
Noticed that SweepStatsKeyValueService doesn't have many tests. I started adding them as I thought I was going to change behaviour as part of fixing #3226, but went another way.

Pushed up a branch, [test/sweep-stats-kvs](https://github.com/palantir/atlasdb/tree/test/sweep-stats-kvs), with the work done so far, but I probably won't continue the testing work now - so filing for tracking.

**Comment by tboam** [comment]
Deprecated code, will not fix.

@gsheasby this is an open source project and we welcome contributions from keen individuals in the community
