### ISSUE TITLE
Add backoff for legacy sweep when there is nothing to sweep

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#3411]
With targeted sweep and not writing to sweep priority, we will start hitting the situation where there is nothing for legacy sweep to sweep, and there never will be. However, we will still do expensive range scans trying to find the next table to sweep. We should either stop trying and keep reporting nothing to sweep (if it's easy to know at that level we are using targeted sweep), or implement some backoff strategy.

**Comment by tboam** [comment]
Done
