### ISSUE TITLE
When the clock for timelock goes back in time, unreadable timestamp gets stuck

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#3425]
When trying to determine why targeted sweep was running behind in some cases, ran into this situation multiple times. How do we fix this in a way that doesn't reoccur when the offending node becomes the leader again?

**Comment by tboam** [comment]
Following up to understand why clocks may go back by large periods of time.  We should be fine with changes of a few hours, but longer periods will lock the unreadable timestamp for too long.

**Comment by gmaretic** [comment]
Turns out it was the puncher thread silently dying: https://github.com/palantir/atlasdb/pull/3427
