### ISSUE TITLE
Targeted Sweep does not interact well with truncation

### ISSUE THREAD

**Issue by tjwilson90** [palantir/atlasdb#3475]
I have an atlas table that is used as a background reindex queue (it's filled up with writes, then scanned through and truncated).

With targeted sweep on, I see behavior consistent with the following events.
1. A row is written to my queue and to the targeted sweep queue.
2. I truncate my queue (actually delete range, but same effect).
3. Targeted sweep writes a timestamp -1 sentinel row to my queue for the earlier row.
4. I scan my queue, hit the -1 sentinel row, and get an exception.

This happens both with SweepStrategy NONE and CONSERVATIVE (haven't tested THOROUGH since I want read only transactions, I would prefer to use NONE since I clean the table myself).

Fixes I would like to see are 1) if my table has SweepStrategy NONE, targeted sweep should not interact with it, and 2) if targeted sweep doesn't delete anything it shouldn't write a sentinel row.

**Comment by j-baker** [comment]
2 isn't going to be possible - a big boon of targeted sweep is that it doesn't have to look at the value to do any sweeping. 1 is a bug which we should fix. Targeted sweep shouldn't be sweeping tables where the user doesn't want them to be swept.

**Comment by gmaretic** [comment]
As @j-baker said, 2. is an integral part of how targeted sweep works.

Writes to tables with sweep strategy NONE are filtered out and not persisted to the queue. Do you have steps to reproduce TS sweeping NONE tables? The one way this could happen is if the table metadata does not exist, it is malformed, or we fail reading it from the KVS, in which case we default to CONSERVATIVE and log:

> "Failed to obtain sweep strategy for table {}. Assuming sweep strategy is CONSERVATIVE."

This was determined as the most reasonable option at the time, but I we can change it to hard fail in case of a read timeout. Note that that would abort the transaction, but since the metadata is cached, it shouldn't be hit often. @j-baker thoughts?

**Comment by tjwilson90** [comment]
From what I can see, every write is passed to the sweep queue from https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L1365 and I didn't see any code further down that path that would filter NONE tables out. Where is the filtering supposed to be done?

My table was originally a CONSERVATIVE table, but I changed it to NONE and regenerated the schema (through `TransactionManagers.builder().addSchemas(...)`). I expected errors might continue for awhile until my code did a complete pass through the queue and targeted sweep finished processing anything it had already persisted, but it didn't appear to be be self correcting as I'd hoped.

**Comment by gmaretic** [comment]
It's filtered out here:
https://github.com/palantir/atlasdb/blob/165ca7f7213d9294581d00989c4112ca563720f8/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueTable.java#L57

Once writes are in the queue, changing the sweep strategy of the table will not affect them, and those writes will still be swept using the old strategy. Also, if you do not bounce the atlas nodes, new writes will still be put into the sweep queue with the old strategy as the strategy is cached.

**Comment by gmaretic** [comment]
https://github.com/palantir/atlasdb/pull/3477

**Comment by tjwilson90** [comment]
Ok, I suppose I must have not been waiting long enough and was getting errors from rows remaining behind in the sweep queue.
