### ISSUE TITLE
Migration / Upgrade Benign Errors

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#350]
Request came in internally (below).  It reported error messages that were known to dev as being benign yet were still being logged at Error.

What I meant was basically – I do an upgrade, Cassandra seems to be up, but am I actually good to go? I mentioned this because I did a fresh install recently and I get a lot of these messages in my logs:
```
ERROR [2016-04-18 18:23:41,396] com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService: While getting metadata for tables, we found the following tables that do not exist in the database, but are represented in the metadata table: [_timestamp]
WARN  [COMMIT-LOG-WRITER] 2016-04-19 18:01:54,257 AbstractCommitLogService.java:117 - Out of 140652 commit log syncs over the past 300s with average duration of 0.01ms, 123 have exceeded the configured commit interval by an average of 6.36ms
```

 And some others I have lost the track of. I hear some of these are benign but I don’t know for sure – I thought, if you guys knew about them/knew what the different cases (probably?) meant, you could write a tool to message it out.

**Comment by gbrova** [comment]
FWIW, the first one

```
ERROR [2016-04-18 18:23:41,396] com.palantir.atlasdb.keyvalue.cassandra.CassandraKeyValueService: While getting metadata for tables, we found the following tables that do not exist in the database, but are represented in the metadata table: [_timestamp]
```

was cleaned up in #330
