### ISSUE TITLE
Cassandra Authentication

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#360]
Provide a means for configuration of authentication credentials that are passed to the cassandra client.

**Comment by clockfort** [comment]
What is diff between what you want here and something like https://github.com/palantir/atlasdb/pull/219

**Comment by tpetracca** [comment]
So 219 is just for SSL.  I want to support username/password based authentication (likely using cassandra internal auth as I think external is only supported by DSE unless we roll our own).

Use case is I want to be able to have keyspace level security, so that if one atlas client gets popped then only the data for that client's keyspace is exposed; data from other clients' keyspaces that share the same cassandra cluster are still secure.

I'll have a PR for this tonight.

**Comment by clockfort** [comment]
Cool.
