### ISSUE TITLE
CKVS can return metadata for deleted tables

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#3625]
CKVS (and maybe other KVSs, I didn't check) can return previously deleted tables in a call to KVS#getMetadataForTables() (the one that gets all of the metadata with no filtering) 

This is because CKVS (and I think all of the other KVSs) record table deletion with a table metadata insert of (tablename, fakeCol, current wallclock, byte[0]), and it happens to not filter out non-live tables whose most recent cell's value is a byte[0] in this particular codepath.
There is also some oddness around tables with missing metadata that are also defaulted to byte[0] when returning.

https://github.com/palantir/atlasdb/blob/abf54b5c158bdf1794f1c545c0374cf2053898e4/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java#L1602-L1646

@gmaretic do you want to look into this as part of your table metadata fixes, or should I put something in (after your thing merges)?

**Comment by gmaretic** [comment]
Do we want to just put a ranged tombstone across the entire Long value range in CassandraTableDropper for both the row corresponding to table name and the one corresponding to its canonical form? Putting the empty byte array is then redundant unless we specifically lose a node after dropping the table and before updating metadata.

I want to look into some other weirdness around metadata, my favourite being Cassandra being case sensitive while AtlasDB trying to enforce case insensitivity -- try to call CKVS.createTables({AA, aa}) for fun results...

Anyway, I'm OOTO for almost two weeks staring today, so feel free to fix things :)

**Comment by clockfort** [comment]
The ranged tombstone sounds good to me.

To be clear, this isn't a sweep-managed table, so currently we leak all the historical table schema changes ad infinitum, but I've actually been (ab)using that to do some debug work for internal ticket PDS-76535, but such debugging workflows should hopefully never be necessary in a future where table metadata stuff isn't a hot mess.

**Comment by gmaretic** [comment]
Fixed in https://github.com/palantir/atlasdb/pull/3649
