### ISSUE TITLE
Initialization fails if callback does not succeed synchronously

### ISSUE THREAD

**Issue by pkoenig10** [palantir/atlasdb#3645]
This regression was introduced in https://github.com/palantir/atlasdb/commit/c26679face65c4d02486ba88b89947bf608d43b5#diff-9b38f0dca31254623a28acd3cd59cbe0.

We attempt to run the callback synchronously (which is sensible), but then call `changeStateToCallbackFailure` if it fails. This is a break since clients did not previously have a way to indicate failure without throwing an exception.

The desired behavior here seems correct, but the ability to return a boolean needs to be exposed to clients. This is currently possible, but only by overriding the `Callback` methods, which is something that we probably want to avoid.

Changing `Callback#init` to return a boolean would resolve this problem by:
1. Allowing clients to return false
2. Forcing clients to address the behavior change instead of silently breaking

**Comment by gmaretic** [comment]
We only fail if the callback is not retryable, i.e. its cleanup method rethrows. The old behaviour in this case would have been to try asynchronously, but it would still have failed permanently.

**Comment by pkoenig10** [comment]
Right, I misread this a bit. I noticed a behavior change because my callback was blocking, waiting for something that happens after initializing the transaction manager. But that might just be incorrect use of the async callback, since the callback was never guaranteed to run asynchronously. I can resolve the issue by overriding the `cleanup` method to not throw.
