### ISSUE TITLE
Improve node blacklisting logic

### ISSUE THREAD

**Issue by JawwadF** [palantir/atlasdb#3688]
Internal reference: 79545

P0 FLUP:
blacklisting needs to be smarter: the KVS check fails because we had more than 1 node blacklisted. We blacklist more than 1 node because we blacklist anything producing failures - but the failures in this incident aren't because of the node we communicate with but because of the node that is down

@tpetracca @leonz

**Comment by tpetracca** [comment]
Haven't confirmed yet, but my theory was:
- single cass node down for extended period of time
- targetted sweep tries to delete something with a replica on the dead node
- the delete is done at consistency ALL so no matter what node you talk to you get InsufficientConsistencyException
- atlas starts blacklisting every node as it tries to delete by hitting random ones (and keeps failing cause the 1 node is still down)
- the blacklisting causes the KVS status check to return a worse state than the cluster is actually in

CC @amandachow

**Comment by gmaretic** [comment]
We only blacklist hosts if we see a `SocketTimeoutException` or a `ClientCreationFailedException`

**Comment by gokcanozakdag** [comment]
I confirmed that there were only one blacklisted host at that time, using the internal metric tool - dashboard name is `Cassandra Retry Strategy` (I think I should rename this)
