### ISSUE TITLE
Properly wait for C* to be up before using it in tests

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#373]
At the moment I added a random Thread.sleep(5000) after CassandraService.daemon.start() and I should be polling it in smaller increments until it responds correctly and then proceed.

**Comment by gbrova** [comment]
I've used [Awaitility](https://github.com/jayway/awaitility) for this sort of thing before and was pretty happy with it.

**Comment by jboreiko** [comment]
This was fixed as part of work to move toward dockerized testing dependencies.  The commit that appears to replace it is c51f714fe9533dc37074c52e6e8345035befbd3e
