### ISSUE TITLE
Error-free schema on SweepSchema's "dummy" row component

### ISSUE THREAD

**Issue by ash211** [palantir/atlasdb#375]
Thanks to additional logging at https://github.com/palantir/atlasdb/pull/248 we now have warnings for certain anti-patterns in schema.

One thing this reveals, as noted at https://github.com/palantir/atlasdb/pull/248#issuecomment-197587429 is that this is now complaining about the builtin SweepSchema's "dummy" row component!

The unfortunate side effect is that all consumers of AtlasDB now get this error appearing in their logs:

```
19:04:16.674 [main] ERROR c.p.a.t.description.TableDefinition - First row component dummy of type VAR_LONG might cause hot-spotting with the partitioner in Cassandra.
```

Can we please fix this schema so it's not so noisy everywhere?

Thanks!
Andrew

**Comment by clockfort** [comment]
Your guess is correct. We're planning on putting in an option in TableDefinition to suppress it like .ignoreSuboptimalLeadingRowComponents() or some-such

**Comment by ash211** [comment]
Sounds good, looking forward to it!

What's the reason it's ok to suppress this warning for this table vs changing the schema to something that's warning-free?

**Comment by sarahfbeller** [comment]
Any update here? Juggernaut saw this on upgrading to Multipass 1.11 (https://support-jira.palantir.com/browse/PDS-43809) and were confused that it was an ERROR since they don't use Cassandra. Can we turn down to WARN or change the schema please?

**Comment by clockfort** [comment]
@sarahfbeller  #491 idk if it's in a release yet or in MP yet

**Comment by clockfort** [comment]
Going to close this issue though, as the fix is at least merged on develop.

**Comment by ash211** [comment]
#491 does not appear to have been part of the 0.6.0 release so we're going to have to wait until the next release to get this into MP @sarahfbeller
