### ISSUE TITLE
Lock down gh-pages so only atlasdb team is able to make modifications

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#389]
- [ ] github user is provision for circleci to commit docs and given permissions of atlasdb team
- [ ] circleci is set up to use users permissions for build / commiting of docs changes

**Comment by joelea** [comment]
@jboreiko is this done now?

**Comment by jboreiko** [comment]
Now locked down - if develop docs plublishing starts failing we will need to revisit but should be working.
