### ISSUE TITLE
Make it so that there is only a single initialization path for AtlasDB connections

### ISSUE THREAD

**Issue by mglazer** [palantir/atlasdb#390]
Refer to: https://github.com/palantir/atlasdb/pull/372 for more background here. But the gist is that there's no single path through which someone instantiates an AtlasDB connection. It would be really helpful if there was only a single path here (and prevented people from going around it by making the various implementations package private), because it would make doing things like injecting version information throughout the code much easier (and possibly adding things like proxies to the implementations much easier).

**Comment by gsheasby** [comment]
We'll do this as part of another task, if it comes up, but won't be prioritising doing it on its own right now.
