### ISSUE TITLE
AtlasDB users should have easy access to deploy their products with Atlas utilities - notably AtlasCli and AtlasDB Console

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#391]
- [ ] Deployments should not have to worry about including AtlasDB utilities + their depedencies when deploying their product with Atlas.  This should be taken care of by a Gradle plugin that takes the version of AtlasDB and adds a task to their dist building process to add scripts and dependencies for AtlasCli / AtlasConsole.

**Comment by jboreiko** [comment]
The priority of this issue increases as we expect products to use a CLI to execute backup.  I'm interested in @tpetracca 's thoughts on how this works with backup/restore.  @shashiadi flagged this as a priority.

**Comment by tpetracca** [comment]
Yea I think we need to have a good story for this ASAP.  Ideally we'd publish a gradle plugin and it could just be applied to the product using it's build script and voila the rest is magic.  As long as an "atlas-cli" executable (or equivalent) ends up getting packaged in the product's distribution with minimal work done by the product development team I'm happy.  That CLI has numerous things required for backup/restore to successfully work.

**Comment by jboreiko** [comment]
First shot at this work can be found in #399 - closed for the moment to keep PRs fresh.

**Comment by jboreiko** [comment]
Work for this can be found on feature/atlas-plugin-fork

**Comment by gbrova** [comment]
Quick update - continuation of this work at feature/atlas-plugin-fork-2

Also shared with an internal team requesting feedback.

**Comment by joelea** [comment]
Blocked on figuring out who is going to take this on: @rjullman or @gbrova

**Comment by gbrova** [comment]
I'm happy to yield this. @rjullman , let me know in case you want me to take over.

**Comment by joelea** [comment]
This is being worked on in https://github.com/palantir/atlasdb/pull/463 - please re-open if necessary.

**Comment by tpetracca** [comment]
I think @gbrova is working on this now, hoping to get something out in a week or so.

**Comment by gbrova** [comment]
@SerialVelocity is working with me on this.  We should prioritize it after we finish #444, though that might take a couple more days.

**Comment by rhero** [comment]
PR is #696.

**Comment by gbrova** [comment]
#696 has release notes, but we should probably document more thoroughly.

**Comment by gsheasby** [comment]
Docs are done. Moving this to "to ship"
