### ISSUE TITLE
AtlasDB build incorrect JDBC Url with 2-way SSL

### ISSUE THREAD

**Issue by jonathanjgo** [palantir/atlasdb#3925]
> Atlas can't connect to Oracle with the JDBC url built by OracleConnectionConfig. This is because it doesn't extract the String value of the Optional returned from getServerDn(). So the relevant portion of the JDBC url looks like this when a certificate is provided:
> ```
> (SECURITY=(SSL_SERVER_CERT_DN="Optional[CN=<cert CN>"])))
> ```
> https://github.com/palantir/atlasdb/blob/e496ec134342e6d47b1fdbffc71efc27a4bf690e/atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java#L53

See internal ticket PG-130873 for more details.

**Comment by mswintermeyer** [comment]
I believe this was incorrectly filed against Open Source Atlas and the problem occurs at a different level
