### ISSUE TITLE
Targeted Sweep can stop forward progress on atlas when a single C* node is down

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#3999]
redacted log that shows poor behaviour:
https://gist.github.com/clockfort/4789976034dfa2db38e16bfe3631c1be
This ended up taking out essentially an entire staging stack because the service in question was MP and it became unresponsive.

There's a bad combination at play of:
- a single C* node in an otherwise healthy cluster legitimately goes down
- all the cool projects have targeted sweep running
- targeted sweep uses a call that requires all cassandra nodes to be up
- the CKVS pool code treats c.p.atlasdb.keyvalue.api.InsufficientConsistencyException as something that it should use to blacklist nodes out of the pool, which doesn't really make sense ("I'm banning you because you told me you couldn't do the operation because you think someone else is offline")
There is a niche case where it _might_ make sense to do that, during a network split in between the C* nodes, but 99% of the time...
- targeted sweep keeps retrying and very quickly blacklists the _entire cluster_ out of the pool
- the main application has trouble making forward progress while running against an entirely blacklisted pool 

We should fix it so the newly-ish added InsufficientConsistencyException is not an exception type that causes blacklisting of the node you're talking to.

**Comment by clockfort** [comment]
fixed by #4039

**Comment by sandorw** [comment]
Nice catch!
