### ISSUE TITLE
SnapshotTransaction#getRows() does a potentially unnecessary sort

### ISSUE THREAD

**Issue by davidscottcohen** [palantir/atlasdb#400]
SnapshotTransaction#getRows() returns a sorted map, regardless of whether the caller actually needs a sorted map.  This is potentially wasteful vs. an unordered map.  

Would be an API break to fix, but worth it if we improve perf in the common case.

**Comment by gsheasby** [comment]
Probably not worth the break until we have solid perf data to back this up.
