### ISSUE TITLE
As a deployer of Atlas I want to know which High Availability failure modes Atlas is and is not affected by so that I can be confident deploying it into my environment

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#406]
This should probably be done with some Jepsen testing

**Comment by jboreiko** [comment]
What more do we want to accomplish with this ticket?  @nemines @joelea

**Comment by harrybiddle** [comment]
We are tracking this elsewhere. Look for component: HA to find HA-related tickets. Closing out.
