### ISSUE TITLE
As a dev I want to delete unnecessary KVS methods so that we have a smaller surface area for bugs

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#407]

**Comment by joelea** [comment]
Blocked on DBKVS move

**Comment by gsheasby** [comment]
@jboreiko which methods are unnecessary?

**Comment by jboreiko** [comment]
I thought this had been recorded somewhere but it appears not.  The general concept here is we need to consider what is essential to the KVS api and what isn't.  With that in mind there are some immediate candidates:
tearDown()
initializeFromFreshInstance()
I would also suspect that getDelegates should be considered for removal or modification.

**Comment by rhero** [comment]
We're not directly prioritizing this, but we'd like to chip away at it as things come up.

**Comment by rhero** [comment]
Going to close this out because we've removed the methods noted above, and this ticket is more of a guideline than an actual issue.
