### ISSUE TITLE
Deal with concurrent C* schema mutations

### ISSUE THREAD

**Issue by jkozlowski** [palantir/atlasdb#4196]
We are experiencing issues with C* gossip getting out of sync when multiple concurrent schema mutations (create keyspace/create table) are occurring on large stacks.

Raising here to track possible improvements in AtlasDB to help alleviate these issues. 

cc @tpetracca @j-baker

**Comment by gmaretic** [comment]
This should be made better if we merge https://github.com/palantir/atlasdb/pull/3754 ?

**Comment by tpetracca** [comment]
Another instance today: PDS-101155

**Comment by clockfort** [comment]
(necro bump to put in my two-penny worth)
we used to have this problem with %excessively_old_cassandra_version% , so we fully serialized all schema mutations with client(atlas) side locks. but that proved quite slow for some use cases

**Comment by jkozlowski** [comment]
I think we fixed this in Cass, so closing
