### ISSUE TITLE
As a development team I would like to easily generate schemas.

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#420]
One proposal that has been partially developed is using java preprocessing with annotations.  The code can be found here: #59 

There currently exists a work around which involves a simple gradle task for running the generator prior to building the project.

**Comment by rhero** [comment]
This would help take care of #23. Not prioritizing now.

**Comment by gsheasby** [comment]
Closing this one, we aren't going to get to it any time soon, and it has no impact for any projects that already use AtlasDB.
