### ISSUE TITLE
Switch to modern Datastax driver before adding too much new CQL code

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#4299]
I see you guys added a bunch of CQL stuff this week.

We probably want to switch to the new 4.2 datastax oss driver now rather than later after you add more classes; there's a bunch of changes around how configuration works, especially if you're currently passing Cluster objects around everywhere. (we are)
(it's stable and back-compat with old cass, the 4.2 version is not like 4.x actual cassandra versioning which is a wild west)

com.datastax.cassandra:cassandra-driver-core 3.7.2 --> com.datastax.oss:java-driver-core 4.2.2

**Comment by jkozlowski** [comment]
We discussed that before and will try to figure out a way forward. Apparently some query builder stuff changed and that's currently used for creating tables (that's why the datastax client was on the classpath). So depending on how that impacts this work we'll try to slot this in.

**Comment by OStevan** [comment]
The version bump is on branch [so/cql-version-bump.](https://github.com/palantir/atlasdb/tree/so/cql-version-bump) Turned out that 4.2.2 didn't have the load balancing policy we actually need so holding off proved useful as it is included in version 4.3.0 on which we based the bump.
