### ISSUE TITLE
Additional serialization required for table creation in C* versions 2.1+ 

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#431]
## BLUF
In C* 2.1+ concurrent table creation can cause apparent data loss, but only much later after the first time a cluster is restarted and re-gossips new CfId around correctly. We need to add additional locking that was previously not necessary.

## Background
Previously, we were able to, with multiple atlas instances talking with multiple C* coordinators, create the same CF to back a createTable(s) call at the same time, and then wait for schema to fully gossip / settle at the end of this operation.

C* <2.1 CfId is a UUID based on KS and CF names.
C* 2.1+ fixes another bug we've run into in the past (that you can occasionally read data written before a drop table after creating a table at a later time with the same name; this is commonly found by things like repeated tests that use and teardown things like "test_table_1", etc) by generating CfId backed by wallclock time.

As a result, C* 2.1+ createTable cannot happen concurrently and does not natively handle the idempotency we require from our KVS.createTable(s) spec; it's possible to get into a state where two nodes both have knowledge of a table, but know it to have differing CfMetadata.cfId because of differing generation wallclock times on different coordinators. Disturbingly, this generates errors that get logged (to the tune of the ConfigurationException attached below), but does allow gossip to settle on a consistent schema version hash despite having different underlying CfId. (imho this is a bug with C*, but we can also solve this ourselves by enhancing our schemas-have-settled-check to look at all CfMetadata on each node as well as the thrift describe_schema_versions() call from each)

Even CQL verb "create table if not exists" ('if not exists' also being something added in 2.1.1+) does not handle concurrent table creation on different coordinators correctly and can get into the same situation that we saw.

In general fixing this class of issues is part of upstream Cassandra epic https://issues.apache.org/jira/browse/CASSANDRA-9424 .

> `
 1329 ERROR [MigrationStage:1] 2016-04-30 17:36:29,485 CassandraDaemon.java:183 - Exception in thread Thread[MigrationStage:1,5,main]
1330 org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 125bfc90-0efa-11e6-bb6f-fdf3c6b1908a; expected 1256f380-0efa-11e6-bb6f-fdf3c6b1908a)
1331 »»»»at org.apache.cassandra.config.CFMetaData.validateCompatility(CFMetaData.java:812) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1332 »»»»at org.apache.cassandra.config.CFMetaData.apply(CFMetaData.java:740) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1333 »»»»at org.apache.cassandra.config.CFMetaData.reload(CFMetaData.java:726) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1334 »»»»at org.apache.cassandra.config.Schema.updateTable(Schema.java:489) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1335 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeTables(LegacySchemaTables.java:527) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1336 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeSchema(LegacySchemaTables.java:424) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1337 »»»»at org.apache.cassandra.schema.LegacySchemaTables.mergeSchema(LegacySchemaTables.java:392) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1338 »»»»at org.apache.cassandra.db.DefinitionsUpdateVerbHandler$1.runMayThrow(DefinitionsUpdateVerbHandler.java:50) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1339 »»»»at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[palantir-cassandra-2.2.1.jar:2.2.1]
1340 »»»»at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
1341 »»»»at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
1342 »»»»at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
1343 »»»»at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
1344 »»»»at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
`
 
## Fix

There are numerous ways to fix this, they're all not great for many reasons.

- Some people serialize all DDL through a single static node (the other large now-London product that leverages C* opts to do this) but this is bad because it's relatively against the concepts of HA and having a live-updatable node list and having clients with slightly different views of the Cassandra cluster.

- We could make a table and use C* compare and swap (CAS) to provide a DB lock around table creation, but this unfortunately requires an already-done table creation

- We could use our own Lock service
-- But this is not good for our abstraction / code smell
-- And we currently package it as LockAndTimestampService which gives you a circular dependency because TimestampService has a KVS dependency so it can storeUpperLimit

**Comment by clockfort** [comment]
I'm going to implement option #2 with a table that I create in the same way we create the internal _metadata table in CassClientPool

**Comment by clockfort** [comment]
I think the best way of doing this CAS operation is to do a CAS of (static global lock name for DDL operations, nodeId + timeoutThatIWillExpireBy) and everyone waiting on the lock can wait timeoutTthatIWillExpireBy and after it passes do a CAS of (differentNodeId, timeoutThatIWillExpireBy) with an expected start value of (nodeId + timeoutThatIWillExpireBy)

**Comment by jboreiko** [comment]
I do not believe we should allow other nodes to overtake a timed out Atlas.  I can create a path to silent corruption if this is the case.  In brief the path to corruption is as follows:

Node1 takes ownership of the lock
Node1 GC pauses / hangs
Node2 polls until deciding Node1 has timed out
Node2 overtakes Node1s lock
Node1 unpauses
Node1 and Node2 both run createTable causing corruption
Node1 fails (eg. main memory failure) prior to checking lock
Node2 completes successfully verifying that it still holds the lock

Cluster is now operation (sans 1 node which does not report this as a possible error) with pending corruption that will become apparent after C* restart.

Even in the case that Node1 is able to run the check and catch the error, we are reliant on users to notice the failure of Node1 and take appropriate action.

**Comment by jboreiko** [comment]
A similar proposal is to have the global lock be non-transferable, this of course could result in a failure if (using the example above) Node1 were to fail anytime before releasing the lock.  PR forth coming.

**Comment by tpetracca** [comment]
"Some people serialize all DDL through a single static node (the other large now-London product that leverages C* opts to do this) but this is bad because it's relatively against the concepts of HA and having a live-updatable node list and having clients with slightly different views of the Cassandra cluster."

Could we do this and make it HA by determining the single node that gets to execute DDL commands via leadership election?

**Comment by gbrova** [comment]
I don't think so - a leader L1 could become elected and then become
unresponsive. To be HA, a new leader L2 would have to be elected, but L1
might later "wake up" and both L1 and L2 could execute the same DDL
commands. (In consensus algorithms we just care about some values being the
same, but here we also want to execute at most once).
