### ISSUE TITLE
leading row component schema error should be ignorable

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#432]
let people write something into their schema that silences the error 'your leading row component is var_foo, you know this is going to have screwy partitioning based on length, right?'

I want people to see the error when they dev new schemas; the act of ignoring it should be something like adding ".thisTableIsTinyOrForSomeOtherReasonIDontCareAboutHotspotting()" on their schema

see internal QA-95016 et al.

**Comment by clockfort** [comment]
@nemines wrote the original.Maybe if she has time she can get to this? Else someone will eventually get to doing this.

**Comment by nemines** [comment]
I will get to it after my queue of assigned bugs, probably next week. If that's fine, you're welcome to assign it to me.

**Comment by joelea** [comment]
Fixed in #491
