### ISSUE TITLE
CassandraKeyValueServiceImpl executor thread pool never removes idle threads

### ISSUE THREAD

**Issue by OStevan** [palantir/atlasdb#4351]
Even though the current implementation sets the keep alive timer for removing idle threads to 1 minute on the `executor` it also sets the core pool size and max pool size to the same value. As a result threads are never removed from the pool.

If we in fact want the pool to remove some threads one possible solution is to have a config option which will specify the fraction of threads from the pool which can be removed. The default value for this would be 0 so that users have to explicitly set it if they think they need such feature.

**Comment by jkozlowski** [comment]
I think the tradeoff here is how quickly the threads are started when you need the capacity. We can probably get metrics on the utilization of those threadpools and come up with a good initial value.
