### ISSUE TITLE
PartitionedKeyValueServiceAvailabilityTest > testCannotModifyValuesAfterWrite flaky

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#449]

**Comment by jboreiko** [comment]
Can we get a link to a flaking build or two?  I haven't noticed the flake.

**Comment by jboreiko** [comment]
Found an answer to my own question: https://circleci.com/gh/palantir/atlasdb/408

**Comment by gbrova** [comment]
More failures: https://circleci.com/gh/palantir/atlasdb/507 and https://circleci.com/gh/palantir/atlasdb/512
