### ISSUE TITLE
Document how to write an AtlasDB healthcheck

### ISSUE THREAD

**Issue by bavardage** [palantir/atlasdb#459]
I get worried after seeing chatter around failed paxos things in my logs. Would be good to have the ability to poke an endpoint and find out if everything in the cluster is now in a good state.

from hipchat:

```

Ben Duffield [01:18] 
is there a way to see whether an atlas cluster is happy?

[01:18] 
where happy is pretty vague

Tom Petracca [01:18] 
lol

Ben Duffield [01:18] 
but I saw some chatter in my logs about leaders and learners

[01:18] 
can I see whether it’s all resolved and ahppy now

[01:18] 
like I want it to tell me “yop, I have blah nodes and blah is the leader"

[01:18] 
“also yeah everything is cool"

Maciej Albin [01:25] 
like a healthcheck?

[01:26] 
if there is would be good to encourage all products to call it as part of their /heathcheck (edited)

Ben Duffield [01:29] 
yeah

[01:29] 
right

new messages
Tom Petracca [02:51] 
I don’t see why we couldn’t do that

[02:52] 
err

[02:52] 
with caveat

[02:52] 
file an issue @bduffield

Ben Duffield [02:52] 
whoah

[02:52] 
an issue
```

**Comment by j-baker** [comment]
Check out the app we both contributed to's healthchecks (if someone could clarify whether we can use app names externally that'd be good). They're very basic, but basically test that Atlas is responsive, and from personal experience are pretty good at working out whether Atlas is in a bad state. I copied them from @tjwilson90.

**Comment by ash211** [comment]
@j-baker is the healthcheck you mention something that should be baked into the Atlas client connection as a heartbeat?  It'd be helpful to have this embedded in the Atlas client side for wider use so this technique doesn't need to be copied to each service.

**Comment by gsheasby** [comment]
We agree, we'd like to add a healthcheck to the transaction manager to cover this.

**Comment by gsheasby** [comment]
Various internal products have rolled their own solution; we intend to add a small piece of documentation to establish a "good" healthcheck methodology.

**Comment by tboam** [comment]
`TransactionManager` exposes a method for getting the health of the underlying store.  Timelock as a separate service will report its own health status.

Is there anything else required for products to report their health?

**Comment by gsheasby** [comment]
Nope, this was superseded by #1832.
