### ISSUE TITLE
PersistentTimestampService Race Condition 

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#462]
I was fixing something else and came across
```
        if (isAllocationTaskSubmitted.compareAndSet(false, true) && isAllocationRequired(lastReturnedTimestamp.get(), upperLimitToHandOutInclusive.get())) {
            final Exception createdException = new Exception("allocation task called from here");
            executor.submit(new Runnable() {
                @Override
                public void run() {
                    try {
                        if (allocationFailure instanceof MultipleRunningTimestampServiceError) {
                            // We cannot allocate timestamps anymore because another server is running.
                            return;
                        }
                        allocateMoreTimestamps();
                        lastAllocatedTime = clock.getTimeMillis();
                        allocationFailure = null;
                    } catch (Throwable e) { // (authorized)
                        createdException.initCause(e);
                        if (allocationFailure != null
                                && e.getClass().equals(allocationFailure.getClass())) {
                            // QA-75825: don't keep logging error if we keep failing to allocate.
                            log.info("Throwable while allocating timestamps.", createdException);
                        } else {
                            log.error("Throwable while allocating timestamps.", createdException);
                        }
                        allocationFailure = e;
                    } finally {
                        isAllocationTaskSubmitted.set(false);
                    }
                }
            });
        }
```

Maybe there are secondary guarantees that protect us here, but it seems that isAllocationTaskSubmitted atomic boolean can be set to true and never unset if (1) the CAS succeeds but the isAllocationRequired() check fails or (2) something catastrophic happens to with your executor before the finally clause is called.  I think probably case (2) is safe depending on Executor documentation.  The other case (1) was introduced more recently in https://github.com/palantir/atlasdb/pull/354.

I'll fix this tomorrow, but wanted to give SA in case we have some procedure for handling/supporting regressions.

**Comment by joelea** [comment]
Add something to the release notes about it and we'll figure out how to message about it.

1) could happen, the finally block won't execute if the thread is cancelled or interrupted, but I don't see anywhere that would happen
2) is a bug - I think just remove the 2nd check fixes it in the appropriate way.

**Comment by gbrova** [comment]
The intent of the `isAllocationRequired` check was to avoid test flakiness: occasionally a single call to getFreshTimestamp could trigger multiple calls to submitAllocationTask(), leading to unexpectedInvocation errors ([circle example](https://circleci.com/gh/palantir/atlasdb/90)). 

I think swapping the order and doing the isAllocationRequired check before the CAS would also fix the concurrency bug. Or, since we don't really care if there are multiple calls to submitAllocationTask, we could just change the tests to accept that (and not throw unexpectedInvocation). 

Also @joelea I'm adding another +1 to possibly refactoring this class.

**Comment by joelea** [comment]
I'd already added my own potential +1 as well. Flipping the order would also work.

My preference is to refactor the whole shebang away and do something like the below, where we just rely on java locking to give us what we need.

```
private void allocateMoreTimestamps() {
    executor.submit(() -> synchronouslyAllocateMoreTimestamps();
}

private synchronized void synchronouslyAllocateMoreTimestamps() {
    if(shouldAllocateMoreTimestamps()) {
        // actually do the work
    }
}
```
