### ISSUE TITLE
As a maintainer of Atlas, I want to be notified when Cassandra is at risk of OOMing (was: It should never be possible for AtlasDB to cause Cassandra to OOM)

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#465]
**BLUF: Discussion below about what we can do to stop Cassandra OOMing. Briefly, all we can do is notify (via logs or alerts) when things start to look memory-taxing. Actions required are below**
1. Have a parameter (configurable at the application level) saying how many values (row batch size \* column batch size) are too many to request. If this value is breached, we log at WARN.
2. Notify (e.g. via more log messages, or better still, a nagios alert) when values successfully returned are dangerously high.
3. Limit the size of cells (values we put) to 5MB

**Original discussion follows. Ticket was titled "It should never be possible for AtlasDB to cause Cassandra to OOM"**

Sorry I didn't make this issue earlier, documenting it here for tracking. One of our deployments were seeing an issue where an application made some unwise choices with their data (tried to load it all into memory in one go).

This caused their single-node Cassandra to OOM, which took down their entire stack.

The symptom was that a Cassandra Thrift write buffer hit >2GB and ByteArrayOutputStream throws an OutOfMemoryError if this happens. Cassandra handles an OutOfMemoryError by shutting down.

When we recommend that people deploy many Atlas applications using the same Cassandra cluster, this seems like a recipe for disaster.

The interesting thing in this case is that the table being loaded wasn't huge (500MB), and beyond this in the programmer's model doesn't have much data in (1000s of rows, talking to the relevant FDEs (their guess was 3000)), but had many more rows (presumably due to frequent updates). There were perhaps 5 columns and 6 million rows in the table in Cassandra (so perhaps every row had up to 400 old versions on average?). This would not surprise me, one of our other applications was resyncing all of its resources every 5 minutes.

To me this seems to be a joint education problem (don't load your entire database, don't write to columns that haven't changed) as well as an Atlas bug (under no circumstances should Atlas make queries to Cassandra that might take it down entirely).

**Comment by gsheasby** [comment]
@j-baker could this be related to the history/sweep issues?

**Comment by gbrova** [comment]
Unfortunately, we're somewhat restricted by cassandra. In specific cases we can find ways to avoid OOMing cassandra, but in the general sense queries need to be tested before they're deployed to avoid this.

Closing in preference to a more specific ticket, which we're handling.

**Comment by schlosna** [comment]
What is the new ticket? Are we adding information to help AtlasDB clients know when they have a schema that is leading to inefficient reads/writes, as well as potentially OOMing the client, not just C*. The ProfilingKVS can log some aspects of this, though needs to be hooked up, and probably some love around info and warning thresholds for logging expensive calls.

**Comment by j-baker** [comment]
The exact case I was thinking of was one where AtlasDB decided to load 3000 wide rows in one batch, leading to 6 million values being requested from the backing store (over 2GB). At least, that's what we think was happening - it was certainly a thrift buffer that was ooming everything.

I remain unconvinced that the application developer was doing something silly with this query - after all they only had 3000 rows in the database.

Whilst I'm sure that in the general case we can't be sure that AtlasDB won't make a request that'll accidentally break Cassandra, we can do better here than 'wontfix', especially since diagnosing this took three of us a full evening involving changing cqlsh timeouts and forking applications.

This would have been diagnosed in seconds if there had been sufficiently loud noise pre explosion (when the stack was merely quietly on fire) that an operation was returning a very large number of rows and columns or was otherwise taking a long time for queries?

Maybe the title should be changed to reflect this? 'It should not be possible to be blindsided by Cassandra ooming'? As well as 'AtlasDB should have some kind of sane default limit on the number of things that it requests from Cassandra in one go'.

I don't think that this should be closed, though.
James

On Tue, 16 Aug 2016 at 07:30, David Schlosnagle <notifications@github.com<mailto:notifications@github.com>> wrote:

What is the new ticket? Are we adding information to help AtlasDB clients know when they have a schema that is leading to inefficient reads/writes, as well as potentially OOMing the client, not just C*. The ProfilingKVS can log some aspects of this, though needs to be hooked up, and probably some love around info and warning thresholds for logging expensive calls.

**Comment by tpetracca** [comment]
I am in agreement with @j-baker.  I actually believe that the major blocker from cassandra really being the ideal choice of KVS when using atlasdb is precisely the fact that it can get cassandra into a state that then regularly causes OOMs in cassandra's heap.

I have a lot of thoughts and information around this.  Starting a thread internally to discuss.

**Comment by rhero** [comment]
// re-opening to address discussion

@j-baker -- how would you go about preventing Cassandra from OOMing generally? I was under the impression that Cassandra doesn't let you know the size of the thing you're trying to load into memory without loading it into memory. So then our approach would have to be, "try not to request things that we think are likely to be large" and/or "let people know we're barely requesting large things successfully". 

So concretely:

1. Resolving known issues where we read wide rows in a single batch, either through configurable batches or using Tanya's dynamic column paging work. Are there other known areas where we do this besides Sweep?
2. Log warnings when memory usage (payload size * # of reads) is very large as a proportion of heap, or even more intelligently, the rate at which memory usage grows over time.

Does that sound off or do you have other thoughts?

I agree that this is a real issue that is source of a bit of criticism against using Cassandra, and making AtlasDB clients play nice with Cassandra is a priority for us.

**Comment by gsheasby** [comment]
Caught up with @j-baker on this. While we can never completely prevent OOMs (values could be large enough that you can put 1 but can't get 2), there are the following concrete things that we can do to help make it possible to catch the fire before the big explosion:

1. Have a parameter (configurable at the application level) saying how many values (row batch size * column batch size) are too many to request. If this value is breached, we log at WARN. 
2. Notify (e.g. via more log messages, or better still, a nagios alert) when values successfully returned are dangerously high.

Note that both of these will catch issues at runtime, so applications using AtlasDB would not catch the issue before release (unless their testing is **really** good). Hard to say how we'd make it so that application developers never write the code that puts lots of large values in the first place.

**Comment by tpetracca** [comment]
I think we also need to limit the size of cells.  No one should every be able to create a cell greater than 5mb, simply because you should never have a row greater than 5mb.

**Comment by tpetracca** [comment]
the stream store exists for a reason

**Comment by gsheasby** [comment]
Sounds good to me - I'll add a BLUF to the top post.

**Comment by hsaraogi** [comment]
Break the ticket into specific checks and see which checks already exist.

**Comment by gsheasby** [comment]
The third point is covered by #1184.

**Comment by gsheasby** [comment]
The three parts in the BLUF above will be tracked separately by #1216, #1217, and #1184
