### ISSUE TITLE
Document tests set up

### ISSUE THREAD

**Issue by nemines** [palantir/atlasdb#468]
It is not immediate to set up docker to be able to run the test if you're not familiar with docker.
it might be useful to have section in the wiki page explaining what's needed and how to get it linking to proper setup steps.

**Comment by jboreiko** [comment]
I would like to see this in github.  It could easily be added to the Getting Started guide under a running all tests locally section.  Including link direct to inline editing on github - https://github.com/palantir/atlasdb/blob/develop/docs/source/overview/getting_started.rst

**Comment by nemines** [comment]
Yes, agreed. That's what I meant and why I opened the issue here. The wiki word is out of habit :)
