### ISSUE TITLE
RocksDB KVS after a few weeks of uptime goes crazy and mallocs 10GB/s of young gen objects

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#473]
![qf2sgnv](https://cloud.githubusercontent.com/assets/57031/15348299/66be3dde-1c7e-11e6-816d-b5bed74898ed.png)

![6kdo7mn](https://cloud.githubusercontent.com/assets/57031/15348301/697a62b4-1c7e-11e6-804d-ea67822ff392.png)

This behavior constantly happens for about ~30-50m after starting up our (idle) application, and takes a lot of CPU time / stop the world time to clean out the crazy amount of allocated objects.

Asked around and @twilson-palantir  has seen the same issue:
"same problem {internal product} had with rocks. jfr showed spawning and killing a thread every ~30 microseconds for 2 - 10 minutes immediately after loading the rocks native libs, then the problem just magically fixes itself"

I plan on debugging further by compiling the rocksdb stuff with debug symbols, popping the binaries into the rocks jar, and using `perf` or similar debugger to see who is calling into us this often on the other side of the JNI bridge.

**Comment by joelea** [comment]
We're unlikely to fix anything Rocks related. Going to close this.
