### ISSUE TITLE
AtlasDB Console improvements

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#476]
There are many known short comings of AtlasDB Console at the moment.  This ticket hopes to document a set of first steps to get Console on better footing in both dev and usability measures.  

@rjullman to help complete.

**Comment by rjullman** [comment]
The biggest blocker to actually improving console is eliminating all the groovy backing code (imo it is fine to use groovy as our interpreter).  This is tied into a slightly more general issue about how we serialize objects (currently we serialize everything internally and externally with json -- the former being bad and the latter being okay).  This is part of an even more general problem, which is how we talk to atlas.  Maybe eventually we want a SQL-like language? Maybe we want to just expose the TransactionManager api, maybe we ant a restricted console api (kind of like what we already have).  This is not meant to sound apocalyptic (I think of these fixes are doable in small manageable chunks), but this is a hard issue to approach through small tickets without initially having a comprehensive discussion (perhaps that discussion is this epic ticket).

**Comment by jboreiko** [comment]
This requires further discussion before it can move forward.  When we choose to begin work on this we should further divide this into sub-issues that move us toward the end goal of a highly functional/useful console for AtlasDB.

**Comment by gsheasby** [comment]
Closing as all issues are done or "wontfix", and making further improvements to console is not high on our list of priorities.
