### ISSUE TITLE
Enormous log line for current ring view

### ISSUE THREAD

**Issue by ash211** [palantir/atlasdb#501]
I'm seeing the below stacktrace in one of my Atlas-backed services after bouncing all 3 Cassandra services in my cluster (but not bouncing the Atlas-backed service).

Can we make this log line higher signal?  I don't think there's much to be gained by listing out all these LightweightOPPTokens.

`
WARN  [2016-05-25 08:35:51,148] com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool: Perf / cluster stability issue. Token aware query routing has failed because there are no known live hosts that
 claim ownership of the given range. Falling back to choosing a random live node. For debugging, our current ring view is: {(-∞‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPTo
ken@4a35a1f1]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6ab61d2b‥com.palantir.atlasdb.keyvalue.cassandra.Ca
ssandraClientPool$LightweightOPPToken@20dbb410]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@1246bba6‥com.pala
ntir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@751baa36]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$Lig
htweightOPPToken@2f1ebefb‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5298f43c]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue
.cassandra.CassandraClientPool$LightweightOPPToken@7524fe42‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5dc6b0ca]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:916
0], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@7f534ef‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@12d90939]=[/10.0.27.149:9160, /
10.0.26.24:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@40dd23ce‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPTok
en@28f58bff]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6899042‥com.palantir.atlasdb.keyvalue.cassandra.Cass
andraClientPool$LightweightOPPToken@5c43c16b]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@75295a7e‥com.palant
ir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@71079d57]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$Light
weightOPPToken@3b4618b5‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@794cce2f]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.c
assandra.CassandraClientPool$LightweightOPPToken@460991d2‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@ba94161]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160],
 (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@216311‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@1f03f88c]=[/10.0.27.247:9160, /10.0
.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@150e6dbf‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5
46d8436]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5fdf4c41‥com.palantir.atlasdb.keyvalue.cassandra.Cassand
raClientPool$LightweightOPPToken@5f9818ae]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@399df577‥com.palantir.
atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@1699a46]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$Lightweig
htOPPToken@2471636e‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@3b334226]=[/10.0.27.149:9160, /10.0.26.24:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassa
ndra.CassandraClientPool$LightweightOPPToken@6d532e7a‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@20a5223c]=[/10.0.27.149:9160, /10.0.26.24:9160, /10.0.27.247:9160], (c
om.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@fe04f55‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@2ee30efd]=[/10.0.27.149:9160, /10.0.2
6.24:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5ab7c5a5‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@538
aa80d]=[/10.0.27.149:9160, /10.0.26.24:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@5e9ddfce‥com.palantir.atlasdb.keyvalue.cassandra.Cassandra
ClientPool$LightweightOPPToken@68bfb606]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@c41cc59‥com.palantir.atl
asdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@a8dc71c]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightO
PPToken@3ade0a2c‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@2f4484f7]=[/10.0.27.247:9160, /10.0.27.149:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandr
a.CassandraClientPool$LightweightOPPToken@2d65b642‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@49b431d5]=[/10.0.27.149:9160, /10.0.26.24:9160, /10.0.27.247:9160], (com.
palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@3f1cda5‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@8199210]=[/10.0.26.24:9160, /10.0.27.149
:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@84ef2f7‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@601c50b2
]=[/10.0.27.149:9160, /10.0.27.247:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6d0d25f1‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClien
tPool$LightweightOPPToken@29c0a352]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@566625d7‥com.palantir.atlasdb
.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@547d6669]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPT
oken@50dbe3ba‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@7cad10c0]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.C
assandraClientPool$LightweightOPPToken@1b02ca1f‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@24f3b938]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.pal
antir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@2b3a482f‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@3f057698]=[/10.0.26.24:9160, /10.0.27.149:
9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@32da1155‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@b59444f]
=[/10.0.27.149:9160, /10.0.27.247:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@72db0e3b‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClient
Pool$LightweightOPPToken@667e174e]=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@44ce26d‥com.palantir.atlasdb.k
eyvalue.cassandra.CassandraClientPool$LightweightOPPToken@45f6b597]=[/10.0.26.24:9160, /10.0.27.149:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPTok
en@6f76c1c4‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@79a46f03]=[/10.0.27.149:9160, /10.0.26.24:9160, /10.0.27.247:9160], (com.palantir.atlasdb.keyvalue.cassandra.Cas
sandraClientPool$LightweightOPPToken@1a18b5d0‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6ab2f109]=[/10.0.26.24:9160, /10.0.27.247:9160, /10.0.27.149:9160], (com.palan
tir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@3313657a‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6995d86c]=[/10.0.26.24:9160, /10.0.27.247:91
60, /10.0.27.149:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@367c46bb‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@4bbbd3c4]=
[/10.0.27.247:9160, /10.0.27.149:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@63ab577c‥com.palantir.atlasdb.keyvalue.cassandra.CassandraClientP
ool$LightweightOPPToken@24bab5dd]=[/10.0.27.149:9160, /10.0.27.247:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@70a7666f‥com.palantir.atlasdb.k
eyvalue.cassandra.CassandraClientPool$LightweightOPPToken@6517be4c]=[/10.0.27.247:9160, /10.0.27.149:9160, /10.0.26.24:9160], (com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPTok ...
<SNIP>
(com.palantir.atlasdb.keyvalue.cassandra.CassandraClientPool$LightweightOPPToken@60451ae5‥+∞)=[/10.0.27.247:9160, /10.0.26.24:9160, /10.0.27.149:9160]} and our current host blacklist is {REDACTED_HOSTNAME_2/10.0.26.24:9160=1464165257427, REDACTED_HOSTNAME_0/10.0.27.149:9160=1464165289465, REDACTED_HOSTNAME_1/10.0.27.247:9160=1464165280434}
`

**Comment by clockfort** [comment]
Fixed already in #498 , I'm 12 hours ahead of you :-)

There hasn't been a release in the last 12 hours though, so you'll have to wait a bit longer if you want to upgrade away from it.

The fix should both make the case where the logging occurs more rare and make the log lines themselves more compact.

**Comment by ash211** [comment]
Great to hear!  I'll put upgrading to the next version on the checklist for my app.

Do you guys have an anticipated release date, or a release schedule published that you're aiming for?

**Comment by clockfort** [comment]
I think @joelea is the man with the plan

**Comment by joelea** [comment]
Hoping for a release by the end of the week, might be early next week. We'll send out an email to the internal atlas announce list when it's ready and I'm pretty sure you can subscribe to get notified of releases on github.
