### ISSUE TITLE
Publish docs only on release

### ISSUE THREAD

**Issue by gbrova** [palantir/atlasdb#509]
Now we are publishing gh-docs on every merge to develop. This means the latest published docs (and release notes) are for a as-yet-unreleased version.  For example, the latest [release notes](http://palantir.github.io/atlasdb/html/release_notes/release-notes.html) right now refer to Atlas 0.6.0, which is not published. 

Instead, we could publish docs the same time we do an actual release.

**Comment by rjullman** [comment]
I see what you are saying, but the counter argument is that (a) that documentation is useful for people tracking develop and (b) that it allows for other documentation changes easily.  If we change this we some simple way to kick the docs to rebuild (that isn't a release).

**Comment by joelea** [comment]
Closed out in the PR.
