### ISSUE TITLE
RocksDB tmp dir isn't cleared after a kill -9

### ISSUE THREAD

**Issue by ash211** [palantir/atlasdb#523]
There's an issue with the RocksDB native libraries temp dir:

Pretend I have a service called MyService that uses Atlas with a RocksDB backend so it stores its data in a local directory

Repro steps:
- start MyService with `nativeLibTmpDir` set
 - rocks native library loader sticks a `.so` file in the tmp dir
- kill -9 MyService
 - the file is still there in the tmp dir since the JVM's finalizer didn't get a chance to kill the temp file, which is registered for delete on shutdown
- start MyService again
 - rocksdb attempts to create the file in the tmp dir again, but now there's a conflict :(  The exception comes from https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/NativeLibraryLoader.java#L91

The exception mentions that the file `librocksdbjni-linux64.so` couldn't be created.

**Comment by joelea** [comment]
Unfortunately, I don't think this is going to get fixed anytime soon. My knowledge of the rocksdb side of things is pretty shabby, but there's nothing we could do atlas side at the point of being kill -9'ed.

Rocks could likely do something where they store the pid in the lock file and then a new process would have the option of clearing out the lock. We could also do something crazy in atlas where we use that locking process ourselves and then clear out the rocks locks. However, given that we're not going to be supporting rocks outside of development in the future, this is not a high priority.

I'm assuming you can delete the tmp file by hand and it will be happy again?

**Comment by joelea** [comment]
Closing this as we're unlikely to fix RocksDB, as we're removing it as a supported KVS.
