### ISSUE TITLE
Deadlock on the _transactions table

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#529]
Internal product has seen instances of deadlocks on the _transactions table that have been attributed to the connection pools used to talk to the underlying datastore - in these cases this was Postgres / Oracle being reached through DBKVS.

There is an internal page 'Non-Root Caused Issues Seen in the Field' tracking this issue.

**Comment by rhero** [comment]
Closing this out since we haven't seen this recently. One workaround has been to turn off Sweep. We'll follow this as we hope to re-enable sweep soon.
