### ISSUE TITLE
Allow a trustStore to be attached to the atlasdb-cli

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#537]
If you're running Cassandra over TLS, you need to modify the launcher script to set a global truststore. Ideally there would be a command line option.

**Comment by joelea** [comment]
Thanks @leeavital, this sounds super annoying. We'll look at this as part of the broader console improvements epic when we start doing some work there (I've added it to the console improvements epic)

**Comment by tpetracca** [comment]
This is covered by https://github.com/palantir/atlasdb/pull/638

**Comment by gsheasby** [comment]
This will be fixed once #638 finally merges.

**Comment by jboreiko** [comment]
#638 has merged.
