### ISSUE TITLE
RocksDB block level corruption

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#543]
12:47:13.041 [main] INFO  com.palantir.common.base.Throwables - Rewrapping throwable java.lang.RuntimeException: org.rocksdb.RocksDBException: Corruption: Snappy not supported or corrupted Snappy compressed block contents with newMessage org.rocksdb.RocksDBException: Corruption: Snappy not supported or corrupted Snappy compressed block contents
org.rocksdb.RocksDBException: Corruption: Snappy not supported or corrupted Snappy compressed block contents```

Was seen during the sweeping of an internal product.  It appears consistently when sweeping a particular portion of the schema.  It was not mitigated by removing the underlying data store - this is perplexing and may indicate that it is a deterministic failure and not the result of a race condition.

**Comment by Alexis-D** [comment]
A bit more context here:

* It happens when sweeping the whole schema, `./bin/atlasdb sweep -a`
* When blowing up the db and restarting Compass everything works, but after a few (stop compass/sweep/restart compass) cycles the DB becomes corrupted.

`0.4.0-1-g0e5fb8b`

**Comment by joelea** [comment]
We're unlikely to be fixing any rocks issues as we are removing rocks DB as a supported KVS. Closing this.
