### ISSUE TITLE
Migration timestamps can break putUnlessExists behaviour

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#557]
Dupe of internal 92457

KVS Migration currently reads in data at [their existing timestamps] and writes it out in the new place at a constant [MIGRATION_TIMESTAMP].

This is somewhat beneficial, as it means we don't need to migrate the timestamp table in the case of a full kvs migration, and additionally allows one to 'clear' a timestamp table that may have grown large in size.

This is somewhat harmful, as it breaks putUnlessExist behavior, which relies on the TS being 0. Previously this was only on the (non kvs migrated) timestamp table so it didn't happen to matter, but other tables can now use putUnlessExist. It also breaks sweep priority table, which uses TS=0 writes to perform upserts.

**Comment by rhero** [comment]
We're going to try and take a look at this relatively soon.

**Comment by hsaraogi** [comment]
Are customers using this?
We can disable putUnlessExists on any non-system tables.

**Comment by gmaretic** [comment]
Atomic tables (which use PUE) should not be migrated anyway, and KVS migration CLI uses transactional reads so doesn't see data written with a timestamp of 0
