### ISSUE TITLE
AtlasDB is really bad at initialisation tasks, because it piggybacks on the host's Jersey implementation

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#565]
So, when you use Atlas with Dropwizard in HA mode, it registers endpoints on the Dropwizard application (`environment.jersey()::register`).

These endpoints are not live until the end of the run method.

This makes initialisation tasks (generating crypto keys on first launch, reindexing ES if necessary, storing initial nodes) difficult, because there's no good place to run them - Atlas explodes if you try to do anything with it before the end of the method. The procedure we've used is to use a Dagger `Lazy` and run the creation code on first transaction - we even have a `TransactionManager` implementation which performs initialisation tasks, but this is messy code (for testing and otherwise) because you have suppliers everywhere, and you have to remember to call the right suppliers before doing the right things - it's just generally pretty jank.

In terms of solutions, the ones that seem reasonable to me are: Atlas could either move away from piggybacking (which would be good for other reasons, I know that in another app I wrote we discovered late on that you couldn't call a bucket 'paxos), or drop support for embedded mode HA.

**Comment by joelea** [comment]
Yep, this initialisation method sucks - #331 is the first step in fixing this kind of thing.

**Comment by jboreiko** [comment]
@joelea will isolate this issue to this ticket (as an epic) for tracking.

**Comment by joelea** [comment]
This will be fixed by #645
