### ISSUE TITLE
Generated code for table definition with noColumns() is confusing

### ISSUE THREAD

**Issue by divath** [palantir/atlasdb#570]
```
        schema.addTableDefinition("table", new TableDefinition() {
            {
                rowName();
                rowComponent("key", ValueType.VAR_STRING);
                noColumns();
            }
        });
```

Generates methods like:

```
    public void putExistsUnlessExists(TableRow row, Long value) {
        putUnlessExists(ImmutableMultimap.of(row, Exists.of(value)));
    }
```

1. I think it would be more readable if putUnlessExists were renamed to putIfAbsent and Exists class could be renamed to e.g. Dummy. 
2. Also it is weird that you can set a value for that extra fake 'exists' column. Shouldn't it be a singleton?
3. Shouldn't noColumns() generates something more resembling a Set interface instead of allowing user to set some hacky column?

**Comment by joelea** [comment]
Where is the Exists class coming from for `Exists.of(value)`? I can't find it in the codebase...

**Comment by divath** [comment]
It is generated nested class and lives inside generated table code. I think it is generated when you use noColumns() option.
