### ISSUE TITLE
Bug: Concept sets: Exporting several concept sets can result in no action

### ISSUE THREAD

**Issue by joeflack4** [palantir/atlasdb#5832]
## Description
I was exporting concept sets from this instance: https://atlas.ohdsi.org/#/conceptsets

There is a concept set called "Pregnancy conditions, procedures, and observations" w/ ID 41, which, when I click it from the "List" tab, shows me a warning/error message saying that there are no concepts.

However, when I try to export this set from the "Export" tab, I do not get an error. Nothing happens.

This same result will occur if I select any number of concept sets, where the problematic concept set is included in the list.

## Expected behavior
When exporting (a) a problematic concept set (e.g. has no concepts), or (b) a number of concept sets including problematic concept sets, an error message should display identifying any problematic concept sets.

## Actual behavior
When clicking "Export Concept Sets", the "processing" spinner appears, and then goes way after a short time, and nothing else happens.

**Comment by jeremyk-91** [comment]
Hey @joeflack4,

I think unfortunately that's a different product that's also named Atlas (metaphors for holding up the world are pretty popular it seems) - you're probably looking for https://github.com/OHDSI/Atlas?

**Comment by joeflack4** [comment]
Yeah that's embarrassing. You're right. I thought this was actually a Palantir product. I'll go ahead and re-post over there!
