### ISSUE TITLE
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'multiget_multislice'

### ISSUE THREAD

**Issue by mousavi007** [palantir/atlasdb#5891]
when run atlasdb for first time it give me 
`Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'multiget_multislice'`
when cassanadra send result of query multiget_multislice, TServiceClient give this error.
i guess when cassandra send null to atlas db in TServiceClient .receiveBase(TBase result, String methodName) method, make TMessage.type = 3 and make exception how to solve this.
I want use atlasdb for educational purpose and this is my code to run sample server
`public class AtlasDbServiceServer extends Application<MyAppConfiguration> {

    public static void main(String[] args) throws Exception {
        new AtlasDbServiceServer().run(args);
    }

    @Override
    public void initialize(Bootstrap<MyAppConfiguration> bootstrap) {
        super.initialize(bootstrap);
        bootstrap.setMetricRegistry(MetricRegistries.createWithHdrHistogramReservoirs());
    }

    @Override
    public void run(MyAppConfiguration config, final Environment environment) throws Exception {
        //AtlasDbMetrics.setMetricRegistry(environment.metrics());
        AtlasDbConfig configs = AtlasDbConfigs.load(new File("atlasdb.yml"), AtlasDbConfig.class);

        Schema schema = TodoSchema.getSchema();
        schema.renderTables(new File("src/main/java"));
        /*TransactionManager transactionManager = TransactionManagers.createInMemory(TodoSchema.getSchema());
        ImmutableTransactionManagers.UserAgentBuildStage userAgent = TransactionManagers.builder().config(configs);*/

        TransactionManager transactionManager2 = ((ImmutableTransactionManagers.Builder) ImmutableTransactionManagers
                .builder())
                .config(configs)
                .addSchemas(schema)
                .userAgent(UserAgents.parse("test/server"))
                .globalMetricsRegistry(MetricRegistries.createWithHdrHistogramReservoirs())
                .globalTaggedMetricRegistry(new DefaultTaggedMetricRegistry())
                .build().serializable();

        TableMetadataCache cache = new TableMetadataCache(transactionManager2.getKeyValueService());

        environment.jersey().register(new AtlasDbServiceImpl(transactionManager2.getKeyValueService(), transactionManager2, cache));
        environment.getObjectMapper().registerModule(new AtlasJacksonModule(cache).createModule());
    }
}`

this is yml file:
`atlasdb:
  keyValueService:
    type: cassandra
    keyspace: atlasdb
    servers:
      - localhost:9160
    poolSize: 20
    credentials:
      username: ????
      password: ????
    ssl: false
    replicationFactor: 1
    mutationBatchCount: 10000
    mutationBatchSizeBytes: 10000000
    fetchBatchCount: 1000
    autoRefreshNodes: false
    ignorePartitionerChecks: false
    socketTimeoutMillis: 10000

  leader:
    # This should be at least half the number of nodes in your cluster
    quorumSize: 1
    learnerLogDir: var/data/paxosLogs
    acceptorLogDir: var/data/paxosLogs
    # This should be different for every node. If ssl is not enabled, then the host must be specified as http
    localServer: http://localhost:3828
    # This should be the same for every node
    leaders:
      - http://localhost:3828`
atlasdb version is 0.526.0

**Comment by gmaretic** [comment]
Hi @mousavi007 ,

Some of our features in the last few years required extensions to the thrift API, which is only supported by https://github.com/palantir/cassandra . If you really want to use Cassandra, you should install binaries from that repository. 

Since this is for educational purposes, I would suggest you use in-memory key value service (type: memory). If you need persistence, it's likely that postgres is easier to set up than Cassandra
