### ISSUE TITLE
getRowColumns returns more columns than expected

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#604]
// Dupe of Internal QA-91733
// jkong edit - updating client code to match + an example

The following client-code below should return a list with a single foo element, but instead, returns a list with 2 duplicate foo elements.

The explanation for why this bug pops up is:

> The bug makes sense, under the covers the two columns are not identical (they have references to the source column). The generated code strips out the source column when returning results, so you get two copies of the same thing. The workaround is to use a Set.

Table and Index Definitions:

```
private static void fooTable(Schema schema) {

        schema.addTableDefinition("foos", new TableDefinition() {{
                rowName();
                rowComponent("foo", ValueType.VAR_STRING);
                rowComponent("bar", ValueType.VAR_STRING);

                columns();
                column("columna", "a", ValueType.VAR_STRING);
                column("columnb", "b", ValueType.SHA256HASH);
            }
        });

        schema.addIndexDefinition("fooIndex", new IndexDefinition(IndexDefinition.IndexType.CELL_REFERENCING) {{
                onTable("foos");
                rowName();
                componentFromRow("bar", ValueType.VAR_STRING);

                dynamicColumns();
                componentFromRow("foo", ValueType.VAR_STRING);
            }
        });
    }
```

Client code (run inside a transaction `tx`):

```
FoosTable foos = SweepTableFactory.of().getFoosTable(tx);
FoosTable.FoosRow row = FoosTable.FoosRow.of("whatever", "key");
foos.putColumna(row, "hello");
foos.putColumnb(row, Sha256Hash.EMPTY);
return FoosTable.FooIndexIdxTable.of(foos).getRowColumns(
        FoosTable.FooIndexIdxTable.FooIndexIdxRow.of("key"))
        .stream()
        .map(c -> c.getColumnName().getFoo()).collect(Collectors.toList()); // returns 2x "hello"
```

**Comment by rhero** [comment]
We think the ways we could address this are:

1. Document the actual behavior better
2. Fix this specific case to be more intuitive to the user 
3. Rewrite the API entirely to be more intuitive to the user

We should do some more due diligence with devs using AtlasDB to see what would be most useful.

**Comment by gsheasby** [comment]
This is confusing, but not incorrect, behaviour. It could be a note in https://palantir.github.io/atlasdb/html/schemas/tables_and_indices.html somewhere.
