### ISSUE TITLE
Add tests to ensure that the lock service functions correctly given node failures

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#611]

**Comment by gsheasby** [comment]
PR #1450 - any others?

Currently testing network partitions.
TODO: Service failure.

**Comment by gsheasby** [comment]
This is done now, right @harrybiddle @gmaretic ?

**Comment by harrybiddle** [comment]
We have written and run the tests, but they are not all committed into the repository to run on a continued basis. I suggest we keep this ticket open to track they portion.

Sent from Email+ managed by MobileIron

On 16 Feb 2017 6:59:37 p.m., Glenn Sheasby <notifications@github.com> wrote:


This is done now, right @harrybiddle[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_harrybiddle&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=6qRMAc65Qp-Lp399U8vyK1Mvm716j-JVIkVplSo8h8Q&m=8dje7JQIun099cuINzTN8owMFeIwC57hlR6GBtV6dLk&s=1rBgB2yXDixrIf6WtXdRnXBiD75MtBW7tfjFqi2-6tE&e=> @gmaretic[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gmaretic&d=DwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=6qRMAc65Qp-Lp399U8vyK1Mvm716j-JVIkVplSo8h8Q&m=8dje7JQIun099cuINzTN8owMFeIwC57hlR6GBtV6dLk&s=HcRRMYH1Eh1G09VLDmdzzglzXeb-W1SdPGiJ8z-y6H0&e=> ?

**Comment by gsheasby** [comment]
The last thing left here is #1431 - tracking there and closing this one out.
