### ISSUE TITLE
Consolidate AtlasDB gradle utilities used by internal projects

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#612]
Several deployments have added gradle tasks to help them manage / dev with AtlasDB.  These should be consolidated into a set of tasks that are deployed with a Gradle plugin managed by AtlasDB + community.

For example, we need: ./gradlew generateSchemas

**Comment by jboreiko** [comment]
Associated with

**Comment by gsheasby** [comment]
@gracew raised this yesterday

**Comment by gsheasby** [comment]
`./gradlew generateSchemas` now exists, and we haven't had additional bumps for 3 months. Closing, can reopen if new requests come in.
