### ISSUE TITLE
Cannot create cross-schema transaction manager for in-memory DB

### ISSUE THREAD

**Issue by meditativeape** [palantir/atlasdb#616]
Creating cross-schema transaction managers is supported in the `TransactionManagers` class: https://github.com/palantir/atlasdb/blob/develop/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L93 It's useful for our product because some services split their Atlas table definitions across multiple schemas.
But the in-memory DB implementation does not provide this functionality, which makes testing hard: https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java#L82

**Comment by joelea** [comment]
Hey,

While this is not the most satisfying answer, my suggestion would be to use TransactionManagers.create with a valid config via new `InMemoryAtlasDbConfig()`. This will create all the schemas for you, and will be testing closer to the codepath you're using.

It's likely we'll be deprecating the other approach in the future.

**Comment by gsheasby** [comment]
Closing due to lack of response - we assume you've taken @joelea's advice.
