### ISSUE TITLE
Cassandra tracing should be easily configurable

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#624]
The process for setting up cassandra tracing is too complicated.  We should just move the configuration to be an optional part of the CassandraKeyValueServiceConfig.  For SA on the current method to getting this running: https://palantir.github.io/atlasdb/html/configuration/enabling_cassandra_tracing.html

**Comment by clockfort** [comment]
I agree. I made it outside of the KVS config framework originally because the KVS config framework at the time didn't provide live updates, and this was a critical feature need for this sort of debugging in prod. (and at the time it also worked with CQLKVS as well without too much code duplication)

I still would like to eventually put the same-ish feature in Postgres KVS (a la explain analyze) and Oracle KVS eventually (a la explain plan or autotrace or similar, which would obviate at least some need for Perf/ Stats pack EE addons in some places, I imagine).
Even so it's better off in the KVS config, even if adding extremely similar functionality will cause duplication in our configuration code.

**Comment by tpetracca** [comment]
Does the current framework actually support live updates, especially registering it when the file didn't previously exist live?  I agree that that's actually an excellent reason for it to not live in the KVS config.

**Comment by tpetracca** [comment]
Wait, I might be reading too much into it but your comment almost suggests that kvs configs live update which definitely isn't a thing.

**Comment by jboreiko** [comment]
This is likely to change given the possibility of switching to a separately deployable time/lock service which may also own a large portion of the config for the services.

**Comment by clockfort** [comment]
@tpetracca Yes, it does live file loading now, and yes, KVS prefs when your application uses the provider correctly can have live-updated settings.

**Comment by tpetracca** [comment]
^^ mind blown.  And I made good use of the live loading of atlas_tracing today, thus #631 
I'll try to address this soon, but it's not a priority given the improved clarity with that PR.

**Comment by gsheasby** [comment]
@tpetracca @schlosna  we believe discussions on this are ongoing; is there any other issue where we're tracking it?

**Comment by clockfort** [comment]
Feel free to make a different issue for this, but I think ideally this should be a KVS preference in your Atlas config, but iff Atlas starts supporting live updates for the Atlas config.

Some settings in it don't make any sense and are really broken if you allow live changes, and live updates to these would have to be disallowed, but many small ones are not, and for things like tweaking performance knobs and turning on logging and tracing, live updates are an order of magnitude better experience for interacting with Atlas on prod.

**Comment by clockfort** [comment]
Re: original more specific topic of this ticket, re: Cassandra tracing
We also plan on implementing a way to grab the Cassandra traces back to appear correctly tagged as part of our own traces, but it relies on a version of Cassandra that we don't ship to the field yet.

**Comment by gsheasby** [comment]
Isn't having a preference available in the config strictly better than not having it, even if it isn't live-updatable?

**Comment by jboreiko** [comment]
@gsheasby You can still set up the tracing, just not through the config.  I second the want for a live loading config, but I'm not sure that will be prioritized by our team in the near future.  Also what version of C* for the zipkin support?  @clockfort feels like we should slide to 3.0.X soon.

**Comment by gsheasby** [comment]
Therefore, it sounds like there aren't any actions left on this ticket. Closing, feel free to reopen if there's something actionable that I've missed. (Note: live-loading config feels like too far in the future to even have a ticket for it yet).
