### ISSUE TITLE
Under no circumstances should manually truncating a table be part of SOPs

### ISSUE THREAD

**Issue by j-baker** [palantir/atlasdb#635]
I've seen a few times now people have been having issues which have eventually been 'fixed' by truncating Cassandra tables (specifically _locks, although I never worked out why that one helped).

This is really really really bad, because it normalises people to the idea of truncating Cassandra tables fixing stuff. For example, I just saw a deployment truncate `_timestamp` (presumably they just confused names), and we can't expect FDEs to know enough about the Atlas TP to realise that's a terrible idea.

Instead we should be educating the approach of the PCloud Postgres default MOTD 'If you do anything not in this list without contacting support, you will have data loss and multi-day outages and it will all be your fault.' - but that can't happen whilst there are still things you can actually fix by truncating random tables with odd sounding names. Like, I can truncate _lock, why can't I truncate _timestamp?

**Comment by clockfort** [comment]
make a clear locks cli that asks the user if they shut down all of the running atlas-using services and then Does The Thing ?

**Comment by j-baker** [comment]
I'd be happy to ship that cli with my app. Perhaps we could also ship an appropriate MOTD with AtlasDB-Cassandra?

**Comment by gsheasby** [comment]
+1 to the CLI idea.

In general we should not be advising FDEs to do scary (especially destructive) stuff, especially when they might:
a) get confused and destroy the wrong data
b) get the impression, as you said, that this kind of thing is a "normal" thing to do

Ideally, Atlas should have a suite of CLIs that enables the FDEs to treat the underlying data store as a black box.

**Comment by rhero** [comment]
@j-baker are you okay with us creating a CLI (with docs) to do the truncating, or would you like to see additional logging/documentation?

**Comment by gsheasby** [comment]
The CLI has been created - is there anything left to do?

**Comment by tpetracca** [comment]
Don't think we should close until it's been used by someone successfully in the field.

**Comment by gsheasby** [comment]
That sounds like "to ship" to me. @rhero for SA.

Also, after the other fixes were released in 0.15.0, we hope that nobody will have to use this in the field.

**Comment by rhero** [comment]
Closing this out as we are getting rid of the "To Ship" pipeline, and we have deployed this, realized it was broken, and then re-fixed (verified on a full stack).
