### ISSUE TITLE
AtlasDB server: Have a cluster that can offer timestamps and locks to clients in multiple keyspaces

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#645]

**Comment by tpetracca** [comment]
What is the HA story here?  Is the idea that timestamp and lock are super light weight and can easily be spun up if they go down or are we running 3x of these that leader elect?

**Comment by joelea** [comment]
Sorry, by one server I mean one cluster - have updated the title.

**Comment by gsheasby** [comment]
We're designing a solution for this, and have scheduled an internal review for next week.

**Comment by rhero** [comment]
We should also address internal ticket PDS-45384 as part of this if at all possible.

**Comment by jeremyk-91** [comment]
Eventually a solution to this will need to address #1292, #1310, #1315 and #1320.
