### ISSUE TITLE
As a client of Atlas, I want Atlas sweep to robustly handle cleaning up stale data

### ISSUE THREAD

**Issue by shashiadi** [palantir/atlasdb#655]
1. People aren’t running sweep because it’s disabled by default
2. When sweep errors out due to a timeout due to a large row it’s not entirely clear from the error that it’s actually because of a large row and not because of a regular timeout

Would be great if sweep could also detect untenably large rows (either because sweep hasn't run in a while, or because of zany usage), skip them, and report at the end and suggest manual user action to handle the rows. Would be even greater if sweep just dealt with the problem!

**Comment by clockfort** [comment]
Specifically, this user had an issue with sweep choking on (one key, many historical versions each of a large size); sweep also currently chokes on (one key, many columns of large size).

**Comment by jboreiko** [comment]
First step of test additions: #710
