### ISSUE TITLE
We should create a globally consistent OBJECT_MAPPER

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/atlasdb#665]
One for YAML, one for JSON?

Take a look at AtlasDbConfiguredCommand, and AtlasDbConfigs. Problem is we can serialise and deserialise things in different ways depending on how the object mappers are set up.

**Comment by schlosna** [comment]
+1 as the Atlas CLI cannot currently deserialize certain configs.

**Comment by gsheasby** [comment]
Duplicate of #664
