### ISSUE TITLE
KVS Migration CLI

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#666]
There should be a CLI that will allow AtlasDB users to migrate between key value stores.

**Comment by tmgordeeva** [comment]
KvsMigrationCommand in the atlas cli should cover this. Is there anything else we need on it?

**Comment by rhero** [comment]
Nope, caught up with @jboreiko on the history of this as well. We can look into improving testing once customers start doing more migrations, but right now it appears migrations are specific to only one internal product.
