### ISSUE TITLE
Upgrade the Postgres JDBC Driver once 9.4.1209 is released

### ISSUE THREAD

**Issue by schlosna** [palantir/atlasdb#669]
Upstream Postgres JDBC driver fix https://github.com/pgjdbc/pgjdbc/pull/603 merged in https://github.com/pgjdbc/pgjdbc/commit/ab2a6d89081fc2c1fdb2a8600f413db33669022c and should be in the next pgjdbc release 9.4.1209 coming soon http://comments.gmane.org/gmane.comp.db.postgresql.jdbc/23052

@tmgordeeva for SA

**Comment by schlosna** [comment]
Postgres JDBC driver version 9.4-1209 was released on July 18, 2016, see https://jdbc.postgresql.org/download.html and changelog https://jdbc.postgresql.org/documentation/changelog.html#version_9.4.1209

**Comment by gsheasby** [comment]
@tmgordeeva - are we ready to take this?

**Comment by schlosna** [comment]
@gsheasby -- @rjullman bumped to 9.4.1209 in 5cb935ab for #722 so we can probably close this for now. Note that the latest is 9.4.1211 https://jdbc.postgresql.org/documentation/changelog.html#version_9.4.1211 released a few weeks ago and 9.4.1212 should be released soon-ish https://github.com/pgjdbc/pgjdbc/milestone/5 .

I'm not sure there is a pressing need to bump beyond 9.4.1209 at this point, so I think we can close this out.
