### ISSUE TITLE
Author CI extension to push changes to internal products

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#674]
Due to the restrictions entering internal networks this would have to poll for changes in AtlasDB and push the corresponding changes to internal products.  This would have the joint benefit of improving our response time to breaking changes as well as helping keep most products rolling forward by reducing the work require to update AtlasDB.

**Comment by gsheasby** [comment]
@jboreiko did you start this?

**Comment by jboreiko** [comment]
Well, this can take several forms as you can imagine.  I started work to automate this with a script (tacked on to the side of the version tracking script) that would push branches up to github repos with the latest version of atlas.  This was part of golden time.
