### ISSUE TITLE
Hikari configuration not being picked up by DbKVS

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#675]
Although I’m configuring the socketTimeoutSeconds and connectionTimeoutSeconds in my Atlas configuration, Hikari logs report that the datasource socketTimeout, connectTimeout, and loginTimeout properties are all zero. Based on my configuration they should be 5, 30, and 30, respectively and by the default Atlas configurations they should be 45, 120, and 120 (see ConnectionConfig in Atlas). These need to be non-zero since we’re running on RDS and will otherwise get stale connections on a failover event.

**Comment by gsheasby** [comment]
We reproduced this on 0.8.0, but it's already been fixed on the latest develop. The open PR above has some tests to ensure that this sorry state of affairs does not reoccur.
