### ISSUE TITLE
Hikari not respecting set minConnections

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#676]
Although Hikari is correctly picking up my non-default minConnections of 32, we’re seeing the RDS sit idle around 30-40 connections. Since we have three servers, we would expect a minimum of 32 * 3 = 94. While it’s able to scale up when under load, this causes temporary performance degradation, as it has to establish a lot of connections at the same time to match the demand.

**Comment by jboreiko** [comment]
After a cursory investigation the minConnections value is being set in the hikari config.  This leads me to believe that Hikari is not respecting the minConnections.  This can be investigate further if it is shown to cause connection start up latency problems.  Otherwise it will be deprioritized.

**Comment by gsheasby** [comment]
Closing as we have not observed any issues.
