### ISSUE TITLE
CassandraKVS#getRange() uses getRangeWithPageCreator inefficiently

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#677]
```
    // TODO: after cassandra change: handle reverse ranges
    // TODO: after cassandra change: handle column filtering
    @Override
    @Idempotent
    public ClosableIterator<RowResult<Value>> getRange(TableReference tableRef, final RangeRequest rangeRequest, final long timestamp) {
        return getRangeWithPageCreator(tableRef, rangeRequest, timestamp, readConsistency, ValueExtractor.SUPPLIER);
    }
```

The `getRangeWithPageCreator` method retrieves the entirety of a row in cassandra (which is the entire history of the cell) only to have the remaining history disregarded by the `ValueExtractor.SUPPLIER` provided by getRange().  This means that getRange is needlessly loading the entire objects history (which can be particularly expensive if the cell is mutated often).

@clockfort / @tmgordeeva for confirmation / context

**Comment by gsheasby** [comment]
Linked to sweep, #655

**Comment by jboreiko** [comment]
We should consider examine this as we look at improvements that can be made to the cassandra kvs.

**Comment by gsheasby** [comment]
Would need to refactor the world to do this. Plus this code has limited life because it'll go away when we switch to CQL. Not going to fix this specifically unless we have to change this code for some other reason.
