### ISSUE TITLE
Expose Dropwizard metrics for transaction / KVS layers

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#689]
Internal products have been making use of dropwizard metrics to expose baseline runtime numbers in production / test environments.  I'm wondering if it would be valuable to expose atlas operations (transaction / KVS runtimes) through applications metrics.  This would not be expected to replace zipkin style tracing, but would offer a less granual solution in much less time.  It would allow applications to observe the most painful portions of their AtlasDB use but not allow them much structure to dig into the particular calls causing the pain.  @schlosna for additional ideas.

**Comment by schlosna** [comment]
Big +1 to this, we have Atlas transaction manager wrapped with metrics proxies in several apps, and this would allow finer grained metrics on the KVS interfaces. We can probably open source the library we're using for that which builds on Dropwizard metrics & HDR histogram. We probably need a mechanism to inject a DW MetricRegistry, which might complicate things a bit with 3rd party dependency versioning, but should be workable.

**Comment by gbrova** [comment]
Does adding tracing give us what we need here?

**Comment by schlosna** [comment]
No, tracing gives you information about individual requests, but we don't expose mechanisms for gather instrumented metrics at the transaction and KVS levels, which are especially useful in quick aggregate view to see what read/write paths are being used and their response time distribution. Basically we need a callback to register the KVS and transaction interfaces with our existing instrumentation that hooks into Dropwizard metrics.

**Comment by rhero** [comment]
Fixed in #1429. Closing out.
