### ISSUE TITLE
Native UUID support

### ISSUE THREAD

**Issue by leeavital** [palantir/atlasdb#69]
Doing range scans with UUID row components is painful, because VAR_STRINGS shouldn't be range scanned. You either have to map UUID <=> (Long, Long) or UUID <=> (SHA256 hash)

Since UUIDs partition evenly, it makes sense to add a native type that supports range scanning.

**Comment by punya** [comment]
@leeavital is this something you can contribute a fix for?

**Comment by carrino** [comment]
Since they are all the same length, it turns out they will range scan in order; but they will still all start with 0x10 so they will hotspot on the node that owns that range.

**Comment by markelliot** [comment]
How many bytes does the ordered partitioner examine to determine node location?

**Comment by carrino** [comment]
Well I think the ring info is 16 bytes for cassandra. But unless you
special case certain subranges (like (1, objId)) the practical limit is
like one or 2 bytes just because you won't have that many kv nodes

**Comment by markelliot** [comment]
Do virtual nodes make this better?

**Comment by carrino** [comment]
You could special case 16 and hand out a lot of subranges that start with
16 to handle this case.  But that seems like overkill when you could just
do the (long, long) encoding, or we can just fix this bug directly like
sha256.

**Comment by markelliot** [comment]
not sure long/long encoding fixes it? I guess we could invert the MSB/LSB to help increase the entropy of the first few bytes.

**Comment by carrino** [comment]
It looks like the standard layout for UUID is actually ok

 * <p> The layout of a variant 2 (Leach-Salz) UUID is as follows:
 *
 * The most significant long consists of the following unsigned fields:
 * <pre>
 * 0xFFFFFFFF00000000 time_low
 * 0x00000000FFFF0000 time_mid
 * 0x000000000000F000 version
 * 0x0000000000000FFF time_hi
 * </pre>

The top 4 bytes are the time in 100ns.  This means that the top 4 bytes
rolls over every 7 min or so.  This is actually pretty reasonable.  This
means that at a given point in time all writes will be going to one node,
but the load will be pretty evenly distributed over a long period of time.
And it will support range scans.

**Comment by markelliot** [comment]
Ok, so I have most of a commit for this I think. I don't quite understand what the hydrateFlipped method call in the enum is supposed to do, and obviously I need to figure out how to test my impl.

**Comment by carrino** [comment]
flipped is just xor the whole thing by -1.  It is used for reverse ordering

**Comment by markelliot** [comment]
Check out PR #90

**Comment by joelea** [comment]
It looks like this got fixed - please let us know if there's still an issue here.
