### ISSUE TITLE
Provide an open-source cassandra docker image for testing with atlasdb

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#698]

**Comment by hsaraogi** [comment]
This has been published at: https://hub.docker.com/r/palantirtechnologies/docker-cassandra-atlasdb/ . @jboreiko, should we close this issue?

**Comment by jboreiko** [comment]
If we want to close this we should switch our testing to use the new public build (if we haven't already).

**Comment by rhero** [comment]
@hsaraogi can you make sure we're using the new docker image?

**Comment by hsaraogi** [comment]
Update the repo and ensure we have a single cassandra image reference for all tests.

**Comment by rhero** [comment]
@hsaraogi @jboreiko have we done this? Is this at all related to #1112 ?

**Comment by jboreiko** [comment]
This is fulfilled by https://github.com/palantir/docker-cassandra-atlasdb that we now use on develop.  There is a follow up task here of getting internal products to use it for their testing.  We will need to figure out how to version it first.  At the moment we only publish a 'latest' and this doesn't allow us to differentiate between the actual cassandra versions backing the docker image.
