### ISSUE TITLE
The timestamp server being used by an atlasdb client should always be available for CLIs to use

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#705]
#593 is one approach to this.

A simpler approach might be to always register the timestamp and lock endpoints, even when leader election is turned off.

**Comment by schlosna** [comment]
Need to be cautious with this route to make sure that if multiple clients are started, leader election must be enabled and quorum is defined in reasonable fashion.

**Comment by jboreiko** [comment]
This was resolved by #708
