### ISSUE TITLE
CLIs should be able to use the same configuration as their servers

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#706]
Having to rewrite the configuration for a CLI when the server it is working on already has all this information is painful.

**Comment by joelea** [comment]
@tpetracca

**Comment by tpetracca** [comment]
@SerialVelocity @jboreiko and I discussed this and other leader block configuration changes today and I'm going to start an internal page describing thoughts.

**Comment by jboreiko** [comment]
Related to work being done here - #708

**Comment by gsheasby** [comment]
Done as part of #696
