### ISSUE TITLE
Rework Cassasndra Configuration (Passwords/Defaults/Docs)

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#73]
Passwords in CassandraKeyValueServiceConfig.java should probably be read from a hash? Also, maybe the default instance of the config should be somewhere else (it is mostly used in testing)?  Default values should be documented for context.

**Comment by joelea** [comment]
@rjullman is this still a thing that needs to happen? Is anyone asking for it?

**Comment by joelea** [comment]
Closing this until we have some more information.
