### ISSUE TITLE
Default Intellij Configuration Mistakes

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#74]
By default intellij configs created with ./gradlew intellij mess up organized imports.

Most notably:
"Class count to use import with '*'" is low (should be as large as possible)
"Names count to use static import with '*'" is low
"Packages to Use Import with '*'" has entries

**Comment by joelea** [comment]
Is this still an issue?

**Comment by joelea** [comment]
Closing this till we have more info.
