### ISSUE TITLE
Developers should be warned earlier when creating a table name which is too long

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#747]
A relevant cassandra issue: https://issues.apache.org/jira/browse/CASSANDRA-8973

**Comment by clockfort** [comment]
48-character cassandra limit is the least of your worries, the 30-character oracle limit is considerably worse. (Especially because, since we keep other things in the same Oracle DB, our KVS (at least used to?) prepend all atlas tables with 'pt_met_' bringing the limit down even further)

Before OSS atlas, we mapped all namespaced tablenames with a KVS wrapper that went through a cached translation layer between (real tablename) --> (made up shortened tablename), specifically to get around length issues as well as allowing funky characters / unicode magic / consistent case sensitivity / etc.
We dropped it for OSS because a lot of people disliked looking at their database and seeing a bunch of cryptically named tables.

**Comment by joelea** [comment]
Sounds like we're going to have to do something similar then, that oracle limit is painful. I really don't want to run into the situation where a product tests against postgres, tells someone they can use cassandra and then absolutely nothing works without giant code changes.

Thanks for the info on the old version.

**Comment by jboreiko** [comment]
@gbrova to own gathering all table naming tickets, here one to start with -> #419

**Comment by gbrova** [comment]
Quick comment on the discussion above: if we decide to implement some kind of mapping, the mapped values don't have to be cryptic. For example, this scheme could map tables to legal, not-cryptic names shorter than `n` characters:

1. convert to lowercase and strip all disallowed characters
2. take the first `n-5` characters. 
3. if there is already a table with that name, append `#####` (the next available number between 0 and `99999`). This works assuming schemas have <100,000 tables; we could use a more complex scheme with variable postfix length if we need to relax that assumption.

**Comment by gbrova** [comment]
This represents a subset of the (more general) #419 ("Document and test KVS table name contract"). 

Not necessarily a duplicate though - it could still be valuable to warn early, if we don't want to prioritize the more general solution discussed above (which would be a breaking change and probably require a schema migration).

Note that #419 is in turn represents a subset of the work required to accomplish #385 ("have a well defined KVS specification so we can write general KVS agnostic code").

**Comment by jboreiko** [comment]
@tjwilson90:
Oracle is polite enough to fail if you try to create a table with more than 30 characters. Postgres will instead silently truncate to 63 characters.

This is mostly ok as long as the truncation doesn't cause any conflicts. Any attempts to interact with the table will truncate the table name and always find the right table.

If there is a conflict, this causes much badness.

**Comment by rhero** [comment]
@hsaraogi @jboreiko - is this fixed or enforced now by chance? Just wondering if we managed to address this with the Oracle changes.

**Comment by jboreiko** [comment]
Nope, not fixed or enforced.  Still need to come up with some rules around this.  Not sure it's considered very high priority as people aren't really making new tables.  Once schema migrations become more popular we might want to consider prioritizing this.

**Comment by rhero** [comment]
Closing this out since it's been referenced on #419 a few times and we'll probably want to get to this when we enforce table name contracts more generally.
