### ISSUE TITLE
Revisit compile.sh

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#75]
proto/compile.sh is not good for regenerating protos (maybe this is not the intended use) for the following reasons:
* it regenerates build.gradle (losing important config)
* it does not handle protos that are not in their own project (e.g. PaxosPersistence.proto and  ProfilePersistence.proto)
Perhaps a new script should be created that hardcodes what to compile where.  Probably better is to have all autogenerated code generated by gradle (and not have to be checked in)?

**Comment by joelea** [comment]
Is this still an issue?

**Comment by joelea** [comment]
Closing this till we have more information.
