### ISSUE TITLE
AtlasDbConfig should have strict and documented checks

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#790]
Three major pieces to this ticket:
- [x] all valid configurations should be documented with an example
  - no leader block (formerly embedded)
  - leader block
  - timestamp / lock service (remote)
- [x] no other configurations should be allowed to be constructed (ie enforce with @check)
- [x] deprecated configurations should throw warnings
  - no lockLeader specified

**Comment by gsheasby** [comment]
Appears to have been partially solved by #842; I am building on this work.

**Comment by gsheasby** [comment]
Pushed some docs changes and validation. For the "throw warning", do you just mean log a warning?

**Comment by gsheasby** [comment]
Added a log when lockCreator() is accessed using the default.

**Comment by gsheasby** [comment]
PRs merged. Closing out.
