### ISSUE TITLE
LockServiceTest is an abomination

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#810]
The tests in LockServiceTest test many things, with a bunch of `Thread.sleep()`s thrown in. In addition, the proliferation of `Assert.assertX(...)` means that test errors on circle are impossible to interpret (they just say "Assertion error").

This test class should be refactored so that each piece of behaviour is tested separately.

Currently, there are 227 instances of `Assert.assert`, and only 22 of `@Test`.

**Comment by gbrova** [comment]
This class also contains some flickering tests.

**Comment by gsheasby** [comment]
We'll clean this file up when we have to touch it for some other reason.
