### ISSUE TITLE
AtlasDB starts with single node failure of Cassandra

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#819]
We should have automated test coverage for AtlasDB clients attempting to connect to a 3-node Cassandra cluster, and one node is unavailable. AtlasDB should be able to startup and gracefully handle a Cassandra node failure.

We haven't observed any issues with this in practice, but it is not covered by automated testing at the moment.

**Comment by gsheasby** [comment]
Remaining tasks (not solved by #927):

- [ ] Verify deletes don't work with a node down (but do work with all nodes up)
- [ ] Gets work when the node to which the query is directed to is down (with large transaction time)
- [ ] Deletes work when the node to which the query is directed to is down (with large transaction time)
- [ ] Gets work when a node to which the query is not directed to is down (with small transaction time)
- [ ] Deletes work when a node to which the query is not directed to is down (with small transaction time)
- [ ] See if we can get giraffe working locally as well as on circle
- [ ] Move docker-compose files away from the root directory atlasdb-ete-tests - e.g. into atlasdb-ete-tests/docker/compose.

**Comment by rhero** [comment]
Moving this out of "In Progress". I don't think we're going to get to any of these tasks in the near future. All of the delete tasks don't make sense to me - we want them to not work when a node is done, but later you say we do want them to work when a node is down. We closed out #332 as not a priority, so I would actually suggest we close this as well.

Thoughts?

**Comment by jboreiko** [comment]
I would leave this at the discretion of @harrybiddle as this seems to fall strictly under HA testing.  If we expect to run against degraded cassandra clusters this testing will be necessary and seems to be partial done?  The question is now utilizing the degraded cassandra cluster testing suite we have to confirm what operations do and don't work.  If this is deprioritized for other HA work than that is fine with me.

**Comment by rhero** [comment]
This is covered by #1045 and #1152. Closing out.

@harrybiddle for SA.
