### ISSUE TITLE
Document usage of KvsMigrationCommand

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#860]
We have a KVS Migration CLI that lives in `atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java`, but we don't mention it on our docs. We should document the basic usage on our [Command Line Utilities](https://palantir.github.io/atlasdb/html/cluster_management/clis.html) page.

**Comment by hsaraogi** [comment]
It is likely on our internal docs.

**Comment by rhero** [comment]
@shashiadi @j-baker do you guys think you'll start using our migration CLI (per PDS-45271)? If so, we can try to get to this sooner than later.

**Comment by sarahfbeller** [comment]
Filed MP #860 to track moving to the OSS Atlas CLI.

**Comment by rhero** [comment]
This is documented, but I would like to improve this a bit now and move it to its own page. Existing docs are here: https://palantir.github.io/atlasdb/html/cluster_management/clis.html#migrate. 

For SA, #1197 is blocking moving to the AtlasDB migration CLI.

**Comment by rhero** [comment]
I've made updates to the docs here and the internal product now delegates to our CLI. Closing out.
