### ISSUE TITLE
Implement logback tagging everywhere

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#867]
From @clockfort: Implement proper logback tagging everywhere so that we can just tag things that have possible customer data in them and all of the logging infra does the right thing with that.

**Comment by gsheasby** [comment]
Copied from a PR here: https://reviewable.io/reviews/palantir/atlasdb/837#-KPyXCZpD7d6iM3qOCGp-r1-1486:-KQ84aw_eM0fwlsFVdpH:b-d5uuav

**Comment by gbrova** [comment]
Next action: figure out what and how to tag so we are in sync with the internal team that requested this. 

@punya

**Comment by punya** [comment]
FYSA @mnazbro.

**Comment by tpetracca** [comment]
Generally I think we should probably never ever be printing cell contents, like we do when gets are are rather large (https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L930).  In a case like that we definitely still need the rowkey for debugging purposes, but even then that should be annotated as "having data" because people might store sensitive information in row keys or column names.

Related is internal PDS-45524

**Comment by rhero** [comment]
I'm in agreement with that, and don't see a need to include actual cell data. We should probably do a cursory look through the code base and address the ones we find. I don't know how much lift it would be to look over every log message, but probably makes sense to do ERROR and WARN first.

**Comment by gsheasby** [comment]
FYI - here's roughly how many log messages we have (grepped for .error( and similar):
Error = 208
Warn = 95
Info = 95
Debug = 72

**Comment by jboreiko** [comment]
@punya as discussed in #837 it would be great to be able to mark lines using tags.  I believe the only blocker at this moment is how we should be doing this tagging.  Is there some standard we should be following here?

**Comment by punya** [comment]
@jboreiko I'm not aware of any OSS standards in this space. @mnazbro and @griechel are working on a spec for this, but in the meantime you could make headway by picking something simple within AtlasDB, which we could refactor (and/or be inspired by) once the standard is ready.

**Comment by gsheasby** [comment]
Related to #1117

**Comment by rhero** [comment]
@hsaraogi or @griechel - did we decide on a standard here from your visit? One concrete place we could add logback tagging would be in #1416 where we could have user created content.

**Comment by mnazbro** [comment]
@rhero Due to time and resource constraints we have not yet decided on a standard way of tagging potentially sensitive data.
