### ISSUE TITLE
github release pages have bad UI

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#874]
old versions of releases use a download-button image that gets auto-updated to the latest release version, leading to a button that says "Download {latest version}" that links to the older, locked-in version you expected.

https://github.com/palantir/atlasdb/releases/tag/0.11.0 for instance

**Comment by gsheasby** [comment]
+1, I've noticed this.

**Comment by gbrova** [comment]
Looked at this briefly, couldn't find a bintray URL for older download images. (This makes sense to me, github badges are usually not static). 

I can go through and add manual links (without the fancy images) unless anyone has objections / other thoughts.

**Comment by gbrova** [comment]
Looks like this is fixed. Thanks @joelea
