### ISSUE TITLE
LMDB as KeyValueService

### ISSUE THREAD

**Issue by krisskross** [palantir/atlasdb#89]
Have you tried LMDB as a KeyValueService? Would you be interested in such a contribution?

https://github.com/deephacks/lmdbjni

Thoughts?

**Comment by carrino** [comment]
Key value services are pluggable, so I think a separate project would be the best place for this code to live.  Sounds like a great single node KV store alternative to rocksdb.

**Comment by carrino** [comment]
This is a good template for what the KV plugins look like if you want to give it a go: https://github.com/palantir/atlasdb/tree/develop/atlasdb-jdbc

**Comment by joelea** [comment]
This isn't something we'll be adding as part of core atlas, but as @carrino said they are pluggable if someone wants to write one.
