### ISSUE TITLE
Move everything to use Dagger

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#899]
It feels weird to me that we use Dagger for some things and not others.  For example, CLI uses it but Console does not (see https://github.com/palantir/atlasdb/blob/develop/atlasdb-console/src/main/groovy/com/palantir/atlasdb/console/module/AtlasCoreModule.groovy#L144).

**Comment by gbrova** [comment]
@rjullman We're interested in picking this up, though we are struggling with Dagger's dependency footprint ( #905 ).  Unsure if we want to move everything to the Dagger code path.

**Comment by tpetracca** [comment]
@clockfort I believe the scope of this issue is more broadly "move everything to dagger" or "centralize on a single way of instantiating transaction managers and atlas services" per https://github.com/palantir/atlasdb/pull/921#discussion_r78086236

**Comment by gsheasby** [comment]
TransactionManagers.create() contains a bunch of logic that could/should be encapsulated in dagger.
