### ISSUE TITLE
Investigate use of AbstractTransaction.tempTables

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#915]
Looking at the code it looks like tempTables may be dead code.  Is it safe to kill this stuff?

**Comment by tpetracca** [comment]
I'm pretty sure that it's dead code.  We could remove all references of it and then the next question becomes, is it safe to delete the OnlyWriteTempTablesTransaction class given that would technically be a breaking change for any consumers of it.

**Comment by tpetracca** [comment]
Nvm we should never actually expose OnlyWriteTempTablesTransaction, it was just getting used by SnapshotTransactionManager.runTaskReadOnly which can just directly use the OnlyWriteTempTablesTransaction's delegate instead.

**Comment by clockfort** [comment]
Yes, since DbKVS no longer uses them we can delete this feature. Our internal products also do not use this feature. It is safe to delete. 
I think I actually started to do parts of this delete previously and was not very thorough / didn't care at the time.
