### ISSUE TITLE
Flaky test: LazyClosableIteratorTest

### ISSUE THREAD

**Issue by gbrova** [palantir/atlasdb#935]
Message: 

```
java.lang.RuntimeException: Failure during run 66
```

Failed builds: 
- https://circleci.com/gh/palantir/atlasdb/2612
- https://circleci.com/gh/palantir/atlasdb/2655
- https://circleci.com/gh/palantir/atlasdb/2693
- https://circleci.com/gh/palantir/atlasdb/2789
- https://circleci.com/gh/palantir/atlasdb/2790

**Comment by gsheasby** [comment]
https://circleci.com/gh/palantir/atlasdb/2790

**Comment by gbrova** [comment]
Attempted fix in #1020; reopen if the problem recurs after that merges.

**Comment by gsheasby** [comment]
Not flaking anymore! :)
