### ISSUE TITLE
Flaky test: CassandraKeyValueServiceIntegrationTest

### ISSUE THREAD

**Issue by gbrova** [palantir/atlasdb#936]
Message: 

```
java.lang.IllegalStateException: Another process cleared our schema mutation lock from underneath us. Our ID, which we expected, was 4360666735259010588, the value we saw in the database was instead 3920376578768493825.
```

Failed builds: 
- https://circleci.com/gh/palantir/atlasdb/2592
- https://circleci.com/gh/palantir/atlasdb/2692

Only observed this once, but flagging because it looks potentially scary and because it might be related to #815

**Comment by gsheasby** [comment]
Not flaky any more! 🌲
