### ISSUE TITLE
Port sweep documentation to OSS Atlas

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#955]
There is some good documentation for sweep available internally.

The goal of this ticket is to:
* Port the documentation to OSS atlas (will need to remove internal references)
* Meanwhile, gain understanding of how Background Sweep should operate, with a view to later refactoring the code (#956)

**Comment by rhero** [comment]
Is this issue now satisfied by these docs? https://palantir.github.io/atlasdb/html/cluster_management/sweep.html

**Comment by gsheasby** [comment]
Yes.

**Comment by gsheasby** [comment]
Fixed by PR #957
