### ISSUE TITLE
Handle Schema Mutation Locks in Cassandra pre-CAS-support Better

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#969]
Current way we do this is by checking for CAS support in Cassandra and if it doesn't exist we just use a java level lock and log a line saying that we're doing so.  This will protect us from multiple concurrent threads creating tables within the same java client, but not across many (which is the likely case when running multiple Atlas clients).

**Comment by j-baker** [comment]
Is it not the case that the versions of C* that don't have CAS also don't have the bug that caused the schema mutation lock to be required?

**Comment by tpetracca** [comment]
Yea ^^.  I think this issue should really be about finding out what exact version of Cassandra the bug was intro'd in (I think it was a minor version update in 2.[012].X) and just having a check compare bug existence against CAS support and only error in scenarios where we have the bug but no CAS support (which I think our research will tell you is non-existant)

**Comment by hsaraogi** [comment]
Not prioritizing as we will move away from old C*.
