### ISSUE TITLE
Overflow migration for Oracle is not required

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#977]
Overflow stuff is a way of defining where large data cells in Oracle go (over some configurable threshold size), which allows Atlas to keep range read performance up and it looks like we use a DB sequence to assign unique IDs to the overflow segments.

OSS Atlas did not have support for oracle in the past and does not need to support migration from ``singleOverflowTable`` to an overflow table per table. We will start with having overflow tables for each table separately.

**Comment by jboreiko** [comment]
We will need to maintain upgrade capability until internal products have guaranteed that it is no longer needed.  See comments on associated PR for more details.
