### ISSUE TITLE
CLI and DW Bundle Should Work the Same

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#995]
Internal PDS-45797

DW prevents you from running CLI without a leader or lock/timestamp, but the CLI doesn't.  CLI should prevent you as well.  It resulted in us running embedded timestamp service for the CLI (which I thought also shouldn't happen without --offline) and hitting

```
This server is no longer usable as there appears to be another timestamp server running.
! com.palantir.timestamp.MultipleRunningTimestampServiceError: Timestamp limit changed underneath us (limit in memory: 1252586782). This may indicate that another timestamp service is running against this cassandra keyspace!
```

**Comment by gsheasby** [comment]
This caused #1386 - we can probably fix both at once, and should probably actually do it soon.

**Comment by gsheasby** [comment]
We should make sure that SweepCommand isn't affected by this issue.

**Comment by gsheasby** [comment]
Closing as we're not likely to get to this any time soon, and we're moving towards a non-CLI world.
